bootc-dev/bootc

- lib/Cargo.toml
I just pushed this out, should fix the `cargo deny` failures.
> Use published ostree-ext 0.10

- .dockerignore
- .gitignore
- Makefile
- ci/Dockerfile.ci
- ci/Dockerfile.fcos
- ci/run-kola.sh
- tests/kolainst/basic
This test will
- build a container image derived from FCOS, injecting bootc-under-test into it
- Schedule a separate container derived from coreos-assembler which has a reference to that container injected via https://docs.ci.openshift.org/docs/architecture/ci-operator/#referring-to-images-in-tests
- Run the stable FCOS base image via kola (qemu), injecting the target oscontainer
- Execute a basic test that just verifies `status --json` today
However, in the future we can change the build system to generate multiple container images, and test upgrades, rollbacks, etc.
> Add initial CI infrastructure designed for Prow

- lib/src/cli.rs
- lib/src/status.rs
- lib/src/utils.rs
If one does any machine-local layering/overrides via rpm-ostree, we really should error out if one does `bootc upgrade`; otherwise we'll just lose their changes.
This is a bit of an ugly hack; what would be more elegant is to add something like a clear `owner` flag into origin files, and have rpm-ostree flip that on if it needs to take over.
But for now, let's do this to avoid more confusion.
> Cleanly display/error if origin is rpm-ostree owned

- lib/src/cli.rs
This is a bug in the ostree Rust bindings, it can't express the difference between a zero-length array and an unset array.
And if we provide a zero-length array, ostree will happily remove all other kargs.
> Use stage_tree_with_options

- lib/src/cli.rs
This way we won't leak state like rpm-ostree packages from a previous one.
> switch: Always create a new origin

- lib/src/cli.rs
When we added logic to prune previous containers, we broke switching from an ostree remote + ref.  We need to parse the ref to handle the remote.
Closes: https://github.com/containers/bootc/issues/19
> switch: Fix changing from an ostree remote

- .github/workflows/autovendor.yml
- cli/Cargo.toml
Add configuration and a GH action post-push which automatically generates a vendor tar.
> Enable `cargo vendor-filterer`

- lib/Cargo.toml
- lib/src/cli.rs
This uses the new ostree API to verify we're in a compatible SELinux domain.  Otherwise, it's a really evil trap because things *seem* to work fine but will just explode in the case when trying to do a major policy update.
> Update to ostree-ext 0.10.1, add SELinux verification

- ci/run-kola.sh
This is needed to support fetching the image from the registry.
> ci/run-kola: Support pull secret for running in Prow

- .github/workflows/ci.yml
- lib/Cargo.toml
- lib/src/cli.rs
- lib/src/lib.rs
- lib/src/privtests.rs
- lib/src/status.rs
status: Don't error out if not booted
For now, just print out nothing.  This helps a future integration
testing scenario.
---
Add an `internal-tests run-privileged-integration`
Add a feature to enable internal tests.  I originally started
by matching
https://github.com/ostreedev/ostree-rs-ext/commit/6543c855580da3a3f2a85bc8b4a294b4c92c2829
but since here the binary is really end user facing and not just
a demo, we shouldn't enable the feature by default.
If in the future we split off the tiny CLI bit out of the workspace,
then we could auto-enable but that seems not worth it.
---
> Add an `internal-tests run-privileged-integration`

- lib/Cargo.toml
- lib/src/cli.rs
- lib/src/lib.rs
- lib/src/reexec.rs
- lib/src/status.rs
status: Use `if` instead of `.then(||)`
It's equally clear and avoids clippy lint conflicts between different
Rust versions.
---
cli: Add some error prefixing
On general principle.
---
Add a `reexec` helper
Prep for the `install` path where we will use this in
more ways.
---
> Small prep patches for `install`

- .cargo/config.toml
- .copr/Makefile
- .github/workflows/packaging.yml
- Cargo.toml
- Makefile
- cli/Cargo.toml
- contrib/packaging/bootc.spec
- xtask/Cargo.toml
- xtask/src/xtask.rs
First, this adds `cargo xtask` following
https://github.com/matklad/cargo-xtask/
We use this to write "external glue scripts" in Rust, not bash. Specifically we now have e.g. `cargo xtask vendor` which just wraps running `cargo vendor-filterer`.
Then build on that and add `cargo xtask package-srpm` which generates a `.src.rpm`.
And build on that by adding the requisite glue to have Fedora's COPR be able to understand it, so that we can get auto-built and shipped packages there.
This will make trying out bootc a bit easier.
> Add `cargo xtask` and packaging infrastructure

- lib/src/cli.rs
- lib/src/reexec.rs
The rexec logic was hardcoded to run `unshare -m`; move that bit into the caller so the core re-exec does literally just that.
Prep for other re-exec callers in the install code.
> reexec: Generalize a bit

- lib/src/cli.rs
- lib/src/install.rs
- lib/src/lsm.rs
- lib/src/reexec.rs
install: Make `/tmp` mount idempotent
Just so that the output of `findmnt` looks cleaner.
---
install: Always mount selinuxfs *before* install_t re-execution
My changes to ensure `install_t` actually re-broke the labeling
on `/etc`, because we were mounting selinuxfs *after* the
re-exec.
Reorder and clean up things so that we always do the mount
before the re-exec for install_t.
---
Add more debug/trace logs
This helped me debug a selinux regression.
---
> Install fixes

- lib/src/install.rs
- lib/src/task.rs
install: Init ostree repo more quietly
---
install: Quiet output of mkfs.vfat and ostree repo init
Just to make the install process look nicer.
---
install: Write `/etc/fstab` entry for `/boot`
So that things work on reboot by default.
---
> Install cleanups

- .github/workflows/ci.yml
- lib/src/cli.rs
- lib/src/privtests.rs
- lib/src/status.rs
I typed `bootc status` in a container and got an unhelpful error. Print something more useful and add integration tests for this scenario.
> cli: More gracefully handle client commands in a container

- .github/workflows/ci.yml
- lib/Cargo.toml
- lib/src/cli.rs
- lib/src/lib.rs
- lib/src/lsm.rs
- lib/src/utils.rs
The install code greatly increases the scope of this project.  Not every OS/distribution will want it on by default; some may always want to use their own install code.
Having a feature for this shows that while we're opinionated, we're also flexible.
> Add a default-enabled `install` feature

- lib/src/install.rs
- lib/src/task.rs
The previous commit should have called it this, because we're not doing a chroot or container, just changing the working directory.
> task: s/root/cwd/

- lib/src/install.rs
- tests/kolainst/install
install: Factor out some options
Prep for `install-to-filesystem` which will accept an already
mounted fs and not a block device.
---
install: Actually honor provided kargs
Oops.  Seems like clap's attribute stuff suppresses unused
variable warnings.
---
install: More refactoring
Prep for adding `install-to-filesystem`.
- Split up options structure further
- Gather more things into global immutable `State`
- Add helper function to prepare `State`
- Tease back apart "kargs needed for rootfs" and "kargs specified by user"
---
> Prep patches for `install-to-filesystem`

- lib/src/bootloader.rs
- lib/src/install.rs
Prep for `install-to-filesystem`; rather than maintaining data about filesystems like `/boot` in an ad-hoc way, add a little structure which is equivalent to a subset of an `/etc/fstab` entry.
Right now we require a UUID for `/boot`.
> install: Add and use `MountSpec` abstraction for `/boot`

- lib/src/cli.rs
- lib/src/privtests.rs
This makes some future code changes more ergonomic.
> tests: Pass ownership of testing opts

- xtask/Cargo.toml
- xtask/src/xtask.rs
I was hitting an issue with our COPR builds where we were getting *earlier* builds because the git hash was the first component of the version, and the leading numbers there don't increment, and RPM wants higher versions.
Force newer-is-better by injecting the date (up to the minute, not second because we're not going to build more than one a second).
> xtask: Inject timestamp into version

- Makefile
- ci/Dockerfile.fcos
- ci/run-kola.sh
- lib/Cargo.toml
- lib/src/blockdev.rs
- lib/src/bootloader.rs
- lib/src/cli.rs
- lib/src/ignition.rs
- lib/src/install.rs
- lib/src/lib.rs
- lib/src/mount.rs
- lib/src/privtests.rs
- tests/kolainst/install
Add `install-to-filesystem`
This will address the use case of having external code set up
the block devices and (empty) filesystems.  For example, one could
use a different privileged container, Anaconda, etc.
Closes: #54
---
ci: Enable all features
---
ci: Use `cosa kola` to pick up `ARTIFACT_DIR` handling
So I can see the logs in Prow.
---
> Add `install-to-filesystem`

- lib/src/install.rs
- lib/src/install/baseline.rs
- lib/src/mount.rs
- lib/src/utils.rs
install: Clean up imageref handling
Prep for takeover installs, but also just a general cleanup.
Rather than having `ContainerPolicyAllowInsecure` in multiple
places, have it just once with an explicit rationale.
---
install: Further clean up imageref handling
Prep for takeover installs.  Rather than carrying the
container env info around in `State`, carry just the
source image reference and digest separately.
This will make it easier to add code later for
takeover installs to use an image already in an ostree repo.
---
install: Split off baseline module
Since we added `install-to-filesystem`, the install code needs
a refactoring where we more cleanly split up our "default"
installer which …
> install: More cleanups

- cli/Cargo.toml
- cli/src/main.rs
cli: Update `tracing-subscriber` to 0.3
On general principle, but specifically it has better APIs
for `EnvFilter`.
---
Tweak default tracing output
Do log `info` level by default, but quiet the output format.
Prep for more use of tracing.
---
> Tweak default tracing output

- Makefile
- lib/Cargo.toml
- lib/src/install.rs
- lib/src/install/00-defaults.toml
- lib/src/install/baseline.rs
- lib/src/privtests.rs
- tests/kolainst/install
Add support for `/usr/lib/bootc/install/*.toml`
and `/etc/bootc/install/*.toml`
and `/run/bootc/install/*.toml` etc. which define config files for the install process.
Use this to configure the root filesystem type instead of hardcoding it.  We still default to xfs but it's now trivial for an OS/distribution to drop-in an override (or just edit the default toml).  Additionally derived builds can do so just as easily.
We then drop the `impl Default for Filesystem` so that the default isn't hardcoded in the binary anymore.
> install: Add systemd-style drop-in config files

- .github/workflows/ci.yml
- Makefile
- ci/Dockerfile.fcos
build: Install bin-archive in target/
To avoid polluting the toplevel.
---
ci: Switch to `make test-bin-archive`
Right now we only install a single binary, but in the future
that will change (e.g. systemd units, config files).
---
> ci: Switch to `make test-bin-archive`

- lib/src/install.rs
install: Split out helper to detect systemd as pid 1
Prep for usage elsewhere.
---
install: Extract a unified `SourceInfo` struct
This data keeps track of the container and ostree commit information.
Prep for `install --takeover` where we want to serialize this data.
---
> install: A few cleanups

- xtask/src/xtask.rs
No idea how it worked before; we don't want to include the diff output which can lead to us failing to parse an integer:
```
error: Packaging
Caused by:
0: Finding git timestamp
1: invalid digit found in string
```
> xtask: Fix package builds

- contrib/packaging/bootc.spec
Sigh, so annoying that RPM makes one allowlist installed files.
> spec: Add `/usr/lib/bootc` to installed files

- lib/src/cli.rs
- tests/kolainst/basic
This also just forwards to `ostree admin unlock` the same as `rpm-ostree usroverlay` does.
> Add `usr-overlay`

- lib/src/install.rs
- lib/src/install/baseline.rs
- lib/src/task.rs
install: Drop `impl Default for Filesystem`
We require this to be configured externally now.
---
install: Add support for LUKS
This currently requires systemd 253 for
https://github.com/systemd/systemd/commit/03f36e9c0174f983e832c6ced80492ebefd34e46
---
>  install: Add support for LUKS

- lib/Cargo.toml
- lib/src/install.rs
- lib/src/lsm.rs
install: Make config module `pub(crate)` and configs serializable
Prep for takeover installs.
---
lsm: Add an API to set SELinux permissive
This is going to be needed for takeover installs.  There's
no point to trying to keep the LSM state running through
the whole thing because we're going to replace the OS anyways.
---
Bump requirement to latest ostree-ext
Prep for takeover installs.
---
> takeover installs: prep0

- lib/src/install.rs
Apparently the clippy task wasn't gating.  But honestly I'm getting feeling like clippy's value proposition has slipped by default.
> install: Fix a clippy lint

- lib/src/cli.rs
- lib/src/privtests.rs
yum/dnf does this, I think it's a friendly thing to do.  I actually typed `bootc update` and got reminded to do this.
> cli: Add an alias `update` for `upgrade`

- lib/src/install.rs
- lib/src/install/baseline.rs
We shouldn't try to do any SELinux labeling if the source doesn't have it.
xref https://github.com/containers/bootc/issues/83
> install: Only invoke `chcon` if SELinux enabled in the source

- .github/workflows/ci.yml
- lib/Cargo.toml
Because it's needed for more libraries.
> Bump MSRV to 1.64

- cli/Cargo.toml
- lib/Cargo.toml
- lib/src/cli.rs
- lib/src/docgen.rs
- lib/src/install.rs
- lib/src/install/baseline.rs
- lib/src/privtests.rs
- lib/src/status.rs
Update to clap 4.2
Just keeping up with things.
---
Update to ostree-ext 0.11, also bump rustix and cap-std-ext
This is similar to https://github.com/coreos/rpm-ostree/pull/4400
---
install: use fsfreeze, not xfs_freeze
More people are going to have util-linux installed than
have xfsprogs.  Reported via email.
---
> Two crate bumps and use `fsfreeze`

- Cargo.toml
This is nicer than having a hardcoded list.
> build: use new `tier = 2` from cargo-vendor-filterer

- CONTRIBUTING.md
- lib/src/cli.rs
This simply pull the manifest of the iamge to see if any update and available. It could be named `--dry-run` but I wanted to be consistent with `rpm-ostree`.
Fixes #3
> cli: Add a `--check` flag for update

- lib/Cargo.toml
- lib/src/cli.rs
- lib/src/lib.rs
- lib/src/privtests.rs
- lib/src/spec.rs
- lib/src/status.rs
- lib/src/utils.rs
- tests/kolainst/basic
I was working on the configmap support slowly, but a big issue
it raised was how we expose the ability to mutate things.
Our current "API" is just an imperative CLI.  This would require
higher level tooling to manage Kubernetes style declarative system state.
Instead, let's use the really nice Rust `kube` crate to define a CRD;
this is what is output (in YAML form) via `bootc status` now.
We translate the imperative CLI verbs into changes to the `spec`
field.
However, things become more compelling when we offer a `bootc edit`
CLI verb that allows arbitrary changes to the spec.
I think this will become the *only* way to manage attached configmaps,
instead of having imperative CLI verbs like `bootc configmap add` etc.
At least to start.
---
> Rework API to use a Kubernetes CRD

- lib/src/cli.rs
- lib/src/utils.rs
Depends https://github.com/containers/bootc/pull/106
---
cli: Add an `edit` verb
This interactively replaces the specified state, in a similar way
as `kubectl edit`.
As of right now, the only supported state to change is the desired
image.
But this will help unblock [configmap support].
[configmap support]: https://github.com/containers/bootc/issues/22
---
> cli: Add an `edit` verb

- lib/Cargo.toml
- lib/src/cli.rs
This makes the whole system less stateful - we always prune unused images.
> deploy: Use new ostree API to GC images

- lib/src/install/baseline.rs
We already are checking for target_arch when using the constants. Just instantiating them when we are in a target arch makes the build fail when we are building on a arch that that hits the constraint we created for initiating the constant.
closes #112
>  install: Compile (but error at runtime) on non-x86_64/aarch64 

- Cargo.toml
- `release` should use `panic=abort` by default because we make heavy use of FFI and this is safest, and I don't think we need unwinding anyways
- The `releaselto` produces smallest binaries
> Cargo.toml: Update release profile, add releaselto

- .github/workflows/ci.yml
The MSRV is just too much churn to maintain, in practice let's roll with what's in Fedora.
> ci: Drop MSRV, move clippy/fmt into tests

- lib/Cargo.toml
- lib/src/cli.rs
And note the new `require_bootable()`, since we couldn't require that in the container image importer.
> lib: Bump to ostree-ext 0.11.5

- Cargo.toml
- lib/src/privtests.rs
tests: Drop unnecessary `drop`
Newer rustc warns about this, dropping a reference does
nothing.  I think this code used to handle unmount via drop.
---
build-sys: Opt in to resolver = 2
This silences a warning from newer Rust.
---
> Two lint fixes

- lib/src/blockdev.rs
- lib/src/install.rs
- lib/src/install/baseline.rs
`sgdisk` dropped out of my image when I was changing things. In retrospect the error message was relatively clear, but here's some error context I added while debugging.
> install: Add some more error context

- lib/Cargo.toml
We only have this for the ioctl code which we copied from coreos-installer...would be good to port to rustix at some point.
But for now let's update to a newer nix.
> lib: Bump to newer nix

- lib/Cargo.toml
- lib/src/spec.rs
- lib/src/status.rs
These are very practical things to want; the switch to a k8s-native API lost these user-facing ergonomics.
> Add version and timestamp to image status fields

- lib/src/bootloader.rs
- lib/src/install.rs
- lib/src/install/baseline.rs
- lib/src/mount.rs
- lib/src/utils.rs
install: Trim bind mount information
I'm seeing this appear when targeting from a container image.
---
WIP: Support for `install-to-filesystem --replace=alongside`
I was trying to be really ambitious in https://github.com/containers/bootc/pull/78
for the full "takeover" path.  This is a *much* *much* simpler variant
where we just:
- Blow away and reinitialize the `/boot` and `/boot/efi` partitions
- Write inside the existing filesystem, leaving the OS running
Then when we reboot, we'll just need to clean up the old OS
state (or optionally leave it).
---
> Support for `install-to-filesystem --replace=alongside`

- lib/src/cli.rs
This changes bootc to use the new API we added to ostree-ext, which rpm-ostree was also adapted to use.
A key advantage of this is that the update is cached and not lost across reboot.
> upgrade: Wire up --check to new API

- lib/src/install.rs
This pairs with
https://github.com/ostreedev/ostree/pull/3059/commits/e3d93a85713dbc4728d6271ecd23e05c88cf54f3
What we need to add is something more like
`ostree admin init-fs --edition=2023` that flips on modern defaults.
> install: Do use zipl on s390x

- Cargo.toml
- deny.toml
- lib/Cargo.toml
On general principle; they trimmed their supported version set which reduces dep size.  But it also drops out some old things like `base64@0.13.1` (how many times does a base64 library really need to break semver?).
> Deps: Bump to latest kube/k8s-openapi

- lib/src/containerenv.rs
- lib/src/install.rs
It's an easy mistake to make and the error message is less than obvious.
> install: Bail out if we detect we're running rootless

- lib/Cargo.toml
- lib/LICENSE-APACHE
- lib/LICENSE-MIT
While we're not shipping this on crates.io and probably won't soon, it's useful to be able to run a `cargo package` just in case.  The Fedora rust2rpm tool wants license files in the crate tarball.
> lib: Include license files when packaging

- Makefile
- contrib/packaging/bootc.spec
- lib/src/cli.rs
- xtask/src/xtask.rs
- Inject pre-generated manpages into the source tarball we make
- Ensure we use the git tag for version if there is one
Immediate motivation is making sure man pages end up in e.g. RPM builds.
> Rework build infra, add manpages into tarball

- lib/src/bootloader.rs
bootloader: Add BOOTC_BOOTLOADER_DEBUG env var
To force on verbose tracing for bootupd to debug things.
---
bootloader: Add more error context
To debug a problem I hit.
---
> More errcontext

- lib/src/install.rs
- lib/src/install/baseline.rs
For example, the current RHEL 9.2 VM images (KVM/cloud-init guest, and at least GCP) don't use a separate `/boot` by default (probably because they don't support LUKS for `/` like CoreOS systems do).
> install: Relax restriction on separate /boot

- lib/src/install/baseline.rs
Formatting devices by concatenation was a noob thing to do.
Closes: https://github.com/containers/bootc/issues/115
> install: Fix installation to loopback (and probably NVMe)

- lib/src/cli.rs
- lib/src/deploy.rs
We want to gracefully handle the case where there's no booted/staged image - i.e. when there's no spec.
However we only support deploying a container image.  So add a `RequiredHostSpec` that is like `HostSpec` but without the `Option`.
This drops out a few unnecessary `Option`-juggling in the deploy code.
Prep for adding configmaps to the spec.
> Add RequiredHostSpec

- lib/src/fixtures/spec.yaml
- lib/src/spec.rs
Just on general principle; prep for further refactoring.
> lib: Add a unit test for parsing the host CRD

- lib/Cargo.toml
- lib/src/k8sapitypes.rs
- lib/src/lib.rs
- lib/src/spec.rs
- lib/src/status.rs
These are massive overkill for what we need now, and in particular k8s-openapi contains huge amounts of generated code.
Reimplement the tiny subset of k8s metadata we need.
> Drop k8s-openapi and kube crates

- .copr/Makefile
This should unbreak the COPR build since we now generate man pages when making the source tarball.
> ci/copr: Add ostree-devel

- ci/run-kola.sh
- lib/src/cli.rs
- lib/src/privtests.rs
- lib/src/spec.rs
- lib/src/status.rs
This avoids unnecessary digging through an `Option`, particularly some `unwrap()` usage.
> spec: Make status always required

- Makefile
- docs/install.md
- lib/src/install.rs
- lib/src/install/00-defaults.toml
- lib/src/privtests.rs
- tests/kolainst/install
Let's require the OS/distro to inject the defaults they want.
> install: Drop default config

- xtask/src/xtask.rs
Fixing the tagged generation broke the untagged case.
> xtask: Fix srpm generation

- lib/Cargo.toml
- lib/src/install.rs
- lib/src/status.rs
- lib/src/utils.rs
status: Make warning message red
To increase visibility.
---
install: Error out early on s390x
xref https://github.com/coreos/bootupd/issues/550
---
> Two minor error/logging improvements

- lib/src/install.rs
- lib/src/status.rs
Motivated by https://issues.redhat.com/browse/COS-2526
It's quite possible that the image sha will have been GCd, but the version number and timestamp inside the image (not just the file timestamp) are probably sufficient for general reference.
> install: Add more image metadata to aleph

- README.md
- Clarify that `bootc update` is totally safe
- Note it's now in Fedora
> README.md: A few clarifications on status

- lib/src/cli.rs
- lib/src/deploy.rs
- lib/src/install.rs
- lib/src/install/baseline.rs
All the clippy warnings were `--fix`able.
> tree: Pass through `cargo clippy --fix`

- lib/src/cli.rs
cli/edit: Don't error out if host spec unchanged
This matches e.g. `kubectl edit`.
---
cli/edit: Default to interactive edit
This better matches `kubectl edit`.
> cli/edit: Minor tweaks

- Makefile
Add a `make validate` target to run cargo-fmt and cargo-clippy. My muscle memory from other containers/ projects is strong where I am used to run `make validate` before committing/pushing changes.
> make validate: add new target

- lib/src/cli.rs
- tests/kolainst/basic
Regression from previous rework around staged diffs; we were incorectly re-staging the same thing.
> cli: Correctly no-op unchanged updates

- lib/src/install.rs
- tests/kolainst/install
I think this got lost in a refactoring.
Closes: https://github.com/containers/bootc/issues/163
> install: Actually honor kargs

- lib/src/cli.rs
- lib/src/lib.rs
- lib/src/reboot.rs
Closes: https://github.com/containers/bootc/issues/165
> Add `upgrade --apply`

- .github/workflows/ci.yml
Having a fast disposable VM is good for this.  Also we are now verifying that the baseline functionality works to install alongside an Ubuntu system!
> ci: Test alongside installation in GH Actions

- docs/install.md
- lib/src/privtests.rs
- tests/kolainst/install
While it's actually nice to show that the container can just install itself, I'm trying to reduce the command line length of the invocation in the interest of simplicity.
There's a minor cost here as it means we'll get a default bridge network, but that hardly matters.  Anyone who wants to avoid it can just specify `--net=none` on their own.
However this said, I think longer term we do want to support networking at install time in order to do things like fetch configmaps, so dropping this is prep for that too.
> install: Drop `--net=none` suggestion

- docs/install.md
- lib/src/install.rs
- lib/src/privtests.rs
- tests/kolainst/install
install: Compute target image reference upfront
Prep for verifying it before we do an install.
---
install: Verify target image fetch by default
Now that we've dropped the `--net=none` by default, let's
avoid two major footguns by verifying the target image specification
by default.
- Forgetting to use `--target-no-signature-verification` (most people are going to need this in demos right now)
- When the target OS requires an authenticated pull, but one didn't embed the pull secret in the target OS
---
> install: Verify target image fetch by default

- lib/src/status.rs
Would have helped a little bit with a recent issue.
> status: Add some error context

- lib/src/status.rs
If we're querying a deployment that has a container base, but also has layered packages we'll error out because we'll try to find the layer base from the rpm-ostree generated merge commit.
Just fully ignore deployments that have rpm-ostree changes.
> status: Fully ignore images with rpm-ostree changes

- docs/install.md
Followup to https://github.com/containers/bootc/pull/182#discussion_r1384597462
> docs: Finish sentence around pull secret

- docs/install.md
There's no reason to leak these containers by default.
> docs/install: Also document using `--rm`

- lib/src/cli.rs
- lib/src/install.rs
See: https://rust-lang.github.io/rust-clippy/master/index.html#/needless_borrow
Applied `cargo clippy --fix --lib -p bootc-lib`
> lib: apply clippy fix for needless borrowing

- .github/workflows/ci.yml
The upload/download-artifact v2  actions are throwing warnings about using Node12. The v3 versions are updated to use Node16.
See: https://github.blog/changelog/2021-12-10-github-actions-github-hosted-runners-now-run-node-js-16-by-default/
> github: update artifact actions to v3

- docs/bootc-images.md
- docs/install.md
I tried to add some clarifying details/context around the how to build "bootc compatible" images and how they are installed.
Generally spruced up the Markdown syntax and cleaned up some spelling/grammar nits.
This replaces #189
> docs: additional details around bootc images, install

- docs/faq.md
These questions were raised in an internal chat and it gave good reason to start an FAQ.
> docs: initial FAQ entry

- CONTRIBUTING.md
In a fresh Fedora 39 container, I had to install the updated list of dependencies to successfully run:
- cargo fmt
- cargo clippy
- cargo build --release
> docs: update required dependencies

- lib/src/containerenv.rs
This tweaks the error message when `.containerenv` cannot be found so that a fully-qualified path is included in the error.
Previously, the error message would just show `run/.containerenv` as the path to the file, which is not entirely clear.
I tried to change the `const PATH` to be an absolute path, but doing so breaks the ability for `open_optional()` to open the file successfully; returns an error `a path led outside of the filesystem`.
> containerenv: small error message fix

- lib/src/install.rs
I'm working on a buildsystem where we run a "supermin" VM that doesn't use systemd as pid1.  There's no reason to hard require systemd for this.  This check isn't fully correct because it will allow things to pass if someone does `podman run --init` to make us pid2, but still in a userns.  In theory we could detect that in the future.
> install: Just check if we're pid1

- lib/Cargo.toml
- lib/src/blockdev.rs
- lib/src/cli.rs
- lib/src/install.rs
- lib/src/podman.rs
- lib/src/utils.rs
I'm experimenting with doing `bootc install` in a supermin VM like we do in coreos-assembler, but hit upon the fact that supermin's `/sbin/init` implementation incorrectly does `chroot()` instead of a `pivot_root`:
https://github.com/libguestfs/supermin/blob/5230e2c3cd07e82bd6431e871e239f7056bf25ad/init/init.c#L288
The problem here then is doing `nsenter` just takes us into the original rootfs, and all the real content is in `/root`.
Re-implement this by re-executing our own binary and doing the `setns()` and `chroot()` dance internally, because we can't really do it with external binaries.
> install: Re-implement hostns to work around supermin

- ci/Dockerfile.fcos
- ci/usr/lib/bootc/install/50-test-kargs.toml
- docs/install.md
- lib/Cargo.toml
- lib/src/install.rs
- lib/src/install/baseline.rs
- tests/kolainst/install
We know we eventually want "day 2" management of kargs, but supporting "install time" kargs in a somewhat container-native way will let us more properly set up things like the `console=` karg only for cloud images for example.
> install: Add `kargs` to installation config

- docs/faq.md
We have examples on how to use "bootc compatible" images in other distro specific locations, so just link to those.
> faq: remove distro-specific examples

- docs/install.md
Fails with the following otherwise:
```
STEP 9/11: RUN mkdir -p /usr/etc-system/ &&     echo 'AuthorizedKeysFile /usr/etc-system/%u.keys' >> /etc/ssh/sshd_config.d/30-auth-system.conf &&     echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL7xFq1HtZKZiaD8MfkhNtn37m8GSc1W168NoSaT9RSf cardno:000F_C36A3FC0' > /usr/etc-system/root.keys && chmod 0600 /usr/etc-system/keys
chmod: cannot access '/usr/etc-system/keys': No such file or directory
Error: building at STEP "RUN mkdir -p /usr/etc-system/ &&     echo 'AuthorizedKeysFile /usr/etc-system/%u.keys' >> /etc/ssh/sshd_config.d/30-auth-system.conf &&     echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL7xFq1HtZKZiaD8MfkhNtn37m8GSc1W168NoSaT9RSf cardno:000F_C36A3FC0' > /usr/etc-system/root.keys && chmod 0600 /usr/etc-system/keys": while running runtime: …
```
> docs: fix injecting root keys example

- lib/src/install.rs
This is dead code right now; dropping it helps lower our dependency on ostree.
> install: Drop `commit` from SourceInfo

- deny.toml
- lib/Cargo.toml
This will help ensure we're testing what's there before release, in particular https://github.com/ostreedev/ostree-rs-ext/pull/569
> lib: Track ostree-ext git

- lib/src/mount.rs
This is the same as
https://github.com/coreos/bootupd/commit/1457c2004766b09ee979d5457cc13a1383fd01bc and makes things work on c9s.
> mount: Be compatible with older util-linux

- lib/src/install.rs
It may be that we're involved via a container flow where e.g. `/tmp` is already "properly" set up as a tmpfs.
In that case we don't need to do a dance in retargeting.
xref https://github.com/osbuild/bootc-image-builder/issues/18#issuecomment-1855886913
> install: Don't retarget /tmp or /var/tmp if they're not overlayfs

- lib/src/install.rs
I hit a bug here and the error context and debug tracing would have been helpful.
> install: Add tracing and error context around re-exec

- .github/workflows/ci.yml
- docs/index.md
- docs/install.md
- lib/src/cli.rs
- lib/src/install.rs
- lib/src/install/baseline.rs
- lib/src/privtests.rs
- tests/kolainst/install
install: Rename `install` -> `install to-disk`, peer with `to-filesystem`
Take the current `install` verb and change it to be
`bootc install to-disk`, and then `install-to-filesystem` becomes
`bootc install to-filesystem` - they are obvious peers.
The main motivation here is that in the end many use cases will
want nontrivial filesystem customization, and while I like having
a fully opinionated builtin flow to write to a target disk,
we should really think of `to-filesystem` as a fully equal peer
of `to-disk`.
---
install-to-disk: Verify target is a block device
I saw someone get confused and think `bootc install` could work
on a filesystem.
---
install-to-filesystem: Verify target is a …
> install: Rename `install` -> `install to-disk`, peer with `to-filesystem`

- lib/src/cli.rs
- lib/src/install.rs
install: Propagate skopeo stderr
We're going to need to consistently use a helper to get this right
in the future...basically most uses of `.output()` are wrong.
---
install: Fix exec helper to not swallow unexpected args
Our `exec-in-host-mount-namespace` internal helper was intended
to be a "passthrough" that accepts whatever child arguments.
However I misunderstood how to do this in clap.  Before this
change we get:
```
$ bootc blabla
ERROR Re-exec in host mountns: Missing command
```
i.e. the exec code kicks in because `external_subcommand` takes
over *everything* unknown.
Fix things to use `trailing_var_arg` which is intended for this case.
After this patch:
```
$ bootc blabla
error: unrecognized subcommand 'blabla'
Usage: bootc …
```
> install: Two smaller fixes

- lib/src/cli.rs
- lib/src/install.rs
- lib/src/utils.rs
Prep for further refactoring, targeting
https://github.com/containers/bootc/issues/218
This will help us find the places we're synthesizing a policy.
No functional changes intended.
> Add a helper for generating sigpolicy

- lib/Cargo.toml
- lib/src/deploy.rs
This will ensure we're really pruning everything.
xref https://github.com/coreos/rpm-ostree/pull/4720
> deploy: Use new ostree-ext pruning API

- lib/src/blockdev.rs
- lib/src/install.rs
- lib/src/lib.rs
- lib/src/lsm.rs
- lib/src/podman.rs
- lib/src/reboot.rs
- lib/src/task.rs
Especially in places where we call `.output()`, what we generally always want is to get stdout, but keep stderr going to the parent process stderr.  The `Command` API doesn't make this obvious to do, and worse forces every caller to manually check the exit status.
The `Task` API fixes both of these.
(Now, the Task API also defaults to printing a description,
which we need suppress in many cases with `.quiet()`)
> Use `Task` generally over `Command`

- docs/man/README.md
- docs/man/bootc-edit.md
- docs/man/bootc-install-to-disk.md
- docs/man/bootc-install-to-filesystem.md
- docs/man/bootc-install.md
- docs/man/bootc-status.md
- docs/man/bootc-switch.md
- docs/man/bootc-upgrade.md
- docs/man/bootc-usr-overlay.md
- docs/man/bootc.md
- xtask/src/xtask.rs
This will help motivate us to improve our man pages, by making them much more visible as pre-generated markdown that can be conveniently viewed from e.g. the Github web UI.
For now, anytime we change the CLI we'll need to manually run `cargo xtask man2markdown`, and commit and push the result. This requires `pandoc` in the environment.
If this becomes burdensome I will likely investigate doing e.g. a Github action which either automates doing it post-commit, or enforces that it's done as part of the commit which introduces the change.  However the problem with the latter will be the `pandoc` requirement.
It may make sense to investigate e.g.
[clap-markdown](https://docs.rs/clap-markdown/latest/clap_markdown/) in the future instead.
> docs: Generate docs/man

- .github/workflows/ci.yml
- docs/index.md
- docs/install.md
- lib/src/cli.rs
- lib/src/fixtures/spec-ostree-remote.yaml
- lib/src/fixtures/spec-v1.yaml
- lib/src/install.rs
- lib/src/privtests.rs
- lib/src/spec.rs
- lib/src/status.rs
- tests/kolainst/install
(Draft for discussion, also this depends on https://github.com/containers/bootc/pull/229 )
--
Don't enforce container sigpolicy by default
Closes: https://github.com/containers/bootc/issues/218
Basically this effort has not been really successful and adds
more pain than it solves.  We need to have a solution that works
for podman too.
In many scenarios, TLS is sufficient - or at least, we're far
from the only thing that if fetched from a compromised server
would result in a compromised system (e.g. privileged containers).
---
> Don't enforce container sigpolicy by default

- lib/src/status.rs
rustdoc does not generate documentation for expression fields
> status: fix warning for unused doc comment

- lib/src/lib.rs
In my experience this is far and away the clippy lint that is:
- Most common to trigger (especially when refactoring code)
- The least valuable to fix; there's no performance or correctness concerns really
> lib: `#![allow(clippy::needless_borrow)]`

- lib/src/cli.rs
- lib/src/privtests.rs
- lib/src/status.rs
We do this in the install flow, do it for CLI verbs like `status`, `update|upgrade` etc.
> cli: Explicitly require root privileges

- lib/src/cli.rs
- manpages-md/bootc-edit.md
- manpages-md/bootc-install-to-disk.md
- manpages-md/bootc-install-to-filesystem.md
- manpages-md/bootc-install.md
- manpages-md/bootc-status.md
- manpages-md/bootc-switch.md
- manpages-md/bootc-upgrade.md
- manpages-md/bootc.md
- xtask/src/xtask.rs
xtask: Fix man2markdown to use new location
We moved these in an earlier commit.
---
cli: Improve man pages
Add some more information into the man pages.
---
> Man improvements

- lib/src/privtests.rs
- lib/src/spec.rs
- lib/src/status.rs
- tests/kolainst/basic
This depends on https://github.com/containers/bootc/pull/241
---
Add `HostType`, change `status` to always succeed
Closes: https://github.com/containers/bootc/discussions/242
Basically it'd be useful for folks to be able to run `bootc status --json`
and have that always work - if we're not on a bootc-booted system
then we just output null data.
Specifically we drop the `isContainer` field and replace it
with an optional non-exhaustive enumeration.  For anything we don't
know about we just output `None` i.e. `null` in JSON.
---
> Add `HostType`, change `status` to always succeed

- .github/labeler.yml
- .github/workflows/labeler.yml
Because it's useful to track sub-components.
> ci: Add GH labeler workflow

- docs/relationship.md
Based on a question from a chat.
> docs: Extend rpm-ostree relationship a bit

- docs/relationship-particles.md
This original vision document from Lennart is great. Let's lay out a vision for why the bootc project exists and is different from this.
> docs: Add relationship-particles.md

- lib/src/cli.rs
Previously, running:
`bootc update; bootc update --apply`
would result in the system not rebooting to apply the previously-staged deployment.
Closes: https://github.com/containers/bootc/issues/234
> upgrade: fix --apply when the desired deployment is already staged

- lib/src/cli.rs
- manpages-md/bootc-upgrade.md
We expect people to be parsing our spec/status via e.g. JSON.
> cli: Drop `upgrade --touch-if-changed`

- hack/Containerfile
This is a relatively efficient container-oriented build flow suitable for local iteration.
> hack/Containerfile: New file for local container builds

- lib/src/spec.rs
- lib/src/status.rs
In https://github.com/ostreedev/ostree-rs-ext/pull/537 we added a facility to cache metadata (manifest+config) for container image updates with an eye for use in rpm-ostree.
The `bootc update --check` code here in bootc was also updated to use it; but we didn't really expose it back in the status.
This closes the gap, just bridging the cached update metadata into status.  We want to do this as opposed to having `bootc update --check` grow its own API for example.
> spec: Add cached update metadata

- lib/src/blockdev.rs
- lib/src/install.rs
- lib/src/privtests.rs
This is such a small amount of additional code that I think there's no good reason not to support it directly here.
> install: Support `to-disk --via-loopback`

- lib/src/lsm.rs
There's no need to perform any additional steps if the bootc process already has install_t.
> lsm: exit early if the process already has install_t

- lib/src/cli.rs
- lib/src/deploy.rs
- lib/src/spec.rs
switch: Move option processing earlier
This logic just converts the provided CLI options
into data structures, so it can come before we do
other things.
Prep for further work.
---
spec: impl Display for ImageReference
I want this in a followup patch.
---
switch: Add hidden `--mutate-in-place`
This is intended to be runnable in current Anaconda `%post`
to fix up its lack of support for `--target-imgref`.
---
> Switch inplace

- docs/install.md
- lib/src/blockdev.rs
- lib/src/install.rs
blockdev: fix recognizing parent loop devices
lsblk returns TYPE == loop for loop devices, modify the code
so loop devices are correctly recognized.
---
install: make the source digest optional
This is a prep work for the following commit. It will implement pulling
the container image from an explicitly given container reference. Thus,
there's no need to always fetch the digest because the caller is being
explicit about the container image, so let's make the field optional.
---
install: add --source-imgref
bootc install and install-to-filesystem currently rely on the fact that they
run inside a podman container. That's quite inconvenient for using bootc
for osbuild, because osbuild already run everything in a container.
While having a container in a container is surely possible, it gets …
> install: add --source-imgref

- Makefile
- manpages-md-extra/bootc-fetch-apply-updates.service.md
- systemd/bootc-fetch-apply-updates.service
- systemd/bootc-fetch-apply-updates.timer
- xtask/src/xtask.rs
Let's ship a baseline systemd unit that can be enabled for automatic updates.
>   systemd: New bootc-fetch-apply-updates.{timer,service} 

- .github/workflows/ci.yml
- lib/src/install.rs
Let's just hard require a skopeo that can fetch from `containers-storage`. Motivated by https://github.com/containers/bootc/pull/263 which was moving this code around.
> install: Drop support for old skopeo

- Makefile
- manpages-md-extra/bootc-fetch-apply-updates.service.md
- xtask/Cargo.toml
- xtask/src/xtask.rs
build: Install systemd units by default
I was being too chicken; there's no reason not to install our
systemd units by default.  They're not enabled by default,
but we do want to encourage their use.
---
Fix manpage for service
We need `-s` for the pandoc invocation to render this right.
---
> Two systemd unit fixes

- .github/workflows/ci.yml
- lib/src/cli.rs
- lib/src/install.rs
- lib/src/privtests.rs
- manpages-md/bootc-install-print-configuration.md
- manpages-md/bootc-install-to-disk.md
- manpages-md/bootc-install-to-filesystem.md
- manpages-md/bootc-install.md
Even when an external process is creating the disk, we want it to be able to honor the root filesystem type specified in the container.
> install: Add `print-configuration`

- docs/usage.md
Document offline USB upgrades.
> docs/usage: New file

- lib/src/install.rs
This was being done in osbuild work to use `bootc install`, so we might as well make it automatic.  The environment variable was not intended as more than a debugging aid.
> install: Don't unshare if we have an external source

- docs/usage.md
- lib/src/cli.rs
- tests/kolainst/basic
Instead of erroring out if the spec is unchanged, just print a notice.  This better matches Kubernetes default style.
> switch: Be idempotent

- docs/install.md
> docs: Document `to-disk --via-loopback`

- lib/src/blockdev.rs
- lib/src/install.rs
blockdev: Add some debugging around loopback
---
install: Only switch to loopback after re-exec
I noticed we were leaking a loopback device, and the reason is
because the "re-exec self for selinux" dance.
We should really try to move that re-exec way earlier because
it's a big hazard for stuff like this right now.
This is a simple fix though that just moves the switch to
allocating the loopback device until after we've done the install
prep (including that re-exec).
---
> install: Only switch to loopback after re-exec

- lib/Cargo.toml
- lib/src/deploy.rs
- lib/src/install.rs
- lib/src/status.rs
Main changes are
- Configuration object is no longer an `Option<T>`
- The metadata trait extensions now must be from cap-std
> Port to ostree-ext 0.13, cap-std 3

- lib/src/cli.rs
- lib/src/install.rs
- lib/src/lsm.rs
lsm: Make setenforce 0 fallback require `BOOTC_SETENFORCE0_FALLBACK`
We shouldn't perform global system mutation without an opt-in.
As painful as it is.
---
lsm: Test if we have install_t capability
Hardcoding `install_t` is a bit ugly; maybe at some point
things change so that `spc_t` has `install_t` privileges.
Let's do a runtime check if we can set an invalid label; if
so then we're good.
---
lsm: Make a not-`nosuid` `/tmp`
This was the thing that was breaking our `unconfined_t` -> `install_t`
transition; the host `/tmp` is `nosuid`.  It simplifies things
here to just make our own, so do that.
---
> Fix install_t again

- lib/src/install.rs
- lib/src/install/config.rs
Our install config is going to grow; the "nested module in existing file" only scales to a certain point, and we are going to pass it.
> install: Factor out configuration into new file

- docs/install.md
- lib/src/install/baseline.rs
- lib/src/install/config.rs
- lib/src/privtests.rs
- manpages-md-extra/bootc-install-config.md
Keep (but soft-deprecate) the existing `root-fs-type`, and add a more general set of tables in `install.filesystem.root`, with `type` as a field underneath that.
This somewhat resembles the [Image Builder blueprint](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/composing_a_customized_rhel_system_image/creating-system-images-with-composer-command-line-interface_composing-a-customized-rhel-system-image#composer-blueprint-format_creating-system-images-with-composer-command-line-interface) design.
In particular, this aims to leave space for
https://github.com/containers/bootc/issues/287
where we'd add e.g.
```
[install.filesystem.root]
extra = "5G"
```
for size specification.
Another obvious extension would be `options` to pass through options to `mkfs.$fs`; …
> install: Generalize `root-fs-type` into `install.filesystem.root.type`

- lib/src/install.rs
- tests/kolainst/install
This came out of a discussion with bootc-image-builder, which has this issue right now:
https://github.com/osbuild/bootc-image-builder/issues/149
As I noted in that issue, I think it's basically been working here because we always write to a real fresh filesystem, but let's be very explicit.
There's a notable tricky bootstrapping we're solving here around "what's the label of `/`" because we know we are running the target OS as a container image already.
> install: Ensure we label `/` (and `/boot`)

- .github/workflows/ci.yml
- docs/install.md
- lib/src/install.rs
- lib/src/podman.rs
I just keep hitting the host skopeo requirement in corner cases; it's annoying because *otherwise* the container is self-sufficient. Change our installation instructions to add a `/var/lib/containers` bind mount.
For the time being of course we continue to support forking off `skopeo` on the host.
One thing I still want to investigate is dropping some requirements here and switch to *dynamically* setting up the mount points inside the container as is mentioned in https://brauner.io/2023/02/28/mounting-into-mount-namespaces.html but this currently requires relatively new host kernels.
As far as test coverage, this changes the Github Action that uses ubuntu and needed to build a newer skopeo to stop doing that, and in fact we explicitly *remove* skopeo to verify it's not being used in the …
> install: Optionally use host mounted `/var/lib/containers`

- lib/src/lsm.rs
Otherwise it's noisy:
```
[root@localhost ~]# ./bootc update --check
chcon: failed to change context of '/tmp/.tmp2rw6pV' to ‘unconfined_u:object_r:invalid_bootcinstall_testlabel_t:s0’: Invalid argument
chcon: failed to change context of '/tmp/.tmpCiTvUm' to ‘unconfined_u:object_r:invalid_bootcinstall_testlabel_t:s0’: Invalid argument
No changes in: ostree-unverified-registry:quay.io/centos-bootc/fedora-bootc-cloud:eln
[root@localhost ~]#
```
> lsm: send test_install_t chcon output to /dev/null

- .github/workflows/ci.yml
- lib/src/install.rs
We're going to investigate supporting installing SELinux-enabled targets from a SELinux-disabled host.  This environment variable will allow bypassing the check.
xref https://github.com/ostreedev/ostree/pull/3151
> install: Add BOOTC_SKIP_SELINUX_HOST_CHECK

- lib/src/install.rs
- lib/src/status.rs
- lib/src/utils.rs
status: Drop warning
Per the issue, having the API format be `v1alpha` is enough.
Closes: https://github.com/containers/bootc/issues/297
---
Adapt warning API for usage in install
The `warning` helper API just became unused by the previous
commit; make it used in another place it should have been.
---
> Drop status warning

- docs/bootc-images.md
- lib/Cargo.toml
- lib/src/cli.rs
- lib/src/deploy.rs
- lib/src/journal.rs
- lib/src/lib.rs
- lib/src/metadata.rs
As we aim to slowly move away from ostree, let's add a bootc label that we expect to be used.  For now, this is just a warning.
I will change rpm-ostree to add this by default if we take this.
But this one is also an important step for if we ever add the flow of simply deriving from an existing application base image.
> Add suggestion for `LABEL containers.bootc 1`

- lib/src/deploy.rs
This one is really a "soft warning"...it's not a serious problem to have stuff in `/run`, it's just ignored.
At the same time, we want to persist it so that someone debugging things later can find the information.
> deploy: Log filtered content warning to journal, not stderr

- .github/renovate.json5
Right now we're not using a `Cargo.lock`, but we should.  Let's try out renovate like some other Rust containers/ GH repos.
e.g. https://github.com/containers/netavark/commit/67b7da4a89e55ab4a94c450971f2e0d0a5983310
I commented out the assignee thing as we don't have a dedicated team yet.
> ci: Add renovate5

- .github/renovate.json5
Renovate apparently doesn't understand that in Rust for pre-1.0 crates that "minor" are actually semver bumps.
> renovate: just do patch updates

- Cargo.lock
- contrib/packaging/bootc.spec
- lib/Cargo.toml
This way we'll get the updated `/var` handling in our -dev images for ease of testing.
> Track ostree-ext git

- .dockerignore
- hack/Containerfile
Specifically, I want to hack on both e.g. ostree and bootc at the same time.  With this, I can do (from ostree):
```bash
$ make install DESTDIR=/path/to/bootc/target/dev-rootfs
```
Then from this repo, running a container build will get me both.
> hack: Allow injecting stuff into target/dev-rootfs

- .github/workflows/ci.yml
- lib/src/install.rs
I've gone back and forth on this one over time; lately my thought is that conceptually `/` is stuff that bootc/ostree doesn't actually own, and so we shouldn't add this bit.
For a use case of e.g. testing out bootc via an "alongside" install, we would want to enable rolling back to the non-bootc state (at some point in the future when we e.g. save the original `/boot`) and the immutable bit would be a thing we'd then need to undo.
The readonly bind mount over `/sysroot` should be sufficient for our use cases.
> install: Drop setting immutable bit on physical /

- lib/src/install.rs
Especially on ARM, which utilizes UEFI for booting in most cases, it is important that the /sys/firmware/efi/efivars be mounted and populated, otherwise bootc will fail to complete a to-filesystem installation.
This patch attempts a mount as long as the hosts efivars directory has an entry, signifying the system is at least capable of UEFI.
Note that it is sufficient to just attempt to mount efivars. If it's already mounted elsewhere, it triggers the mount to be made at the /sys location.
Fixes #291
> Ensure that efivarfs is mounted in the container

- Cargo.lock
- contrib/packaging/bootc.spec
- lib/Cargo.toml
I decided to just do a release anyways, so we don't need to track git.
This (effectively) reverts commit 79295cedaf0135c9e9dd5505575921d8a46d45ba.
> Update to ostree-ext 0.13.2

- lib/src/install.rs
- lib/src/lsm.rs
Prior to this fix the selinux_enabled function would always return true, even if selinux was set to disabled or permissive.
fixed #303
> Make `--disable-selinux` work on hosts that have `selinux=0`

- lib/src/install.rs
- lib/src/install/baseline.rs
As we want to support enabling `root.transient` in some images, this means that things like `apt|dnf install foo` literally just works out of the box.
However...we have a looming danger around things like kernels.  Typically the package installation scripts for those aren't going to handle this correctly.
Let's mount `/boot` readonly by default, as we have been doing in Fedora CoreOS and derivatives for a while.
Now I'm not totally happy with this because ultimately I think this should be configurable by the OS, not hardcoded in bootc.  We have some thought to put in to exactly how that's exposed.
But for now let's set the precedent here.
> install: Mount `/boot` readonly by default

- contrib/packaging/bootc.spec
- xtask/src/xtask.rs
The release process has drifted with xtask; I forget exactly why but I ended up with `.zstd`, not `.zst` in the tarballs and I've been hand-hacking that manually.
Fix things up so that `cargo xtask package` generates the source snapshot and the vendor tarball named exactly how we release them now.
> xtask: Fixes for `cargo xtask package`

- .github/renovate.json5
It will never work to try to bump e.g. the upload and download actions as separate PRs.
> renovate: Attempt to group GHA updates

- lib/src/install.rs
- manpages-md/bootc-install-to-disk.md
- manpages-md/bootc-install-to-filesystem.md
install: Drop unimplemented root_options
I added this in 8078700c433b41ae80564def5190cdbe08315108
but it was never implemented.
Drop it to avoid confusion.
---
manpages-md: Regenerate
(TODO: add a periodic GH action that does this)
---
> install: Drop unimplemented root_options

- lib/src/install.rs
- lib/src/lsm.rs
As a follow-on to #302, we want to also mount the selinuxfs special filesystem if the host also has that filesystem mounted.
Related #303
> Add selinuxfs to be mounted in the container

- Cargo.lock
For some reason the changes that dependabot made here recently still result in local `Cargo.lock` changes for me.
> Cargo.lock: Adjust for nix bump

- lib/src/mount.rs
> mount: Factor out a run_findmnt helper

- lib/src/privtests.rs
This test fell over, let's show what stderr actually had instead.
> privtests: Show stderr on failure

- lib/src/privtests.rs
I missed that there were two here; followup to previous commit.
> tests: Another missing `assert!` change to dump stderr

- contrib/packaging/bootc.spec
COPR can't resolve `%autorelease`. That caused bootc RPM pakcage name like `bootc-202403011229.g5dde9d8842-%autorelease.x86_64`.
This PR uses `1%{?dist}` instead.
> spec: %autorelease can't be resolved by COPR

- lib/src/blockdev.rs
This is what other projects do; it avoids double buffering and is generally a good idea.
> blockdev: Use --direct-io=on for losetup

- .github/workflows/integration.yml
- tests/integration/README.md
- tests/integration/install-upgrade.fmf
- tests/integration/playbooks/install.yaml
Use `--tls-verify=false` in podman build, don't need CERT_URL secret any more.
> test: update integration README

- .github/workflows/ci.yml
- tests/kolainst/install
Until the fix for https://github.com/coreos/fedora-coreos-tracker/issues/1680 finally propagates.
> ci: Pin eln image

- .github/workflows/ci.yml
- docs/src/bootc-install.md
- lib/src/cli.rs
- lib/src/install.rs
- tests/integration/playbooks/install.yaml
This is just mild sugar on top of the existing `to-filesystem` right now.  But, I think we can do more with this later.
Partially addresses https://github.com/containers/bootc/issues/380
> install: Add `to-existing-root`

- docs/src/bootc-install.md
- lib/src/cli.rs
- lib/src/install.rs
- lib/src/kernel.rs
- lib/src/lib.rs
Builds on top of https://github.com/containers/bootc/pull/382
---
install: Support gathering more info for host root (including LVM)
Teach `install to-existing-root` how to gather kernel arguments
and information we need from `/proc/cmdline` (such as `rd.lvm.lv`).
In this case too, we need to adjust the args to use `-v /dev:/dev`
because we need the stuff udev generates from the real host root.
With these things together, I can do a bootc alongside install
targeting a Fedora Server instance.
Closes: https://github.com/containers/bootc/issues/175
---
> install: Support gathering more info for host root (including LVM)

- lib/src/cli.rs
- lib/src/install.rs
- lib/src/install/baseline.rs
- xtask/src/xtask.rs
> Cleanup clippy lints

- lib/src/lsm.rs
This is what we're matching against to retrieve the context, not the
target, so it's more useful for debugging to primarily see the
`as_path` argument.
> Log `as_path` in lsm_label

- tests/integration/playbooks/deploy-aws.yaml
This PR is to update ami id to latest according to compose update.
> test: update ami image id

- lib/src/install.rs
- lib/src/install/baseline.rs
The mount output for tmpfs/etc. is just an implementation detail, we don't need to print it.  Do add a log message with the container information to make more clear
that's what's going on - we're installing the running container image.
> install: Improve early output

- lib/src/install.rs
- lib/src/install/osconfig.rs
Right now bootc supports an experimental install from a non-selinux host when using the `BOOTC_SKIP_SELINUX_HOST_CHECK=1` option.
This is nice and works relatively well. However files written during the install like /etc/fstab or the tmpfiles.dfile in /etc/tmpfile.d/bootc-root-ssh.conf must be labeled too.
This commit adds a (rather crude) manual way to do this.
Closes https://github.com/containers/bootc/issues/362
> install: manually label {/etc/fstab,tmpfile.d/bootc-root-ssh.conf}

- tests/integration/mockbuild.sh
`quay.io/fedora/fedora:40` image changed. Package `sudo` has not be installed (log: http://artifacts.osci.redhat.com/testing-farm/a7409509-aaaf-4632-b1cc-6459b2e9ce43/). I filed a bug https://bugzilla.redhat.com/show_bug.cgi?id=2269960 and mark it as testBlocker. The `sudo` should be installed from https://pagure.io/fedora-kickstarts/blob/f40/f/fedora-container-base.ks#_12. I don't know what happened in the new Fedora 40 image. Anyway, let's remove `sudo` from `mockbuild.sh`.
> test: remove `sudo` in mockbuild.sh

- docs/src/man/bootc-install-to-disk.md
- docs/src/man/bootc-install-to-existing-root.md
- docs/src/man/bootc-install-to-filesystem.md
- docs/src/man/bootc-install.md
- lib/src/install.rs
- xtask/src/xtask.rs
It is not clear from the current man-page that `--karg` can be passed multiple times. From reading the code it seems to be the case but because it's not obvious (to me) I also added a small testcase to the CI to ensure that I'm not misreading things.
I added a small comment to the docs that it can be given multiple times.
[draft to double check in CI that it actually works]
P.S. it would be nice to have an easy way to run the CI test locally, especially since they won't run automatically and someone needs to "ack" them first here on GH
> docs: clarify that `--karg` can be passed multiple times

- docs/src/filesystem.md
Let's talk about the `/var` trap more.
> docs: Expand on filesystem /var

- tests/integration/install-upgrade.sh
- tests/integration/playbooks/check-system.yaml
- tests/integration/playbooks/rollback.yaml
This PR will:
1. add rollback and bootc upgrade fetch timer test
2. To avoid hitting quay.io race limitation, add retry for podman push and podman build
> test: add rollback and bootc upgrade fetch timer test

- .github/workflows/ci.yml
- lib/src/cli.rs
- lib/src/install.rs
- lib/src/install/baseline.rs
- lib/src/install/osconfig.rs
- lib/src/lsm.rs
- lib/src/privtests.rs
First, in the install code, acquire a proper policy object.
Add helpers for writing files/directories that take a policy object and operate *solely* using fd-relative operations and don't fork off helper processes.
This is a notable cleanup because we don't need to juggle absolute file paths *and* fds, which avoids a lot of confusion. Our usage of a wrapper for the cap-std-ext atomic write API for generating files ensures that if the file is present, it will always have the correct label without any race conditions.
Change the one place we now call `chcon` as a helper process to be an explicit recursive selinux relabeling.  In the future we should switch to using a direct API instead of forking off `/usr/bin/chcon` - then everything would be fd-relative.
> Rework SELinux labeling more

- lib/src/deploy.rs
- lib/src/install.rs
deploy: Use alternative format for staging
Followup to e3db0108b194f420c014bdcbce0c3e705f3942f6
where this one was missed.  Copy-pasting that git log
for ease of consumption:
Same motivation as https://github.com/ostreedev/ostree-rs-ext/pull/604
Because fetching from a registry with the default sigverify is
the 90% case default, when we see this (and are formatting for
human consumption), use the "alternate" formatting to just
display the image name.
This makes the ostree stuff *much* less in the user's face
in the default path.
---
install: Clean up image output more
Ensure we use alternative formatting for the image reference
for consistency.
And move the image output (including digest) to the very
start where it's more centralized. …
> More image output cleanup

- docs/src/bootc-install.md
The current example for installing to a disk is slightly inconsistent as the truncated filename and the target in bootc do not match.
This trivial commit aligns them.
> docs: tweak install disk example

- lib/src/install.rs
- lib/src/lsm.rs
There's a bug in the ostree API here around nullability.
Closes https://github.com/containers/bootc/issues/403
> lsm/install: Use csum(), not name() from SELinux policy

- lib/src/install/osconfig.rs
The current location via tmpfiles.d to install the root ssh keys seems to be not working on firstboot. There is an error that `/root/.ssh` does not exist from `systemd-tmpfiles-setup` and indeed the authorized_keys file is on in `/root/.ssh`.
It seems like everything else in the firstboot in
tmpfiles.d is refering to `/var/roothome` instead of `/root` and switching to this for the location of the ssh keys solves the issue.
I tested this via bib and a local container using the new `bootc install to-filesystem` pipeline :) So hopefully it should finally work.
> osconfig: install root ssh keys to /var/roothome

- lib/src/cli.rs
- lib/src/install.rs
John is hitting an issue where we're failing to re-exec into the mount namespace when querying podman for some reason.  We log surprisingly little even at trace level before we get there. I don't think this will help debug it, but I had to carefully read the code to know that e.g. we've verified we're not running under rootless podman until the time we get there.
More logging especially at trace level is ~free so let's do it.
> install: Add some more debug/trace calls

- lib/src/containerenv.rs
- lib/src/install.rs
Previously this was just always None via Default.
Also updated trace logging to show the entire container_info struct.
All of those fields are potentially useful, not just engine.
> Correctly populate container environment rootless status

- lib/src/containerenv.rs
- lib/src/install.rs
This builds on https://github.com/containers/bootc/pull/413
---
This will catch rootless podman cases even more reliably (assuming
we were invoked with `--pid=host`).
> Trace rootless

- lib/src/cli.rs
- lib/src/install.rs
- lib/src/install/baseline.rs
So we can unit test with `assert_eq!()`.
> Add `#[derive(PartialEq, Eq))` for cli bits

- Cargo.lock
- cli/Cargo.toml
- lib/Cargo.toml
- lib/build.rs
- lib/src/cli.rs
Simple build-time code generation for now. Plan to add git info from the environment if it exists.
Fixes #361
> feat(build): Add extra version information

- .github/workflows/ci.yml
- lib/src/install.rs
- lib/src/lsm.rs
install: Change no-SELinux -> SELinux to a warning
We believe we have almost all the labeling work here covered,
so degrade this to a warning.
---
install: Change SELinux state into enum, serialize to aleph
We want to support the "installing SELinux target from SELinux-disabled
host" - but in case we run into problems, let's serialize the state
of things at install time into the aleph data, for the same reason
we save other relevant environmental data like the kernel version.
---
> install: Change no-SELinux -> SELinux to a warning && serialize to aleph

- lib/build.rs
- lib/src/deploy.rs
- lib/src/install.rs
- lib/src/lsm.rs
> Fix various accumulated clippy lints

- .github/renovate.json5
Renovate can't install 1.77 for some reason, and I'm not sure if it
can't install *any* version, or if something is just broken with 1.77
since it's relatively new.  So let's try 1.76 and see what happens.
> Add constraint on rust 1.76

- lib/Cargo.toml
Reverts containers/bootc#423
This is broken and didn't update Cargo.lock, roll it back until we figure out why renovate is failing, and then we'll have renovate re-do it correctly.
> Revert "fix(deps): update all patch dependencies"

- lib/src/cli.rs
- lib/src/deploy.rs
- lib/src/spec.rs
- lib/src/status.rs
- tests/integration/playbooks/rollback.yaml
I'd really hoped to do something more declarative here, and really flesh out the intersections with automated upgrades and automated rollbacks.
But, this just exposes the simple primitive, equivalent to `rpm-ostree rollback`.
> Add a `rollback` verb and `rollbackQueued` status

- .github/renovate.json5
This reverts commit 224f91ce9cc3ad4a0147b581ca2c5254500b1850.
Renovate is still trying (and failing) to install rust 1.77 despite
this change, so let's revert it.  I think renovate has bigger problems
anyway, and it doesn't have anything to do with the particular rust
version.
> Revert "Add constraint on rust 1.76"

- .github/workflows/ci.yml
- docs/src/SUMMARY.md
- docs/src/bootc-install.md
- docs/src/man-md/bootc-fetch-apply-updates-service.md
- docs/src/man/bootc-edit.md
- docs/src/man/bootc-install-print-configuration.md
- docs/src/man/bootc-install-to-disk.md
- docs/src/man/bootc-install-to-existing-root.md
- docs/src/man/bootc-install-to-filesystem.md
- docs/src/man/bootc-install.md
- docs/src/man/bootc-rollback.md
- docs/src/man/bootc-status.md
- docs/src/man/bootc-switch.md
- docs/src/man/bootc-upgrade.md
- docs/src/man/bootc-usr-overlay.md
- docs/src/man/bootc.md
- docs/src/upgrades.md
- lib/src/cli.rs
- xtask/src/xtask.rs
I went through the docs and cleaned some things up, fixed some missing content, etc.
Also a patch to `xtask` to make it so that `cargo xtask manpages` works even when $PWD is in `docs`.
> docs: Various updates and fixes

- lib/src/install.rs
- lib/src/mount.rs
At container start, /dev is snapshotted, so any new device files
don't get added unless /dev is bindmounted in. For now, check that
/dev is the same as the host's /dev via fsid. If they differ, it
means that /dev is not bindmounted.
Fixes #352
> Stop if /dev is not a bind mount with loopback

- docs/src/bootc-install.md
- docs/src/man-md/bootc-install-config.md
- lib/src/install/baseline.rs
- lib/src/install/config.rs
tests: Use `..Default::default()` for install config
To make adding a new field not require touching all the tests.
---
install: Add `block` to config, disable tpm2-luks unless opted-in
This allows the container image builder more control over
`bootc install to-disk` in the installation config.  Per discussion in
https://github.com/containers/bootc/issues/421
this one definitely requires integration by the base image,
and not all of them will want it.
(Or if the do want LUKS, they may want more control over it)
The default value is `block: ["direct"]` which only enables
the simple filesystem install.
This change allows two different things:
`block: []`
With this, `bootc install to-disk` will just error out.  It's
a way to effectively …
> install: Add `block` to config, disable tpm2-luks unless opted-in

- lib/src/privtests.rs
Was having trouble figuring out which place "Container tests" in an
error message was actually referring to.  Give these unique contexts.
> privtests: Differentiate duplicate contexts

- docs/src/filesystem.md
- docs/filesystem: Some fixups for `/var`
---
- docs/filesystem: Expand on /usr
Motivated by discussion in bib.
> docs/filesystem: 

- docs/src/building/users-and-groups.md
Came up in chat, I do think we want to make this an obvious thing to do because many "less stateful" workloads want it.
> users-and-groups: Explain patterns for tmpfs /home more

- plans/install-upgrade.fmf
To avoid galaxy server unstable issue, like `504 gateway timeout`, `error when getting available versions of collection community.general`, download two required collection packages and install them locally. And those two collections are more general and do not have too much update often.
> test: install ansible collection from tar.gz package

- docs/src/SUMMARY.md
- docs/src/building/bootc-runtime.md
Let's clarify this more; it's touched on in the main docs but worth elaborating on.
> docs: Add a new bootc-runtime.md

- docs/src/building/guidance.md
This won't work right now without special handling.
> docs/guidance: Talk about nesting containers

- docs/src/building/bootc-runtime.md
This one deserves a special entry.
> docs: Expand on HEALTHCHECK

- docs/src/building/bootc-runtime.md
Since SELinux is special let's elaborate on it more here.
> docs: Talk more about runtime properties, especially SELinux

- docs/src/intro.md
- docs/src/relationships.md
This helps share the broader context and mission of the project when thinking of it beyond bootc.
> docs: Add link to the bootable containers webpage

- .github/workflows/ci.yml
- lib/src/install.rs
- lib/src/install/baseline.rs
- lib/src/install/config.rs
This fixes a logical bug where for base images that don't have any install configuration at all, we errored out even if we were explicitly passed `--filesystem`.
This is just about making it easier to test base images that don't have an install config.
> install: Support being passed --filesystem with no install config

- docs/src/bootc-install.md
This PR is to fix error `ERROR Installing to disk: Loopback mounts (--via-loopback) require host devices (-v /dev:/dev)` when run `bootc install to-disk`.
> doc: add "-v /dev:/dev" in bootc install to-disk

- docs/src/bootc-install.md
- lib/src/blockdev.rs
When using a loopback device pointing to a file on a 9p filesystem (e.g. the home mount of a podman machine), using direct-io=on causes the partitioning via sgdisk to fail. This is a temporary fix until podman machine switches away from 9p or another fix is found. Direct IO can be enabled via the BOOTC_DIRECT_IO=on environment variable.
Fixes #485
> bugfix: Switch losetup to --direct-io=off by default

- tests/integration/files/rhel-9.template
- tests/integration/install-upgrade.sh
- tests/integration/mockbuild.sh
Since `rhel-bootc` image started using `updates` compose, the test should be updated as well.
This PR changed rhel compose URL to the same as what rhel-bootc used. That avoids compose update between nightly and updates.
> test: update test to use `updates` compose to align with rhel-bootc image

- docs/src/bootc-images.md
- docs/src/bootc-install.md
> docs: Link to bootupd in prominent places

- .github/workflows/ci.yml
- .github/workflows/integration.yml
Every time I (or someone else) force pushes to re-add the DCO we're wasting resources and/or just have added latency.
> ci: Add concurrency cancellation

- .github/labeler.yml
- .github/workflows/ci.yml
- .github/workflows/integration.yml
Let's try to skip the testing farm stuff in particular for documentation only changes.
> ci: Add control/skip-ci label

- lib/src/install/baseline.rs
- lib/src/task.rs
install: Explicitly print which block setup we're using
This is an important thing.
---
install: Print more information when making filesystems
- Label is mandatory so change the API to always take it
- Print the label we're using as a description of the fs
- Also print the fs type as it's notable info
---
> install: Two informational patches

- docs/src/bootc-images.md
- docs/src/building/bootc-runtime.md
We had SELinux info but I was expecting it in the
"information about images" section, not the "building" section.  Move it, and link from the previous place.
Then add the gotcha about toplevel directories.
> docs: Move selinux into image info, add toplevel gotcha

- Cargo.lock
This pulls in a few updates, notably support for `docker-archive` and `zstd`/`zstd:chunked` images.
> Update to ostree-ext 0.13.4

- docs/src/building/users-and-groups.md
This one is going to be a very common issue.
It is highly tempting to add some automatic merge logic for `/etc/passwd` to ostree, which would have different tradeoffs.
> users-and-groups: Document useradd httpd more

- docs/src/SUMMARY.md
- docs/src/filesystem-sysroot.md
- docs/src/filesystem.md
This one is also important to understand as growing the rootfs is a corner case.
> docs: Talk about sysroot, growing

- .github/workflows/ci.yml
- lib/src/install.rs
- tests/kolainst/install
It was raised in a discussion that it's rather easy to copy-paste this command you may find in a document and not fully understand what it does.
Let's prominently warn by default, with a timeout.
> install: Add prominent warning+timeout when targeting host root

- lib/Cargo.toml
Currently the effective MSRV is 1.74.1 per `cargo msrv`.  We have 1.75
available in c9s, so let's target that at minimum.
> Update MSRV to 1.75

- docs/src/SUMMARY.md
- docs/src/booting-local-builds.md
We want to make this use case feel awesome; today it doesn't for multiple reasons.
We probably want a `bootc status --booted-image` which would print the digested pull spec to start.
Then one could at least `podman pull $(bootc status --booted-image)`.
But we clearly *also* want to streamline exporting from the local ostree storage back into a container, which has some downsides/bugs right now.
> docs: Describe how to boot local builds

- docs/.gitignore
- docs/src/building/guidance.md
- docs/src/filesystem.md
This is where I expected to find it.
>   book: Move /opt redirection guidance to building

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- docs/book.toml
- docs/src/SUMMARY.md
- docs/src/building/users-and-groups.md
- docs/src/relationship-particles.md
- **ci/docs: Add mdbook-linkcheck**
- **docs: fix mdbook-linkcheck errors/warnings**
> mdbook linkcheck

- lib/src/install/baseline.rs
> install/baseline: Make `/boot` the same fs type as `/`

- lib/src/install.rs
- lib/src/install/baseline.rs
In order to simplify what we're doing here, let's drop the separate `/boot` aka XBOOTLDR partition by default for the `to-disk --block-setup=direct` path (the default).
We retain it when using `--block-setup=tpm2-luks` as it's required there.
Notably this kills off a hardcoded "ext4 for /boot" which is suboptimal for many reasons.
Longer term again I'd like to emphasize `install to-filesystem` with external installers, plus integrating external installation scripts as part of `bootc install to-disk`.
xref:
- https://github.com/containers/bootc/issues/499
- https://github.com/containers/bootc/issues/440
> install/to-disk: Drop separate /boot by default

- lib/src/deploy.rs
We had a `{prefix}` in the template, but nothing was set.  Let's print the number of layers.
Now, in theory this should be a fix to ostree-ext, but doing so would require a Rust API change, and anyways in the future we want to switch to podman pulls anyways.
> deploy: Add number of layers to fetch progress

- docs/src/SUMMARY.md
- docs/src/bootc-install.md
I incorrectly "fixed" this once alrady in:
https://github.com/containers/bootc/commit/ee78e9e7a07248c5690e3824f544aaea3d81069c
This effectively reverts that change to SUMMARY.md and performs the
correct change in boot-install.md instead.
> docs: Fix incorrect link for bootc-install-config

- Cargo.lock
- docs/src/man/bootc-edit.md
- docs/src/man/bootc-install-print-configuration.md
- docs/src/man/bootc-install-to-disk.md
- docs/src/man/bootc-install-to-existing-root.md
- docs/src/man/bootc-install-to-filesystem.md
- docs/src/man/bootc-install.md
- docs/src/man/bootc-rollback.md
- docs/src/man/bootc-status.md
- docs/src/man/bootc-switch.md
- docs/src/man/bootc-upgrade.md
- docs/src/man/bootc-usr-overlay.md
- docs/src/man/bootc.md
- lib/Cargo.toml
Regenerate manpages too.  I notice here that we're getting some unnecessary quoting in the man pages since I think the tooling doesn't know whether or not we're writing markdown in the Rust source comments or not.
More medium term we'll have to figure out a better workflow for this.
> Release v0.1.11

- docs/src/bootc-install.md
- Emphasize `to-filesystem` more, clarify `to-disk` is more "demo"; we definitely support "external installers" too with `to-filesystem`.
- Add machine-local state post-install section
> docs/install: A few changes

- docs/src/SUMMARY.md
- docs/src/man-md/bootc-install-config.md
1. Correct a typo in bootc-install-config.md
2. Keep the same format for man usage
3. Remove ".md" suffix in some man description
4. Add missing "bootc-install-to-existing-root"
> docs: Various doc improvements

- docs/src/building/guidance.md
- docs/src/filesystem.md
Came up in chat; we have this elsewhere, but let's reinforce this here.
> docs: Clarify mutability at build vs runtime

- hack/Containerfile
- hack/build.sh
- lib/src/docgen.rs
Colin Walters (2):
hack: Also support --build-arg=base=<fedora>
lib: Run `cargo fmt`
> two minor patches

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- hack/Containerfile
- lib/src/docgen.rs
- tests-integration/Cargo.toml
- tests-integration/README.md
- tests-integration/src/hostpriv.rs
- tests-integration/src/install.rs
- tests-integration/src/tests-integration.rs
A few things going on here:
- Rewrite logic from shell script into Rust (using xshell, so it's still convenient to fork commands)
- Make the test logic take an externally-built container image instead of using a `-v bootc:/usr/bin/bootc` bind mount
- Build the container image using our stock hack/Containerfile in Github Actions instead of building for c9s in GHA
- This all hence starts to make the logic reusable outside of Github Actions too; the container build is a known standard thing.
> Move install tests shell script into Rust

- lib/src/bootloader.rs
- lib/src/install.rs
- lib/src/install/baseline.rs
- lib/src/utils.rs
install: Add a spinner for container deployment
This can take substantial time.
---
install: Be verbose for EFI creation and bootloader install
We previously changed the rootfs `mkfs` invocation to be
verbose; for consistency let's do the same for the EFI partition
as well as the bootloader run just so people can see
what's going on more.
---
bootloader: Drop --src-root /
It's the default.
---
> install: A few minor patches

- lib/src/bootloader.rs
Same as #547, but I'm not sure how this instance wasn't caught
previously.
> lib: Run `cargo fmt`

- ci/installdeps.sh
(For Fedora - https://src.fedoraproject.org/rpms/bootc/pull-request/3)
Required after https://github.com/ostreedev/ostree-rs-ext/pull/628
> installdeps: Add libzstd-devel for non-fedora

- docs/src/man/bootc-install-to-disk.md
- docs/src/man/bootc-install-to-existing-root.md
- docs/src/man/bootc-install-to-filesystem.md
- docs/src/man/bootc-switch.md
- lib/src/cli.rs
- lib/src/install.rs
This is a useful transport, if you want to bootc switch from a local container store.
> Add containers-storage to available options

- docs/src/building/secrets.md
In the [current architecture](https://github.com/ostreedev/ostree-rs-ext/) unfortunately it's going to be hard for us to fix this...it's explicitly by design today: https://github.com/ostreedev/ostree-rs-ext/blob/c0e8c8fe9c3344b9d349e2c9371e1335e1173bef/lib/src/container/mod.rs#L427
To handle the "credential helper only" case we'd need to enhance skopeo with something like `--no-root-homedir`.
Closes: https://github.com/containers/bootc/issues/562
> secrets: Doc credential helper

- .github/workflows/ci.yml
- lib/src/privtests.rs
- Build from the hack/Containerfile flow but using Fedora
- Run that container instead of bind mounting in our binaries
> ci: Clean up fedora CI

- docs/src/building/guidance.md
The extra `&&` breaks the mv command.
> Fix command to move examplepkg log files

- docs/src/man/bootc-container-lint.md
- docs/src/man/bootc-container.md
- docs/src/man/bootc.md
- hack/Containerfile
- lib/src/cli.rs
- lib/src/lib.rs
- lib/src/lints.rs
Add an entrypoint that basically everyone can start
adding to their builds which performs some basic
static analysis for known problems.
---
(original description follows)
We know this does not fix #216 yet, we are working this in time-slots as a part of mobbing to address this. In the next update we plan on having the logic to check for one kernel complete. Then we can debate if we want the lint to be in this code base, or if we want it to be moved somewhere else.
> cli: add container lint

- lib/src/install.rs
It'd be cleaner to have this in ostree itself, but...in general right now it's really a special install-time only thing.
It's also not actually strictly speaking *needed* - since we mount this in the initramfs before policy is loaded.  However, I want to turn on a CI check that verifies that all files are labeled, and this is the sole remaining exception.
> install: Explicitly label .ostree.cfs

- Cargo.lock
- lib/Cargo.toml
I noticed we had some old crates being pulled in, and this was the cause.  We aren't actually using it...so drop it.
> Drop unused serde_with

- tests-integration/src/install.rs
Now that we've started to label the last holdout in the `.ostree.cfs` superblock, let's verify everything is properly labeled.
> ci: Fully test file labeling post-install

- Cargo.lock
- hack/build.sh
- lib/Cargo.toml
This pulls in at least the public authfile bits we want for the podman pull changes.  Also this transitively bumps our oci-spec dependency which lets us drop some imported "darling" crates.
> Update to ostree-ext 0.14.0, gvariant 0.5.0

- contrib/packaging/bootc.spec
- tests/integration/mockbuild.sh
Required to build zstd-sys - https://artifacts.osci.redhat.com/testing-farm/66cab0ec-1653-42ec-b482-a90001dbd65a/work-awskhuoovz0/plans/install-upgrade/aws/execute/data/guest/default-0/tests/integration/install-upgrade/rpm-build-1/output.txt
> tests/integration: install libzstd-devel

- Cargo.lock
Fixes the authfile brown paper bag bug.
> lib: Update to ostree-ext 0.14.1

- HACKING.md
- README.md
Let's give some recommendations here.
> docs: Add HACKING.md

- lib/src/cli.rs
- lib/src/deploy.rs
- lib/src/kargs.rs
- lib/src/lib.rs
Fixes https://github.com/containers/bootc/issues/255. Allows users to create files within `/usr/lib/bootc/kargs.d` with kernel arguments. These arguments can now be applied on a switch, upgrade, or edit.
General process:
- use ostree commit of fetched container image to return the file tree
- navigate to /usr/lib/bootc/kargs.d
- read each file within the directory
- push the contents of each file (kargs) into a vector containing all the desired kargs
- pass the kargs to the stage() function
Example Containerfile:
```Dockerfile
FROM quay.io/fedora/fedora-coreos:stable
RUN mkdir -p /usr/lib/bootc/kargs.d
RUN cat <<EOF >> /usr/lib/bootc/kargs.d/00-console.toml
kargs = ["console=ttyS0,114800n8"]
supported-arch = ["x86_64"]
EOF
RUN cat <<EOF >> /usr/lib/bootc/kargs.d/01-mitigations.toml
kargs …
```
> add `/usr/lib/bootc/kargs.d` support

- HACKING.md
- hack/lldb/Containerfile
- hack/lldb/dap-example-vim.lua
- hack/lldb/deploy.sh
- hack/lldb/etc/sudoers.d/wheel-nopasswd
- hack/lldb/etc/sysctl.conf
- hack/lldb/etc/systemd/system/lldb-server.service
This is useful for remote debugging bootc running in a VM.
Until podman-bootc has support for forwarding arbitrary ports, this custom solution is needed.
This has been working well for me and I thought it might be useful to include in the docs for others to try if they're interested.
> hack: Add remote lldb utilities to hack dir

- hack/Containerfile
- hack/provision-derived.sh
These are things that https://tmt.readthedocs.io/en/stable/ wants, and the goal is to support running under tmt more directly.
Part of https://github.com/containers/bootc/issues/543
With this I can run:
```
provision:
how: virtual
image: /home/walters/src/github/containers/bootc/target/testbootc-cloud.qcow2
summary: Basic smoke test
execute:
how: tmt
script: bootc status
```
> hack: Add support for installing cloud-init+rsync

- lib/src/status.rs
- tests/integration/playbooks/check-system.yaml
This prevents /sysroot from switching to being
persistently mounted as rw.
> status: Use prepare_for_write instead of require_root

- hack/build.sh
This must be a regression from the timestamp change: 91ed63caf196dd728fb7c7da10bdce40e2008504
Without this we fail to parse the timestamp and get errors; maybe something else changed.
Of course, we should use a non-Makefile language for this so we get proper error checking.  I may move some of the makefile bits into xtask.rs or so.
> build: Install git too

- xtask/Cargo.toml
New stable gives warning:
`default_features` is deprecated in favor of `default-features` and will not work in the 2024 edition
> Fix deprecation warning with rust 1.79.0

- lib/src/cli.rs
When running `rpm-ostree install <package>` without a reboot, `bootc upgrade` will fail. Prior to this, the error message was unclear of the cause.
fixes RHEL-36003
> upgrade: Add error message when staged deployment is incompatible

- lib/src/utils.rs
- tests-integration/src/tests-integration.rs
- Allow the needless_borrows in tests-integration
- Remove empty else block
> Clippy janitor cleanup

- lib/src/install.rs
I'm not sure if this fell out of a refactoring or not, but right now we end up emitting the warning here
twice in the case that we re-exec the current process in order to get the right SELinux label.
It's unfortunately a bit hard to truly minimize the set of things we do before `prepare_install`, so we'll just have to be mindful.
> install: Move warning after state and possible re-exec

- README.md
- docs/src/building/bootc-runtime.md
- docs/src/filesystem.md
This is definitely the `#1` confusion many people have to start;
it's very understandable!  Because in theory we *could* have
a runtime and a larger role, but it was an explicit choice
not to do that.
> docs: Even more about how bootc is not a container at runtime

- lib/src/blockdev.rs
- lib/src/install/baseline.rs
Now that we hard require the host's `/dev`, let's
drop our duplicate `devtmpfs` copy. My main motivation here is I wanted to add some other debugging and trying to invoke e.g. `lsblk` on our temporary copy doesn't work.
With the combination of the host `/dev` plus our invocation of udev settling, we shouldn't hit races.
> install/baseline: Drop separate /dev mount

- docs/src/man/bootc-container-lint.md
- docs/src/man/bootc-install-to-disk.md
- docs/src/man/bootc-install-to-existing-root.md
- docs/src/man/bootc-install-to-filesystem.md
- docs/src/man/bootc-install.md
- docs/src/man/bootc-switch.md
- lib/src/cli.rs
- lib/src/install.rs
It seems like in clap one can document both the verb and the option structure. Change things to consistently document the verbs, and expand the text.
> cli/docs: Expand and clean up clap doctext a bit

- HACKING.md
This commit adds a note to `HACKING.md` to clarify that the environment
variable `CONTAINER_CONNECTION` should be set to the name of the podman
machine.
As an inexperienced user of podman-machine, this detail was not obvious
to me (#611).
> HACKING.md: Clarify `CONTAINER_CONNECTION`

- tests-integration/src/runvm.rs
- Pass `--timestamp` to podman build to squash timestamps in order to gain reproducibilty, working around https://github.com/containers/buildah/issues/5592
- Fix the xattr reading code to correctly skip trailing nils
> tests-integration: Optimize rebuilds

- .packit.yaml
This PR is a continuous setting of https://github.com/containers/bootc/pull/613. It adds [Packit](https://packit.dev/) to run tmt integration test.
`testing-farm:fedora-40-x86_64:tmt-integration-test` is from [Packit](https://packit.dev/).
> test: add packit to run tmt integration test

- lib/src/install/baseline.rs
It's useful to see this; we're already somewhat verbose at install time.
> install: Add more information on target blockdev

- lib/src/cli.rs
- lib/src/install.rs
- lib/src/status.rs
Previous to this change, we were always pairing together two functions:
- `prepare_for_write()`
- `get_locked_sysroot()`
Make the latter automatically call the former (and make it private to the cli code).
This will avoid bugs like https://github.com/containers/bootc/pull/595/commits/dcfc7521acaf21072032777b9683796ff710bdfe where we forgot to call the first one and didn't end up with an unshared mountns.
While we're here, drop an unnecessary `async` from these functions, and just in case make `prepare_for_write()` idempotent.
> cli: Make sysroot lock automatically check root + setup mountns

- lib/src/install/baseline.rs
This patch enables partition layouts that do not include EFI partition and/or boot partition.
Without this patch, partition numbers becomes not consecutive, and subsequent `findpart` will fail.
> install: Support non EFI partition format

- lib/src/install/baseline.rs
This was originally done to match what CoreOS is doing, which is motivated by having Ignition configs that work cross-architecture.
We don't have the same constraints or focus; we encourage operation at filesystem level in general.
This just changes the baseline `to-disk` installer, anyone who wants to do things like cross-architecture matching can of course do so externally.
> install/baseline: Drop aarch64 reserved partition

- docs/src/filesystem-sysroot.md
When reading the docs i thought "ok so `/sysroot` is the physical root but then how does `/` work"? Did a `findmnt` on my Sway Atomic to find out. I only have a basic understanding of the topic at this point, just hoping that what i wrote there is correct :). Please let me know if it should be reworded.
> docs: Mention logical root mount point

- docs/src/bootc-images.md
On my system the path seems to be `/etc/selinux/targeted/policy` so i think the docs had a typo there.
> docs: Fix SELinux policy path

- Cargo.lock
- lib/Cargo.toml
Added support for configuring kernel arguments in container builds via the new `/usr/lib/bootc/kargs.d` file; these kernel arguments can be changed "day 2" via container updates. More in https://containers.github.io/bootc/building/kernel-arguments.html
New subcommand `bootc container lint` that can be used in container builds via e.g. `RUN bootc container lint`. This is intended to be a cheap command to run that will detect at build time some common problems.
- A variety of improvements to the documentation landed
- This release includes changes to the default `install to-disk` code and partitioning layout in preparation for supporting s390x, among other architectures.
- Significant work on testing landed, with more to come; this should increase velocity and confidence.
---
Raw git log: …
> Release 0.1.12

- docs/src/man/bootc-container-lint.md
- docs/src/man/bootc-container.md
- docs/src/man/bootc-edit.md
- docs/src/man/bootc-install-print-configuration.md
- docs/src/man/bootc-install-to-disk.md
- docs/src/man/bootc-install-to-existing-root.md
- docs/src/man/bootc-install-to-filesystem.md
- docs/src/man/bootc-install.md
- docs/src/man/bootc-rollback.md
- docs/src/man/bootc-status.md
- docs/src/man/bootc-switch.md
- docs/src/man/bootc-upgrade.md
- docs/src/man/bootc-usr-overlay.md
- docs/src/man/bootc.md
- lib/src/install.rs
install: Clarify /boot (optional) and root mount spec
- /boot has been optional for a while
- Clarify the root uuid
---
docs: Regenerate markdown
Pick up change in the previous commit, plus a few others.
---
> install: Clarify /boot (optional) and root mount spec

- hack/lldb/deploy.sh
- tests/integration/image-install-upgrade.sh
- tests/integration/playbooks/install.yaml
We're really going to need to switch over to having the container do dynamic mounts; cc https://github.com/containers/bootc/issues/380#issuecomment-1983721453
Just noticed this missing in one place, and found others with a grep.
Right now we do operate without, but it can be racier.
> tree: Add missing -v /dev:/dev in a few places

- lib/src/install/baseline.rs
Running bootc install commands on ppc64le system bails out
with unsupported architecture error.
ERROR Installing to disk: Creating rootfs: Unsupported architecture: powerpc64
This patch enables support for ppc64le arch.
Signed-off-by: Sachin Sant <sachinp@linux.ibm.com>
> Add support for ppc64le architecture

- lib/src/blockdev.rs
- lib/src/cli.rs
- lib/src/deploy.rs
- lib/src/docgen.rs
- lib/src/install.rs
- lib/src/kargs.rs
- lib/src/lsm.rs
- lib/src/status.rs
We were inconsistent here; I prefer this `StdExternalCrate` style. Unfortunately it's not stabilized, but this is a manual run with current nightly rustfmt. On the positive side, rustfmt will preserve this ordering in the future.
> tree-wide: rustfmt with `group_imports = "StdExternalCrate"`

- docs/src/man/bootc-status.md
- lib/src/cli.rs
- lib/src/status.rs
- tests/booted/001-test-status.nu
Prep for adding `--format=human` for example. But this is also useful for anything that explicitly wants to consume YAML today.
> status: Add explicit `--format` argument

- Cargo.lock
- hack/Containerfile
- lib/Cargo.toml
- lib/src/kargs.rs
No functional changes intended; just prep for further work.
---
kargs: parser cleanups
- Accept &str vs owned String, allowing dropping unnecessary `clone`
- It isn't parsing a file necessarily, just a string buffer, so rename
it
- Drop unnecessary `pub`
- Add doc comment
- Add error context to callers to be clear *which* file we failed
to parse
---
kargs: Add a few more unit tests
---
kargs: Parse booted kargs via cap-std, not liboverdrop
liboverdrop isn't helpful here because I don't think we want
or need right now to actually support things like having a file
in `/etc` or `/run` override the kargs. Especially for `/run`
there's no dynamic runtime state.
No functional changes intended, …
> kargs: Various cleanups

- hack/Containerfile
- hack/test-kargs/10-test.toml
- hack/test-kargs/20-test2.toml
- lib/src/install.rs
- lib/src/kargs.rs
- tests-integration/src/install.rs
This was a rather important miss; we need to pick
up the kargs.d files when doing a `bootc install` too.
---
> install: Pick up kargs.d kernel arguments too

- lib/src/install.rs
We juggle multiple things we call in different places the "rootfs", in some the container's root, in others the target root.
Add a handy member variable of `State` for the container root and use it consistently. This improves clarity now, and is prep for later patches.
> install: Only open / once

- lib/Cargo.toml
- lib/src/cli.rs
- lib/src/image.rs
- lib/src/lib.rs
- tests/booted/002-test-image-pushpull-upgrade.nu
We have a basic `bootc image list` but more interesting is
`bootc image push` which defaults to copying the booted
image into the container storage.
> cli: Add a new bootc image subcommand

- .copr/Makefile
Yet *another* copy of our build dependencies here... The core problem right now is that we embed pre-built manpages as part of the "source"...which means we need all of our build dependencies there.
It's tempting to switch to not generating man pages.
> copr: Use dnf builddep

- Cargo.lock
- lib/Cargo.toml
Supporting `kargs.d` at install time is a critical feature for kernel args.
> Release 0.1.13

- lib/src/cli.rs
- lib/src/kargs.rs
- lib/src/status.rs
We had an unused variable...should probably start denying that in CI.
Fix a few other style things while we have the patient open.
> tree-wide: Fix minor clippy lints

- README.md
HeliumOS is a new Linux distribution using bootc for immutability.
This PR would add HeliumOS to the list of operating systems and distros using bootc on the readme.
> Add HeliumOS to list of distributions using bootc

- lib/src/lints.rs
This verifies the syntax of all included `kargs.d` files. I hit this when I did a build in an image without `/usr/lib/bootc/kargs.d` and did a
`COPY foo.toml /usr/lib/bootc/kargs.d`
which created a regular file named `kargs.d` there.
> lint: Verify we can parse the kargs.d files

- docs/src/man/bootc-container-lint.md
- docs/src/man/bootc-container.md
- docs/src/man/bootc-edit.md
- docs/src/man/bootc-install-print-configuration.md
- docs/src/man/bootc-install-to-disk.md
- docs/src/man/bootc-install-to-existing-root.md
- docs/src/man/bootc-install-to-filesystem.md
- docs/src/man/bootc-install.md
- docs/src/man/bootc-rollback.md
- docs/src/man/bootc-status.md
- docs/src/man/bootc-switch.md
- docs/src/man/bootc-upgrade.md
- docs/src/man/bootc-usr-overlay.md
- docs/src/man/bootc.md
- lib/src/cli.rs
- lib/src/status.rs
- tests/booted/001-test-status.nu
- tests/booted/basic.py
In preparation for us changing the default output of `bootc status`
in the future (cc https://github.com/containers/bootc/issues/518 )
add `--format-version` that people can start using now to explicitly
request the current version.
It's possible that instead of a hard break we still support
outputting the current format for a while.
---
docs: Regenerate manpage markdown
---
> status: Add --format-version

- .copr/Makefile
This whole "install all the build tools to make a source rpm" flow rather stinks...
One thing that would help is for me (or someone else) to package cargo-vendor-filterer at some point.
> copr: Also install git

- .copr/Makefile
For some reason the copr process uses a f39 root, and we don't have our zstd dependency there.
Hopefully this will the last fix...
> copr: Use included spec

- lib/src/cli.rs
- lib/src/deploy.rs
- lib/src/install.rs
See individual patches. Motivated by https://github.com/containers/bootc/discussions/646
> install: Disable fsync() in repo when pulling && improved pull progress

- Cargo.lock
To pull in the fix for hardlinked `/etc`.
> Bump to ostree-ext 0.14.3

- docs/src/filesystem.md
This works fine now and is another alternative to solving the `/opt` problem.
> docs/filesystem: document state overlays

- lib/src/deploy.rs
This is preparation for the lifecycle bound image work. It will need access to the Deployment to read the bound image spec files.
> deploy: Return Deployment from deploy function

- docs/src/SUMMARY.md
- docs/src/package-managers.md
- Talk about readonly `/usr`
- Note how easy it is to do with podman
- Give examples with both `apt` and `dnf` as the exist today
- Include brief blurbs on transient and persistent changes
> docs: Add new package-managers section with guidance

- lib/src/cli.rs
- lib/src/deploy.rs
- lib/src/kargs.rs
- lib/src/utils.rs
deploy: Centralize karg computation
I happened to be looking at this code for an unrelated reason.
We had 3 copies of the function calling karg computation.
But that can just be pushed to a much lower level, right
before we tell ostree what to do.
---
kargs: Use merge deployment
This is in general for us right now a no-op, but is closer
to technically correct. In ostree the "merge deployment"
concept started out as "deployment we use for the original /etc"
which *may be different* from the booted deployment. For example,
when one wants to do a "factory reset", we want to start
from a fresh /etc.
The other important case here is when we're doing a fresh
install (or into a new stateroot) there may be no merge
deployment at all! It wouldn't …
> kargs: More cleanups

- tests/booted/002-test-image-pushpull-upgrade.nu
- tests/e2e/playbooks/rollback.yaml
This PR fixed two errors:
1. do not check cachedUpdate.imageDigest in rollback test. The cachedUpdate.imageDigest is always null. We have wget package checking for rollback successful or not.
2. do not delete image before copy it. Fix "ERROR Pushing image: Export: Copying image: No such image" in integration test.
> test: Error fix

- Cargo.lock
- lib/Cargo.toml
- lib/src/generator.rs
This makes string literals way more legible. Prep for more tests.
> tests: Use indoc

- lib/src/blockdev.rs
- lib/src/bootloader.rs
- lib/src/install.rs
- lib/src/install/baseline.rs
This series is prep for 
- https://github.com/containers/bootc/pull/665
- https://github.com/containers/bootc/pull/667
---
blockdev: Get more properties
- Add `partlabel` in prep for ppc64le bootloader bits
- Add `maj_min` and `start` which we want for s390x
- Clearly move the filesystesm-related bits to a separate
section
---
blockdev: Backfill `start` if missing
This way we continue to support the version of util-linux in C9S
today.
---
blockdev: Use `-b` for lsblk, hard require size property
I noticed that the JSON format inconsistently uses human-readable
sizes for some properties, but not others. `size` happens to
be one of the ones were it outputs human readable. But I think
we will …
> blockdev+install updates

- Cargo.lock
- lib/Cargo.toml
- lib/src/boundimage.rs
- lib/src/deploy.rs
- lib/src/lib.rs
This is just a PoC using quadlet/systemd to pull "lifecycle" bound images. 
I have a bootc image pushed to `quay.io/ckyrouac/bootc-lldb-bound:latest` for testing. Any custom bootc image with quadlet image files located in `/etc/containers/systemd/bootc` should work.
Steps for testing:
1. Build a container image with these changes and start a VM: https://github.com/containers/bootc/blob/main/HACKING.md#creating-your-edit-compile-debug-cycle
2. `sudo bootc switch quay.io/ckyrouac/bootc-lldb-bound:latest`
3. Validate the `quay.io/ckyrouac/bootc-lldb` image was pulled via `sudo podman images`
4. Validate the new image is staged via `sudo bootc status`
> Retrieve bound images when staging new image

- .github/workflows/ci.yml
- CONTRIBUTING.md
- Makefile
The `make validate-rust` reproduces locally the same checks we run in CI as gating by default; hook it up to the existing `make validate`.
> build-sys: Add `make validate-rust`

- Cargo.lock
- lib/src/boundimage.rs
- This is an abstraction we want to use in multiple places
- It has shared convenience helpers like `read_to_string` which reduce code here
> boundimage: Use new RootDir API

- Cargo.lock
- lib/Cargo.toml
- lib/src/kargs.rs
This avoids annoyances with constantly checking for utf-8.
> kargs: Introduce usage of fs_utf8

- lib/src/blockdev.rs
- lib/src/bootloader.rs
- lib/src/install.rs
- lib/src/install/baseline.rs
This works around an issue where `lsblk` ends up parsing data cached from udev in `/run/udev`, but we don't have that mounted by default.
Adding a new mount point hard requirement is logistically complicated right now - we will eventually switch
to dynamic mounts with `open_tree` (cc
https://github.com/containers/bootc/issues/380 )
but this is a relatively straightforward workaround.
> install: Use sfdisk, not lsblk

- Cargo.lock
Closes: https://github.com/containers/bootc/issues/679
> Bump to ostree-ext 0.14.4

- lib/src/bootloader.rs
- lib/src/install/baseline.rs
Bootloader code currently writes required data to base/parent
device (eg /dev/sda). This logic does not work for ppc64le
architecture as bootloader configuration has to be written
to PRePboot partition(typically first partition of disk).
This patch adds code to identify PowerPC-PReP-boot partition
(for ppc64le architecture) and writes bootloader data to it.
realpath command is used to identify PReP partition.
Incase of writing to qcow2 image, first partition of loopback
device is used as it points to PRePBoot. In order to identify
loopback device usage the patch introduces a boolean flag to
filesystem_impl() routine.
Signed-off-by: Sachin Sant <sachinp@linux.ibm.com>
> lib/bootloader: Write to PReP partition on ppc64le

- lib/src/boundimage.rs
Two minor things:
- I think it's cleanest to separate parsing from files; we were passing the file name to the parser just to include it in the error message
- We had the file path *twice* in errors (once in the context, once in the returned error)
Fix both these things by using `with_context` that includes the path in the callers.
So the resulting error should look like e.g. `Parsing /usr/lib/bootc/bound-images.d/foo.image: Missing Image field` or so.
> boundimage: Drop duplicate filenames from errors

- lib/src/boundimage.rs
- The `.write` API is really convenient to write a string to a file
- Use `indoc!` to format the strings with embedded newlines more readably
> boundimage: Use `indoc!` and `.write`

- lib/src/bootloader.rs
- lib/src/install.rs
- lib/src/mount.rs
This is a part of s390x enablement https://github.com/containers/bootc/issues/569
Currently, the `zipl` command is called via libostree to install bootloader on s390x, but it does not work correctly on a loop device.
This patch changes `bootc` to execute the `zipl` command directly with appropriate command line options for installation on a loop device.
> install: Use zipl to install bootloader on s390x

- .packit.yaml
- Add s390x because it's a target too
- Drop other arches for non-primary targets just because the chance they break is basically nil
> packit: Adjust arch targets; build on s390x

- Makefile
Let's ensure these directories exist by default, because we want people to drop things there - and having to create the directory in derived images invites typos.
> build-sys: Pre-create `kargs.d` and `bound-images.d`

- Makefile
- xtask/src/xtask.rs
I plan to add more generated-from-source files, so generalize the target which is currently specialized to manpages.
> build-sys: Generalize manpage bits to `make update-generated`

- lib/src/blockdev.rs
- lib/src/install/baseline.rs
I think this may also help with the install flake we've been
seeing where we somehow get the partitions mixed up.
- Use `sfdisk` in the baseline install because it's what
we're switching to using anyways later on
- Add some verification at least for the root and EFI partitions
that we read back the expected type
>  install/baseline: use sfdisk, not lsblk

- .github/workflows/docs.yml
- docs/src/SUMMARY.md
- docs/src/experimental-bootc-image.md
ci: Document building the docs locally
It was slightly less than obvious.
---
docs: Add experimental section w/`bootc image`
Let's follow a standard operating procedure for our experimental features:
- A github tracking issue
- A documentation section like this one
---
>  docs: Add experimental section w/`bootc image`

- lib/src/install.rs
- lib/src/install/baseline.rs
This patch enables support for the s390x architecture.
> install: Support the s390x architecture

- lib/src/boundimage.rs
boundimage: use utils::sysroot_fd
These landed independently; use the shared helper.
---
boundimage: Add some module docs
---
boundimage: Add some tracing::debug
To debug things.
---
> boundimage: A few minor things

- lib/src/install.rs
Code similar to this was part of the original https://github.com/containers/bootc/pull/559 - this is prep for pulling bound images at install time
---
install: Split internal main phase into two
Split up:
- Initialize empty sysroot
- Install container to sysroot
This makes it easier to do more things that still
reference the sysroot.
(The git diff for this change is...really nice IMO,
very straightforward)
---
install: Change helper to return deployment too
Prep for further changes.
---
> install: Two prep changes for pulling bound images at install time

- contrib/packaging/bootc.spec
Sadly RPM requires that we explicitly enumerate all the files we ship.
> spec: Add the new bootc-experimental dir

- Cargo.lock
- lib/Cargo.toml
- lib/src/blockdev.rs
- lib/src/install/baseline.rs
The `ioctl` to reread the partition table was the last thing pulling in `nix`. Honestly especially in the install path I have no problem forking external binaries, and since we're already depending on util-linux-core for other things like `sfdisk` and `lsblk`, it just makes sense to so here with the command whose entire role in life is to just issue that `ioctl`.
This drops out an older verison of `nix` (which is a fine crate, but again I think `rustix` is nicer). There's a different version pulled in via libsystemd, but we can get to that later.
> install: Fork `blockdev --rereadpt` instead of internal ioctl

- tests/e2e/bootc-install.sh
- tests/e2e/playbooks/check-system.yaml
Integration test for the changes in: https://github.com/containers/bootc/pull/401
> Test: implement kargs e2e test

- lib/src/boundimage.rs
- lib/src/utils.rs
utils: Drop unnecessary lint allow
This function doesn't use unsafe anymore.
---
boundimage: Use high level `deployment_fd` helper
This keeps things even simpler, it's the same thing we're doing
in `kargs.rs`.
---
> boundimage: Use high level `deployment_fd` helper

- lib/src/boundimage.rs
- lib/src/install.rs
utils: Drop unnecessary lint allow
This function doesn't use unsafe anymore.
---
boundimage: Use high level `deployment_fd` helper
This keeps things even simpler, it's the same thing we're doing
in `kargs.rs`.
---
boundimage: More struct definition to top
I think it's generally best to have type definitions come before
the code that references them.
---
boundimage: Drop const parameter
We were always passing this single constant value to the
function; let's just reference it inside the function
and simplify callers.
---
boundimage: Rename helper function
I think this name is a bit clearer. …
> Bound install time

- cli/src/main.rs
- lib/src/cli.rs
This works around bootc-image-builder not setting HOME, in combination with `podman` bombing if it's unset.
Needed for bound images as part of bootc-image-builder.
> main: Set HOME very early on if unset

- lib/src/blockdev.rs
- lib/src/install.rs
I am not aware of any reason to use anything else; in theory we can leave this up to the OS, but...I think using `dos` format is really probably just a legacy mistake now.
And if we see anything else...well, let's at least warn.
> install: Warn if we're not installing to gpt

- Makefile
- contrib/packaging/bootc.spec
- docs/src/experimental-logically-bound-images.md
- lib/src/boundimage.rs
This is a stable enough feature to be included in the primary bootc directory.
> boundimages: Switch from bootc-experimental to bootc

- lib/src/install/baseline.rs
Reusing a disk (after manually deleting partitions on it) with xfs
as file system, install to-disk command fails complaning about
existing file system on root partition.
Creating root filesystem (xfs) on device /dev/sdb2 (size=107.4 GB)
> mkfs.xfs -m uuid=4826aa5b-0dd0-4382-a0c1-7c0b77cfd47d -L root /dev/sdb2
mkfs.xfs: /dev/sdb2 appears to contain an existing filesystem (xfs). 
mkfs.xfs: Use the -f option to force overwrite.
Use the -f option with mkfs.xfs to force overwrite.
Signed-off-by: Sachin Sant <sachinp@linux.ibm.com>
> install: Force mkfs.xfs to overwrite

- lib/src/boundimage.rs
- lib/src/install.rs
Instead of fetching images from the network at install time, require them to be present in the host's container storage (the same place we expect to find the bootc image).
There are numerous advantages to this, such as the basic fact that this helps one avoid re-pulling images at each install.
But more importantly it aligns with the needs of "hermetic builds" which want to pre-fetch content from the network into the target environment.
For example when generating a disk image with bootc-image-builder or so, a build tool can consistently preload all the input images (including the bootc base) into the container store, and know that the install process to generate the disk will use those images.
xref https://github.com/containers/bootc/issues/715
> install: Fetch bound images from host's /var/lib/containers

- docs/src/SUMMARY.md
- docs/src/bootc-via-api.md
- docs/src/host-v0.schema.json
- lib/src/cli.rs
- lib/src/k8sapitypes.rs
- lib/src/spec.rs
- xtask/src/xtask.rs
- Add a hidden command to generate JSON schema
- Wire it up to the new `make update-generated`
- Describe how to use it in the docs
> Add JSON schema and guidance on API usage to docs

- Cargo.toml
- lib/src/lib.rs
- tests-integration/src/tests-integration.rs
A new instance of this snuck in under xtask, this will make sure it's
covered everywhere going forward.
> build: move needless_borrow lint allows to be global

- lib/src/cli.rs
- lib/src/deploy.rs
- lib/src/install.rs
We broke `bootc image copy-to-storage` because the change to run a separate pull phase was using the digested (source) pull spec incorrectly. Somehow the deploy phase was picking that up and not also writing the non-digested (target) spec.
> install: Correctly set target imgref at pull time

- lib/src/lib.rs
This dox/doc_cfg attr looks like it was originally included when bootc
was split off from ostree into its own repo but never actually used
here, so just remove it.
> Fix compiler warning on rust 1.80

- lib/src/cli.rs
- lib/src/install.rs
- lib/src/store/mod.rs
install: Rework to use Storage
Prep for https://github.com/containers/bootc/issues/721
---
storage: Change to return Result
Prep for adding more falliable initialization here.
---
> storage: Two prep changes

- lib/src/install.rs
install: Allocate a global tmpdir
We allocate temporary things in a few places, and it's
handy to have a pre-created single directory for the
whole install process to use instead of creating
individual tempfiles.
---
install: Use tmpdir for target fetch verification
We create a transient ostree repo, to do so use the global
install tmpdir.
---
> install: Allocate a global tmpdir

- lib/src/install.rs
- lib/src/utils.rs
When I added the `Task` stuff it wasn't with the idea that we'd use it for *all* subprocess invocations.
I think in some cases we really just do want a `Command` instance without the extra wrappering.
Add an implementation (there are many of variants of this out there in lots of Rust codebases)
This makes sense to use instead of `Task` where we're using `.quiet()` so that we don't print the description, and especially where we don't expect the task to fail usually, so it's OK if the error message is odd.
> utils: Add a little CommandRunExt helper trait

- lib/src/deploy.rs
- lib/src/kargs.rs
This is prep for switching over bound images to use the bootc container storage (and I think is what we want for the bootc-using container-storage).
In the future I think we can actually stop using the magic `Deref` implementation actually too.
> cli: Thread Storage through more places

- lib/src/install.rs
- lib/src/install/osbuild.rs
- lib/src/podman.rs
install: Factor out an osbuild module
Unfortunately the interactions/workarounds here are going to grow, so make
a module to encapsulate them.
---
install: Work around bootc-image-builder using /run/osbuild/containers
xref: https://github.com/osbuild/bootc-image-builder/issues/560
Basically osbuild/bib puts the host `/var/lib/containers` at
`/run/osbuild/containers`. If we detect this situation, bind
mount it to `/var/lib/containers` so that the container
stack we invoke at install time can find logically bound
images.
Closes: https://github.com/containers/bootc/issues/715
---
> install: Work around bootc-image-builder using /run/osbuild/containers

- cli/Cargo.toml
- lib/Cargo.toml
- lib/src/utils.rs
- tests-integration/src/install.rs
utils: Allow non-static str for spinner
I have a use case for dynamic strings, this just requires
duplicating the string for the progress bar.
---
lib: Enable mount API for rustix
Will be used by future changes.
---
tests: Add generic post-install verification
Prep for more work.
---
utils: Capture stderr, add async
We want to capture stderr by default in these methods
so we provide useful errors.
Also add an async variant.
---
> A few prep commits for https://github.com/containers/bootc/pull/724

- Makefile
- docs/src/experimental-logically-bound-images.md
- lib/src/boundimage.rs
- lib/src/cli.rs
- lib/src/deploy.rs
- lib/src/image.rs
- lib/src/imgstorage.rs
- lib/src/install.rs
- lib/src/lib.rs
- lib/src/podman.rs
- lib/src/store/mod.rs
- tests-integration/src/install.rs
- tests/booted/readonly/010-test-bootc-container-store.nu
- tests/booted/test-logically-bound.nu
Closes: https://github.com/containers/bootc/issues/721
- Initialize a containers-storage: instance at install time
(that defaults to empty)
- Open it at the same time we open the ostree repo/sysroot
- Change bound images to use this
We are *NOT* yet changing the base bootc image pull to use this.
That's an obvious next step (xref
https://github.com/containers/bootc/pull/215 ) but will come later.
> Introduce bootc-owned container store, use for bound images

- lib/src/blockdev.rs
- lib/src/cmdutils.rs
- lib/src/image.rs
- lib/src/imgstorage.rs
- lib/src/install.rs
- lib/src/lib.rs
- lib/src/mount.rs
- lib/src/podman.rs
- lib/src/utils.rs
blockdev: Drop dead code
We have no use for listing all devices, so drop it.
---
blockdev: Fold listing fn
We only have a case for listing one device.
---
lib: Move Command extensions to new `mod cmdutil`
Prep for more stuff there.
---
cmdutils: Add helper to run and parse JSON
It's handy to have a central helper for this.
---
blockdev: Use JSON parsing helper
It's shorter and clearer and we get stderr.
---
Switch a few Task users to direct Command
I never intended the `Task` abstraction to be "the one way to
run subprocesses in bootc"...let's …
> A few misc cleanups

- lib/src/bootloader.rs
These may exist in the wild, even if we want to encourage GPT in the future.
Closes: https://github.com/containers/bootc/issues/742
> install/ppc64le: Also handle MBR partitions

- .packit.yaml
- plans/e2e.fmf
- tests/e2e/bootc-install.sh
- tests/e2e/playbooks/check-system.yaml
- tests/e2e/playbooks/deploy-libvirt.yaml
This PR includes:
1. add centos stream 10 all arch rpm build
2. add e2e test for centos stream 10
> test: add centos stream 10 rpm build and e2e test

- docs/src/filesystem-sysroot.md
Someone looking to understand how things work is probably interested in this notable detail.
> docs: Also mention the bootc container storage in /sysroot

- lib/src/boundimage.rs
- lib/src/imgstorage.rs
Also print how many bound images we have, since it's interesting and relevant information.
> store: Only print "Fetching bound image" if it's not there

- Cargo.lock
- lib/Cargo.toml
- lib/src/blockdev.rs
- lib/src/image.rs
- lib/src/imgstorage.rs
- lib/src/install.rs
- lib/src/lib.rs
- lib/src/mount.rs
- lib/src/podman.rs
- utils/Cargo.toml
- utils/src/command.rs
- utils/src/lib.rs
In general the codebase is starting to get to the size where some internal crates make sense. Let's start with the inevitable catchall "utils" crate which
starts off just holding our helper traits for
subprocesses.
> Split off an internal "bootc-utils" crate

- tests/e2e/bootc-install.sh
- tests/e2e/files/caddy.container
- tests/e2e/files/node_exporter.container
- tests/e2e/playbooks/check-system.yaml
- tests/e2e/playbooks/install.yaml
This PR added logically bound images e2e test.
> test: add logically bound images

- LICENSE-MIT
This one has a History...I think when I made bootc I copied some of the "raw project structure" from a different Rust project...maybe one of these:
https://github.com/search?q=org%3Acoreos%20path%3ALICENSE-MIT%20openat&type=code
There's nothing copyrightable by the openat developers here; switch to a "standard" copy of LICENSE-MIT from
https://github.com/rust-lang/rust/blob/master/LICENSE-MIT
(BTW notice also https://github.com/rust-lang/rust/commit/2a8807e889a43c6b89eb6f2736907afa87ae592f
which dropped the copyright)
Closes: https://github.com/containers/bootc/issues/766
> LICENSE-MIT: Canonicalize

- lib/src/imgstorage.rs
Should really have noticed this, a bit embarrassing that we're spewing this on the install path.
> imgstorage: Quiet initialization phase

- lib/src/cli.rs
No reason not to have this.
Closes: https://github.com/containers/bootc/issues/770
> cli: Add `switch --apply`

- lib/src/install/baseline.rs
Port from gdisk to sfdisk (util-linux) as gdisk is less well maintained and is specifically targeted to be dropped from RHEL10 (xref https://issues.redhat.com/browse/RHELMISC-6651 ).
Closes: https://github.com/containers/bootc/issues/774
> install/baseline: Use sfdisk, not sgdisk

- lib/src/cli.rs
- lib/src/deploy.rs
- tests-integration/src/install.rs
Solves #776
Right now the integration tests have some hacky code to clear out `ostree` stateroots  (see `reset_root` function), it would be better if they could rely on a bootc command to take care of that for them instead
This commit adds a new `state wipe-ostree` subcommand to the CLI that removes all `ostree` deployments from the system using native ostree bindings. This makes it easier to later rm -rf the stateroots and have a clean slate for the next test.
> cli: Add new `state wipe-ostree` subcommand

- lib/src/install.rs
- tests-integration/src/install.rs
This commit makes it so that the `bootc install` stateroot will be configurable (it defaults to `default`). For now this is a hidden CLI option until we decide whether we want to commit to this API.
In the future we also want to make the stateroot of `bootc switch` be configurable (https://github.com/containers/bootc/pull/617) so that users can install an image to a new stateroot while they already have an existing stateroot
Also removed the constant `STATEROOT_DEFAULT`, we're now simply taking it from the `ostree_ext` crate
> install: Make stateroot configurable

- lib/src/cli.rs
- lib/src/deploy.rs
> cli: wipe_ostree in spawn_blocking

- lib/src/install.rs
Use a method to get the stateroot instead of repeating the defaulting logic
_Originally posted by @cgwalters in https://github.com/containers/bootc/pull/622#discussion_r1750378337_
> install: Use a method to get the stateroot

- lib/src/install.rs
Solves #781
This commit replaces the `ostree admin os-init` CLI invocation with the `sysroot.init_osname` API call. This is a more direct way to initialize the stateroot.
> install: `sysroot.init_osname` API instead of CLI

- Cargo.lock
- lib/Cargo.toml
The major change here is we dropped our dependency on `gdisk` in favor of sfdisk from util-linux, which is more widely available and better maintained.
> Release 0.1.16

- lib/src/install.rs
- lib/src/lsm.rs
We have e2e tests for this today. On a related topic, unfortunately the way bootc-image-builder sets up the container it runs bootc in it doesn't mount selinuxfs, so we see SELinux as disabled when it's not.
We should fix that, but it also avoids user confusion to drop the warning here.
While we're here, change things so we more consistently log the state computed.
Closes: https://github.com/containers/bootc/issues/419
> install: Drop SELinux-disabled warning

- xtask/src/xtask.rs
tmt: Add TMT_PLUGINS env to tmt run invocation
This is temporary while waiting for tmt to release the bootc provision
plugin.
----
tmt: Add TMT_VERBOSE env var
1 -> enabled. This adds -vvvvv to the tmt run invocation when using
`make test-tmt` to stream detailed test run output.
> TMT test tweaks

- lib/src/cli.rs
- lib/src/fixtures/spec-only-booted.yaml
- lib/src/fixtures/spec-ostree-to-bootc.yaml
- lib/src/fixtures/spec-rfe-ostree-deployment.yaml
- lib/src/fixtures/spec-staged-booted.yaml
- lib/src/fixtures/spec-staged-rollback.yaml
- lib/src/status.rs
supersedes #602 and builds on top of #639
> cli: Add a human readable format to status

- .github/workflows/ci.yml
- Cargo.toml
- Makefile
- cli/src/main.rs
- lib/build.rs
- lib/src/boundimage.rs
- lib/src/cli.rs
- lib/src/lib.rs
- lib/src/lsm.rs
- lib/src/podman.rs
- lib/src/status.rs
- lib/src/task.rs
- lib/src/utils.rs
- tests-integration/src/tests-integration.rs
- utils/src/command.rs
- xtask/src/xtask.rs
Add `dead_code = "deny"` to our default lints; we had a compiler warning for this in main.
Fix the warning by moving the human readable test code into `#[cfg(test)]`.
While we're here, move the other lib.rs lints into the crate; enforcing docs for *everything* at first I thought might be heavy handed but actually is fine as it only applies to things that are `pub`, of which we don't actually have that much so it mainly forced me to add some stub docs for the modules, which is probably a good idea.
> Make lints stricter, apply crate wide

- Cargo.lock
- lib/Cargo.toml
- lib/src/deploy.rs
Only one tiny change required thankfully for this one!
This drops out duplicate versions of oci-spec from our lockfile too which is nice.
> Update to ostree-ext 0.15

- lib/src/fixtures/spec-via-local-oci.yaml
- lib/src/status.rs
status: Change transport display
Registry is the assumed default; let's be quieter (less output)
in this default/expected case.
If we're using something else (e.g. `oci`) then put it
inline with the image name as that's something one can
pass to e.g. `skopeo`.
---
status: Minor code refactorings
- Rename variable to `slot_name` as I think it's a bit clearer
---
status: Factor out helpers for rendering container image
Prep for more work; no functional changes.
---
> Status tweaks

- Cargo.lock
- lib/src/cli.rs
- lib/src/deploy.rs
- lib/src/spec.rs
- lib/src/store/ostree_container.rs
> Bump ostree-ext to 0.15.1 and use proper digests where possible

- docs/src/experimental-logically-bound-images.md
Point to the podman discussion about `--userns=auto` instead.
> docs/lbi: Note non-support of "rootless"

- lib/src/blockdev.rs
- lib/src/lsm.rs
- lib/src/mount.rs
- utils/src/command.rs
ref https://github.com/containers/bootc/discussions/793
> utils: Add a `log_debug()` helper

- lib/src/store/ostree_container.rs
- tests/booted/readonly/001-test-status.nu
Sadly this code got forked from ostree-rs-ext, where we were doing things correctly. Add the fallback
to the config.
> store: Get timestamp from config or annotation

- docs/src/man/bootc-container-lint.md
- docs/src/man/bootc-container.md
- docs/src/man/bootc-edit.md
- docs/src/man/bootc-install-print-configuration.md
- docs/src/man/bootc-install-to-disk.md
- docs/src/man/bootc-install-to-existing-root.md
- docs/src/man/bootc-install-to-filesystem.md
- docs/src/man/bootc-install.md
- docs/src/man/bootc-rollback.md
- docs/src/man/bootc-status.md
- docs/src/man/bootc-switch.md
- docs/src/man/bootc-upgrade.md
- docs/src/man/bootc-usr-overlay.md
- docs/src/man/bootc.md
- lib/src/cli.rs
- lib/src/status.rs
- Output a clear message when we're not booted
- Update the docs and help to reflect current reality (e.g.
format is stable) and include some guidance on use cases
> status: Output targeted message in non-bootc case, update docs

- tests/e2e/playbooks/check-system.yaml
Test comes from issue https://github.com/containers/bootc/issues/800.
Both rpm-ostree and bootc bump ostree-rs-ext. This test is to avoid version-skew issue.
Test already catch this issue in our CI in rpm-ostree status test (https://artifacts.dev.testing-farm.io/00c7ce6c-d233-448f-891f-4fb484d4d710/) , but I did not failed this test. Let's enabled the error checking there.
```
TASK [check rpm-ostree status] *************************************************
changed: [guest] => changed=true 
cmd:
- rpm-ostree
- status
delta: '0:00:00.140106'
end: '2024-09-19 20:38:24.470069'
msg: ''
rc: 0
start: '2024-09-19 20:38:24.329963'
stderr: ''
stderr_lines: <omitted>
stdout: |-
State: idle
Deployments:
● (error fetching image metadata)
Timestamp: 2024-09-19T20:32:03Z
stdout_lines: <omitted>
```
> test: add ostree-rs-ext version-skew test

- docs/src/filesystem.md
We want to be clear that toplevel directories for mountpoints need to be created in the container build.
Also, this moves the transient root and stateoverlay to markdown level 2, where they should have been.
Closes: https://github.com/containers/bootc/issues/814
> docs/filesystem: Mention toplevels and mountpoints

- lib/src/kargs.rs
This breaks in situations where `/tmp` is on e.g. overlayfs which sadly is the podman/docker default.
> kargs: Skip xattrs in tests

- docs/src/bootc-install.md
Without this, we error out with:
ERROR Installing to disk: Loopback mounts (--via-loopback) require host devices (-v /dev:/dev)
> docs: install: Add /dev volume mounts for loopback example

- lib/src/imgstorage.rs
- tests/booted/test-logically-bound-install.nu
- tests/containerfiles/lbi/Containerfile
- tests/containerfiles/lbi/usr/share/containers/systemd/podman.image
- xtask/src/xtask.rs
We are unable to copy a signed image from c/storage -> c/storage while preserving the signature. See
https://github.com/containers/image/issues/2599
fixes #812
> lbi: Add --remove-signatures to install time lbi copy

- Cargo.lock
- lib/Cargo.toml
- lib/src/lsm.rs
It isn't an actively maintained crate and our usage is tiny
and not performance sensitive enough to warrant the zero-copy
it entails.
Just motivated by doing a pass over our dependencies.
> Drop gvariant

- docs/src/SUMMARY.md
- docs/src/logically-bound-images.md
The feature is working as is and provides a lot of value, so let's stabilize it.
Closes: https://github.com/containers/bootc/issues/128
> Stabilize logically bound images

- Cargo.lock
- cli/Cargo.toml
- docs/src/man/bootc-container-lint.md
- docs/src/man/bootc-container.md
- docs/src/man/bootc-edit.md
- docs/src/man/bootc-install-print-configuration.md
- docs/src/man/bootc-install-to-disk.md
- docs/src/man/bootc-install-to-existing-root.md
- docs/src/man/bootc-install-to-filesystem.md
- docs/src/man/bootc-install.md
- docs/src/man/bootc-rollback.md
- docs/src/man/bootc-status.md
- docs/src/man/bootc-switch.md
- docs/src/man/bootc-upgrade.md
- docs/src/man/bootc-usr-overlay.md
- docs/src/man/bootc.md
- lib/Cargo.toml
We'll support all APIs and features we have now for the forseeable future.
Why not 1.0.0? Just to avoid making this version feel too "special".
> lib: Bump version to 1.1.0

- tests/booted/test-logically-bound-install.nu
- tests/containerfiles/lbi/usr/share/containers/systemd/podman.image
- xtask/src/xtask.rs
This way we don't need to add any credentials to github.
> lbi: Switch to unauthenticated ubi9 for lbi test

- docs/src/filesystem-sysroot.md
We were failing to publish the docs because of this.
> docs: Fix link

- CONTRIBUTING.md
- README.md
README.md: Link to community forums
For now we're reusing the Fedora chat, in the future that may change.
---
CONTRIBUTING: Recommend filing an issue before big PRs
---
> Contributing chat

- docs/src/filesystem-storage.md
- docs/src/filesystem.md
- docs/src/relationships.md
- Clarify c/storage instance and LBIs in multiple places
- Flesh out/clarify some differences between bootc and rpm-ostree
> docs: Various elaborations

- lib/src/install.rs
- lib/src/install/baseline.rs
- lib/src/mount.rs
Works to improve `bootc install to-disk` flow by checking for mounts on the device to be installed to. If mounts are present then install will abort. 
Resolves #720
> install-to-disk: Check for mounts before install

- ADOPTERS.md
- MAINTAINERS.md
- README.md
These files help clarify/formalize some information. In particular I'd like to look at tools that auto-sync from MAINTAINERS to the github permissions so that we can maintain that in a git-ops fashion.
> Add MAINTAINERS.md and ADOPTERS.md

- lib/src/cli.rs
In some cases we re-exec ourselves; seeing the temporary file in there is super ugly. In general ideally in the future we support reliably querying journal logs from bootc; at least this improves things so that one can do
`journalctl _COMM=bootc`.
> cli: Reset executable name

- docs/src/bootc-install.md
We changed this in the code a while back too.
> docs/install: A separate `/boot` is not required

- .packit.yaml
- tests/e2e/bootc-install.sh
- tests/e2e/shared_lib.sh
Fedora 41 released already, it's time to drop Fedora 40 test and run Fedora 41 test instead
> ci: Update Packit target to Fedora 41 from Fedora 40

- lib/src/install/baseline.rs
When existing partitions are detected, suggest using bootc flag `--wipe` to wipe them, and not just the `wipefs` command.
> install: improve error message when existing partitions are detected

- hack/provision-derived.sh
- tests/booted/test-logically-bound-install.nu
- tests/plugins/bootc-install.py
This contains the latest plugin code from
https://github.com/teemtee/tmt/pull/3161. It includes automatically spinning up a podman-machine when podman is not rootful. It also fixes a bug introduced in the latest tmt version related to starting a web server via a systemd service.
> tmt: Update bootc-install.py plugin

- lib/src/install.rs
- lib/src/lsm.rs
Pairs with https://github.com/ostreedev/ostree-rs-ext/pull/674 to enable consuming containers that don't have `/ostree`.
> install: Just check etc/selinux/config if we don't have ostree

- Cargo.lock
We need the updated tar for
https://github.com/ostreedev/ostree-rs-ext/pull/679
And the updated cap-std-ext fixes an important bug.
> Cargo.lock: Bump tar and cap-std-ext

- lib/src/deploy.rs
- lib/src/utils.rs
deploy: Use bar.println
In some cases I wasn't seeing this output, and I think it's
because we hadn't `drop()`'d the bar. Since it's in scope
it's cleaner to use its `println` method.
---
deploy: Add a spinner
First, this operation was absolutely not asynchronous
and we need to spawn it in a helper thread on general
principle. Doing that is unfortunately VERY hacky
because we need to clone a lot of things and especially
there's an ergonomics hit here since `Deployment` is
incorrectly `!Send`.
But the main motivation is this operation can be slow sometimes,
so let's show progress output so the admin knows we're not blocked.
Closes: https://github.com/containers/bootc/issues/842
---
utils: …
>  deploy: Add a spinner

- lib/src/install.rs
Fix a small typo in a function context
> install: context typo

- utils/src/command.rs
Factor out a helper that runs and captures output *and* checks exit status out of what we have existing in `run_and_parse_json`, so we can use it for things that output not-JSON.
> utils: Add a helper to run command + capture output

- lib/src/blockdev.rs
Bootc install to-disk command fails to recognize correct path of device-mapper
devices. As a result bootc install command on device-mapper fails with
Wiping /dev/mpathe1
Wiping device /dev/mpathe1
wipefs: error: /dev/mpathe1: probing initialization failed: No such file or directory ERROR Installing to disk: Creating rootfs: Failed to wipe /dev/mpathe1: Task Wiping device /dev/mpathe1 failed: ExitStatus(unix_wait_status(256))
Make sure the device name is captured correctly.
Results with the fix:
Wiping /dev/mapper/mpathe1
Wiping device /dev/mapper/mpathe1
Wiping /dev/mapper/mpathe2
Wiping device /dev/mapper/mpathe2
Wiping /dev/mapper/mpathe
Wiping device /dev/mapper/mpathe
Thanks to Dharaneeshwaran for debugging the problem.
> lib/blockdev: Handle devicemapper path

- docs/src/bootc-images.md
We now do use the final tree for computing file contexts.
> docs/bootc-images: Update for recent SELinux changes

- docs/src/bootc-images.md
We have this in other places, but it's best here. At some point I might redirect the other copies here.
> docs: Move kernel/initramfs from install to base image doc

- lib/src/cli.rs
- tests/booted/readonly/11-ostree-ext-cli.nu
Today rpm-ostree exposes the `ostree container` verb. As part of taking over from rpm-ostree we need to do the same.
Followup to merging ostree-rs-ext in this repository.
A next step here is for us to start owning the
/usr/libexec/libostree/ext/ostree-container
symlink but that will be a followup.
> cli: Wrap ostree-ext via `bootc internals`

- xtask/src/xtask.rs
e.g. `TMT_TEST=test-21-logically-bound-switch make test-tmt` will run all the tmt setup code then run test-21-logically-bound-switch. This is useful when developing a test.
> tmt: Add TMT_TEST env variable to specify single test to run

- ostree-ext/src/container/store.rs
- ostree-ext/src/container/update_detachedmeta.rs
- ostree-ext/src/fixture.rs
- ostree-ext/tests/it/main.rs
A sticking point keeping ostree in the picture here for containers was SELinux handling. When we started this effort I'd feared rewriting.
But recently we changed things such that we label derived images using the policy from the final root.
This is a relatively small change in code size and complexity, that allows us to import images that don't have "ostree stuff" in them at all, i.e. there's no `/ostree/repo/objects`.
The advantage here is that this significantly simplifies constructing base images.
The main disadvantage today for people who build images this way is that we end up re-labeling and re-checksumming all objects.
But, the real fix for that in the future will be for us to rework things such that we support `security.selinux` for example as native xattrs in the tar stream.
> store: Support importing images without `/ostree`

- lib/src/bootloader.rs
- lib/src/install/baseline.rs
install: Hoist ESP GUID to a const
Prep for further work.
---
install: Drop an unnecessary mount
This is handled by bootupd.
---
> two minor bootloader cleanups

- lib/src/glyph.rs
- lib/src/lib.rs
- lib/src/status.rs
- Add a circle like rpm-ostree
- Add a whitespace line between entries
- Drop not-present entries
- Rework timestamp+version combo; if there's no version, then show the column as `Timestamp`; if there's a version but no timestamp, just omit the timestamp
- Align columns
Closes: https://github.com/containers/bootc/issues/900
> status: Rework human readable output

- Cargo.toml
- lib/src/install.rs
- lib/src/utils.rs
- tests-integration/src/install.rs
Ironically our support for `--replace-mode=alongside` breaks when we're targeting an already extant ostree host, because when we first blow away the `/boot` directory, this means the ostree stack loses its knowledge that we're in a booted deployment, and will attempt to GC it...
https://github.com/ostreedev/ostree-rs-ext/pull/550/commits/8fa019bfa821303cfb7a7f069ae2320f4c3800fa is a key part of the fix for that.
However, a notable improvement we can do here is to grow this whole thing into a real "factory reset" mode, and this will be a compelling answer to
https://github.com/coreos/fedora-coreos-tracker/issues/399
To implement this though we need to support configuring the stateroot and not just hardcode `default`.
> Add support for `--replace-mode=alongside` for ostree target

- lib/src/install.rs
The extra cloning we were doing here looked odd to me. I think this ends up being cleaner make the toplevel variable mutable and replace it only in the circumstance we detect an ostree deployment.
> install: Some cleanups around root_path

- lib/src/utils.rs
We do validation using `--no-default-features` which triggers these
> Fix unused import errors

- Cargo.lock
- lib/Cargo.toml
- lib/src/cli.rs
- lib/src/image.rs
- tests/booted/test-logically-bound-install.nu
Solves the second part of https://github.com/containers/bootc/issues/846
The (hidden) image list command now has a `--type` flag to allow users to list only logical images, only host images, or all images.
Also the command has been adjusted so that it can run even when not booted off of a bootc system. In that case, it will only list logical images. If a user tries to list host images without a booted system, an error will be thrown.
The command also has a `--format` flag to allow users to choose between a human-readable table format and a JSON format.
> List logically bound images

- lib/src/install.rs
- lib/src/install/baseline.rs
install: Reduce usage of absolute path for rootfs
In the install flow we have both `rootfs` and `rootfs_fd` which
hold the physical root. Using fd-relative accesses where we
can provides a lot of advantages, so switch most uses over
to the file descriptor.
---
install: Rename rootfs -> physical_root
In the install flow we juggle *three* file systems in general:
- The container/host root
- The physical root
- The deployment root
"rootfs" in theory could be any of those three. In the install code
it's the physical (target) root, so rename the variable
to clarify.
---
> install: Two rootfs cleanups

- lib/src/install.rs
As the comment says everything we do before
`prepare_install` is something we might do *twice* so let's keep it as early as possible.
Looking at the history of this code (and its logical inputs) I believe there's no reason for its placement in the middle of this function other than just "stuff appeared
before it organically".
Yes, it means some argument validation will happen after the re-exec but that's fine.
> install: Move re-exec earlier

- tests/booted/test-image-pushpull-upgrade.nu
Updated versions of nu make this a syntax error apparently.
> tests: Fix syntax error from newer nushell

- lib/src/boundimage.rs
- lib/src/cli.rs
- lib/src/install.rs
Partially solves #846
This adds a new `--bound-images` option to `bootc install` which will allow the user to choose how they want to handle the retrieval of LBIs into the target's container storage.
The existing behavior, which will stay the default, is `--bound-images stored` which will resolve the LBIs and verify they exist in the source's container storage before copying them into the target's container storage.
The new behavior is `--bound-images pull` which will skip the resolution step and directly pull the LBIs into the target's container storage.
The older `--skip-bound-images` option (previously hidden) is now removed and replaced with the new (but still hidden) `--bound-images skip` option.
> install: Add support for pulling LBIs during install

- lib/src/install.rs
The `warn_on_host_root` check was broken when we added support for installing on already-ostree systems.
See https://github.com/containers/bootc/issues/907
The solution is to use the original user provided root_path for the fd passed to warn_on_host_root, rather than the modified one, as that will always match /proc/0/root's fsid (in ostree systems systemd is running with the deployment root as its root, and this is what we have mounted as /:/target)
> install: Fix broken warn_on_host_root check

- Makefile
- lib/src/cli.rs
cli: Factor out helper to parse "callname"
No functional changes; prep for further work.
---
cli: Prepare for other argv0 dispatching
Clean up the interception to prepare for other cases.
---
cli: Add interception for ostree extension verbs
This allows us to fully own the symlinks in `/usr/libexec/libostree/ext`.
---
>  cli: Add interception for ostree extension verbs

- Cargo.toml
Add a profile that allows squeezing every single bit out of the output executable.
Embedded applications will inevitably require squeezing every single bit out of bootc. Current release executable stands at 140mb due to including debuginfo. This is stripped by the RPM but consumers/forks that do not do that are left with the symbols.
Runs with  `cargo build --profile=thin`. 
Produces an executable with size 5.8mb, current fedora executable of ver 1.1.2 is 7.1mb.
The idea here would be to use for an embedded web installer, that is used by e.g., double clicking an executable or installing an apk file which adds a light EFI executable/bootloader to the device's boot/EFI partition.
> feat: add thin build profile for embedded applications

- lib/src/install.rs
Prep for the anaconda install completion work.
> install: Factor out helper to create aleph version

- lib/src/boundimage.rs
- lib/src/cli.rs
- lib/src/install.rs
- lib/src/install/completion.rs
- ostree-ext/src/container/deploy.rs
When bootc was created, it started to become a superset of ostree;
in particular things like `/usr/lib/bootc/kargs.d` and logically
bound images.
However...Anaconda today is still invoking `ostree container image deploy`.
Main fix
--------
When bootc takes over the `/usr/libexec/ostree/ext/ostree-container`
entrypoint, make the existing `ostree container image deploy` CLI actually
just call back into bootc to fix things up. No additional work required other
than getting an updated bootc in the Anaconda ISO.
Old Anaconda ISOs
-----------------
But, a further problem here is that Anaconda is only updated once
per OS major+minor - e.g. there won't be an update to it for the lifetime
of RHEL 9.5 or Fedora 41. We want the ability to ship new
features and bugfixes in those OSes (especially …
> install: Add `ensure-completion` verb, wire up ostree-deploy → bootc

- lib/src/boundimage.rs
- lib/src/cli.rs
- lib/src/image.rs
- lib/src/install/completion.rs
- lib/src/kernel.rs
- lib/src/mount.rs
- ostree-ext/src/chunking.rs
- ostree-ext/src/container/encapsulate.rs
- ostree-ext/src/container/mod.rs
- ostree-ext/src/fixture.rs
- ostree-ext/src/ostree_prepareroot.rs
- ostree-ext/tests/it/main.rs
image: Drop unnecessary vec!
No need to allocate here. Drive by cleanup as I was porting
other code to use comfy-table.
---
tree-wide: Run `cargo clippy --fix`
Nothing important here but eh, let's quiet it.
---
lib: One more clippy fix
---
> Minor fixes

- lib/src/cli.rs
- lib/src/generator.rs
- lib/src/status.rs
- ostree-ext/src/container_utils.rs
- ostree-ext/src/integrationtest.rs
Just a code cleanup.
Closes: https://github.com/containers/bootc/issues/934
> Use a shared const and helpers for run/ostree-booted

- Cargo.lock
- lib/src/image.rs
- ostree-ext/Cargo.toml
- ostree-ext/src/cli.rs
I was looking at our vendoring set and while it's not actually relevant I found myself wondering why we had *three* versions of `windows-sys`. Having that many crate versions is often a signal that there's an unmaintained dependency.
And indeed, `terminal_size` is no longer cool. The "in" crowd has moved on to newer, hipper things. Life moves fast, we need to keep up.
(OK but yes also this drops some manual column printing code
we had which is also a win)
> ext: Replace terminal_size with comfy-table

- lib/src/lints.rs
Ref https://github.com/containers/bootc/issues/942
We don't want to support this, lint against it.
> lints: Add check for /usr/etc

- lib/src/cli.rs
- lib/src/install.rs
- lib/src/install/completion.rs
> install: Guide user towards the correct podman flags

- .github/workflows/labeler.yml
- .github/workflows/python.yml
This PR includes:
- No python code in the repo any more, do not need python checking in CI.
- Fix "The configuration file (path: .github/labeler.yml) was not found locally" labeler error.
> ci: remove python checking and fix labeler action error

- Cargo.lock
- lib/src/install.rs
- lib/src/utils.rs
- ostree-ext/Cargo.toml
- ostree-ext/src/container/deploy.rs
- utils/Cargo.toml
- utils/src/command.rs
utils: Add a lifecycle_bind helper for Command
In almost all children we fork, we want the child to reliably
exit if we do (e.g. especially if we panic). The Linux
PR_SET_PDEATHSIG is just great for this.
---
utils: Use `run` helper for editor
I just happened to glance at this code, this gives us stderr
in the error, etc.
---
> Cmd pdeathsig

- docs/src/filesystem-storage.md
- docs/src/filesystem.md
filesystem: Doc usr/etc
Came up in review.
---
filesystem: Doc etc.transient
I noticed this was missing.
---
doc: Expand on prepare-root
Per review.
---
> Filesystem doc

- tests-integration/src/install.rs
We think this is unnecessary now; part of improving
the ergonomics of `bootc install` in general, but
especially with the `to-existing-root` path.
Once this lands, at some point later then we
can also remove it from all of the documentation.
But the most safe thing is to leave it in the
docs for a bit longer.
Closes: https://github.com/containers/bootc/issues/928
>  install: Drop code/test uses of `--security-opt`

- lib/src/mount.rs
Motivated by https://github.com/containers/bootc/issues/957 but probably not any kind of fix in reality. Our error handling here was buggy. What we really should do is avoid `fork()` and do an execve here, but that's a larger refactor.
- Close the other side of the socket in the forked child so the parent doesn't hang indefinitely if the child dies before sending
- Change the parent to return a clean error if the child doesn't write anything instead of an `assert!`
- Check the exit code of the child
> mount: Some error handling fixups

- .copr/Makefile
The copr build environment looks upgrade to Fedora 41 now, dnf5 has been used since that. That caused `dnf builddep` command error.
```
dnf -y builddep ./contrib/packaging/bootc.spec
Unknown argument "builddep" for command "dnf5". Add "--help" for more information about the arguments.
It could be a command provided by a plugin, try: dnf5 install 'dnf5-command(builddep)'
make: *** [/mnt/workdir-c4js6f0t/bootc/.copr/Makefile:5: srpm] Error 2
```
dnf5 needs `dnf5-command(builddep)` installed to run "dnf builddep"
The copr build failure log: https://log-detective.com/contribute/copr/8384952/srpm-builds#
> copr: fix Unknown argument "builddep" for command "dnf5"

- lib/src/cli.rs
- lib/src/deploy.rs
- lib/src/install.rs
- lib/src/lib.rs
- lib/src/progress_jsonl.rs
- ostree-ext/src/cli.rs
- ostree-ext/src/container/store.rs
Adds a total progress bar to the progress output of switch and upgrade that also shows time remaining.
Then, uses the total progress bar to allow sending a jsonl output to stderr that can be read by userspace software. Has to be stderr, as bootc has some spurious prints on stdout. Progressbar is hidden as it writes to stderr.
Progress bar styling needs some cleanup. Jsonl output needs a type arg to identify the type of output, so that there can be other jsonl jsons for e.g., deployment.
> feat(upgrade): Add total progress bar and JSON output

- docs/src/bootc-install.md
We need to change Anaconda and bootc-image-builder to stop generating `/etc/fstab` for this reason.
> docs/bootc-install: Give more guidance on `root=` and `rootflags=`

- docs/src/bootc-images.md
This needs to be called out way more strongly than it is now. For example a lot of our assumptions about being able to put content anywhere (i.e. outside of `/usr` which happens especially with containers) which rely on it.
> docs/images: Document composefs here too

- lib/src/lib.rs
This was bothering me as I was doing something else
Organize these in some sane manner:
- Non-feature-gated modules, sorted
- Then feature-gated modules, grouped and sorted by feature name
> lib: tidy up module declarations

- lib/src/install.rs
- lib/src/install/completion.rs
- lib/src/store/mod.rs
- lib/src/utils.rs
> utils: Add sysroot_dir helper

- lib/src/cli.rs
- lib/src/progress_jsonl.rs
Add a shared structure (so we only document the option once) and add a `TryFrom` chain which cleans up the conversion from the options into a `ProgressWriter`.
> cli: Centralize progress parsing a bit

- .github/labeler.yml
It appears the single glob '*' doesn't match recursively, so use the
globstar '**' where we want to match anything within a subtree
> ci: labeler: use globstar where applicable

- lib/src/lints.rs
- lib/src/utils.rs
As mentioned in #975, we should add a lint to ensure that all filenames are UTF-8, giving nice errors (with full pathnames) in the event that we encounter invalid filenames.
We also check symlink targets.
Add a unit test that tries various valid and invalid scenarios.
> lints: add check for non-utf-8 filesystem content

- Makefile
- docs/src/SUMMARY.md
- docs/src/man-md/bootc-status-updated.path.md
- docs/src/man-md/bootc-status-updated.target.md
- lib/Cargo.toml
- lib/src/cli.rs
- lib/src/deploy.rs
- lib/src/imgstorage.rs
- lib/src/lib.rs
- lib/src/rhsm.rs
- lib/src/store/mod.rs
- systemd/bootc-publish-rhsm-facts.service
- systemd/bootc-status-updated.path
- systemd/bootc-status-updated.target
> Add subscription-manager fact generation

- lib/src/rhsm.rs
- tests/booted/test-image-pushpull-upgrade.nu
Followups to https://github.com/containers/bootc/pull/977
> two minor rhsm followups

- lib/src/blockdev.rs
- lib/src/cli.rs
- lib/src/generator.rs
- lib/src/glyph.rs
- lib/src/install/config.rs
- lib/src/kernel.rs
- lib/src/lints.rs
- lib/src/utils.rs
This is a general best practice; specifically motivated by handling test-specific imports.
> tree-wide: Move most tests under `mod test`

- lib/Cargo.toml
- lib/src/blockdev.rs
- lib/src/bootloader.rs
- lib/src/boundimage.rs
- lib/src/cli.rs
- lib/src/install.rs
- lib/src/install/baseline.rs
- lib/src/install/config.rs
- lib/src/kargs.rs
- lib/src/lib.rs
- lib/src/lsm.rs
- lib/src/mount.rs
- lib/src/podman.rs
- lib/src/status.rs
- lib/src/utils.rs
I consider `bootc install to-filesystem` support a key feature of bootc. In theory today one can still set up a system directly with `ostree` and we will continue to support that.
But things like logically bound images we do want to be initialized from the start and that's with `bootc install to-filesystem`.
Maintaining the feature just has a logistical annoyance any time one touches the install code as we often end up needing to carefully `#[cfg(feature = "install")]` in many places in an infectious way.
Also as we head towards enabling factory reset
https://github.com/containers/bootc/issues/404
we really do want some of the install code enabled there.
However, `to-disk` is much more of a "demo". I don't want bootc to grow too much knowledge around block devices. Complex setups (LVM, …
> `install` feature is always on, add `install-to-disk`

- Makefile
- baseimage/README.md
- baseimage/base/ostree
- baseimage/base/sysroot/.gitignore
- baseimage/base/usr/lib/ostree/prepare-root.conf
- contrib/packaging/bootc.spec
- lib/src/lints.rs
This directory will contain expected files in the base image.
That said, I may change the container import path to auto-create
at least the sysroot dir and symlink at some point and these
can just be dropped.
And for that matter after
https://github.com/ostreedev/ostree/commit/9a0acd7249bb0c7f55c2bf56e5073902cd60038b
"libostree/deploy: enable composefs by default"
we can likely just drop the prepare-root bit too.
But for now this is needed.
Motivated by improving base image generation from
https://gitlab.com/fedora/bootc/tracker/-/issues/32
> install: Add /usr/share/doc/bootc/baseimage

- Makefile
- baseimage/README.md
- baseimage/dracut/usr/lib/dracut.conf.d/10-bootc-base.conf
ref https://gitlab.com/fedora/bootc/tracker/-/issues/32#note_2270189835
This will keep track of the generic bootc+dracut integration glue here instead of replicating it in different base images.
(Perhaps bootc actually injects code into the initramfs in the
future instead of ostree, for example)
> install: Add `dracut` subdirectory to baseimage reference

- docs/src/bootc-images.md
- Link to our `baseimage` content
- Update to note we don't require `ostree/` anymore
- Consistently use `##` for subsections (though more cleanup could be done)
> docs/bootc-images: Refresh a bit

- Cargo.toml
- ci/installdeps.sh
- ostree-ext/tests/it/main.rs
Fallout from the ostree-ext merge. We were missing a `BuildRequires`
in the spec, which caused our unit tests to fail in Fedora.
I since added that BuildRequires, but let's change our tests
to skip if it's not present.
> tests: Handle not having skopeo present

- lib/src/install.rs
- lib/src/lints.rs
- lib/src/utils.rs
utils: Move open_dir_noxdev here
Prep for using it elsewhere.
---
install: Never traverse mount points with `--wipe`
If we encounter a mount point when attempting to
wipe a filesystem, then something has definitely gone
wrong. At the install phase we should only be operating
on a single physical filesystem.
Motivated by https://github.com/containers/bootc/issues/997
---
>  install: Never traverse mount points with `--wipe`

- Makefile
- systemd/bootc-status-updated.path
- tests/booted/readonly/012-unit-status.nu
build-sys: Enable `bootc-status-updated.path` by default
Followup to https://github.com/containers/bootc/pull/977
In chatting with John we had some agreement to statically
enable the `.path` unit by default upstream here since
it's a feature we want to be available by default
so that tooling can react dynamically to changes.
---
bootc-status-updated: Add `ConditionPathExists=/run/ostree-booted`
This is a general best practice for our units to ensure
they don't apply outside of bootc systems.
---
> Two changes for `bootc-status-updated.path`

- lib/src/cli.rs
- lib/src/rhsm.rs
The bootc facts file added in https://github.com/containers/bootc/pull/977 uses the wrong file extension to work with subscription-manager.
I've tested this on a bootc system registered to Foreman via subscription-manager:
```
[root@bootc-machine bootc]# subscription-manager facts | grep bootc
bootc.available.digest: Unknown
bootc.available.image: Unknown
bootc.available.version: Unknown
bootc.booted.digest: sha256:48884b0220bb075ce50ae31d8e6739f3e9b3870e746a4b3c87ea2fe3353b7208
bootc.booted.image: quay.io/centos-bootc/centos-bootc:stream10
bootc.booted.version: stream10.20241230.0
bootc.rollback.digest: sha256:e168d2f013ed4cc89771d2c5d1b15951ae09792ed3d647226f48e5b62316d7fb
bootc.rollback.image: quay.io/centos-bootc/centos-bootc:stream10
bootc.rollback.version: stream10.20241216.0 …
```
> Rename RHSM file to bootc.facts

- docs/src/bootc-images.md
The baseimage content is above the docs, which causes a rendering error. Use the full absolute URL for now.
> docs: Use absolute link for toplevel content

- tests/booted/test-image-pushpull-upgrade.nu
We could add a new test case for this, but it's expensive to do these image push/pull ones so let's just pile onto this one.
> tests: Add some sanity checking of --json-fd

- docs/src/SUMMARY.md
- docs/src/bootc-via-api.md
- docs/src/experimental-progress-fd.md
- docs/src/progress-v0.schema.json
- docs/src/progress-v1.schema.json
- lib/src/cli.rs
- lib/src/deploy.rs
- lib/src/progress_jsonl.rs
- tests/booted/test-image-pushpull-upgrade.nu
- xtask/src/xtask.rs
deploy: Avoid cloning progress
Have the printer take ownership and return it. This is generally
prep for making the writer more stateful which will make it easier
to work with.
---
cli: Rename --json-fd to --progress-fd
The format is not as important as what the option *does*. There's
multiple things that can be JSON, but this is specifically
about dynamic progress information.
---
cli: Make --progress-fd hide=true for now
We're still debating some of the interface/semantics here
so let's mark this as hidden.
---
docs: Describe `--progress-fd`, add rendered JSON schema
Signed-off-by: Antheas Kapenekakis <git@antheas.dev>
Signed-off-by: Colin …
> Various updates for `--progress-fd`

- Makefile
- baseimage/README.md
- baseimage/systemd/usr/lib/kernel/install.conf
This is part of the kernel-integration work:
- https://github.com/coreos/rpm-ostree/pull/5135
- https://gitlab.com/fedora/bootc/base-images/-/merge_requests/62
- https://github.com/coreos/rpm-ostree/pull/5209
WIP while we release rpm-ostree.
> baseimage: Add kernel-install integration

- lib/src/cli.rs
- lib/src/install.rs
- lib/src/utils.rs
- ostree-ext/src/cli.rs
- ostree-ext/src/container/store.rs
- ostree-ext/src/tar/import.rs
Right now when using OSTree remote verification, there's no indication
that the OSTree commit was successfully verified.
Capture the return string from `OstreeRepo.signature_verify_commit_data`
and return it as part of the public `LayeredImageState` object.
We could return a more structured signature object here, but this is
sufficient for our purposes for now and saves clients from having to
regenerate similar looking text.
In the `ostree container` CLI, print this verification text.
> ostree-ext: surface libostree signature verification text

- ostree-ext/src/tar/export.rs
A lot of technical debt here. A long time ago I added this hacky bit to inject var/tmp is the container stream even if it wasn't in the ostree commit.
Today things shipped by `rpm-ostree compose image` like FCOS don't have `var/tmp` in the commit.
But then more recently we started shipping `/var/tmp` in base images directly.
Now I'm working on https://github.com/coreos/rpm-ostree/issues/5221 where we're rechunking from a rootfs that does have var/tmp and that ends up in the ostree commit.
The path comparison here was wrong because the tar stream we generate has the paths start with `./` and a literal comparison doesn't match `./var/tmp` != `var/tmp`.
Add a canonicalization helper and use it for this.
> ostree-ext/tar/export: Fix reexport of var/tmp

- .github/workflows/ci.yml
- deny.toml
We should really have a more centrally-maintained `cargo-deny` configuration. I'd argue to maintain it here in bootc to start, but this will be a common thing for other projects in github.com/containers and elsewhere.
Anyways, this needed updating for the new Unicode-3.0 license in some updated unicode crates that I saw in rpm-ostree.
While we're here, quiet the duplicate crate warning in the CI job, as it's just noise. Keep it when running locally so we have some visibility if we care about it.
> deny: Sync with rpm-ostree

- contrib/packaging/bootc.spec
The Go macros for Fedora, RHEL 10, and ELN (the future RHEL 11) are all in sync; only RHEL 9 and earlier need the old syntax.
Downstream PR: https://src.fedoraproject.org/rpms/bootc/pull-request/7
> spec: fix build with rhsm

- Cargo.lock
- lib/Cargo.toml
- lib/src/lints.rs
Internal only change, but prep for future work; I want to track the version lints were introduced in, support clearly differentiating between warnings and fatal errors, etc.
Specifically motivated by custom base image work
https://github.com/coreos/rpm-ostree/issues/5221
but also obviously useful in general.
> lints: Various improvements

- Makefile
- systemd/bootc-status-updated.target
Any services that react to status changes should be idempotent, and
should run on boot.  It is likely (but not guaranteed) that during
boot we are in the process of switching from a previous deployment to
a new one, and thus what was previously "staged" is now "booted" and
what was previously "booted" is now "rollback", so anything that cares
about status is going to want to handle that.
> systemd: enable bootc-status-updated.target on startup

- lib/src/blockdev.rs
- lib/src/install/baseline.rs
- utils/src/command.rs
The install code and the blockdev code call each other. Clean up blockdev to only use `bootc-utils`.
Prep for splitting out the blockdev stuff into at least a separate internal crate; ref
https://github.com/coreos/bootupd/pull/820
> install/blockdev: Break cyclic build dependency

- hack/Containerfile
- hack/build.sh
- tests/containerfiles/lbi/Containerfile
One CI run just got a server error fetching the spec from Fedora. We have a spec here (which I don't like but we do) so use it to lower CI flakes.
> build.sh: Use our embedded spec

- ostree-ext/src/container/encapsulate.rs
I was getting EPERM on creating the dir, and it was a pain to track down.
> ostree-ext/encapsulate: Add some error contexts

- Makefile
- systemd/bootc-publish-rhsm-facts.service
- systemd/bootc-status-updated-onboot.target
The bootc-status-updated.target unit cannot directly be
WantedBy=multi-user.target, because we rely on StopWhenUnneeded=true
so the target will be activated each time bootc-status-updated.path
triggers it.  Because multi-user.target remains active, this would
hold bootc-status-updated.target in an active state as well, and the
path unit activating would not have the desired effect of retriggering
the target unit.
The new bootc-status-updated-onboot.target is intended to serve the
same purpose as bootc-status-updated.target but will activate (and
remain active) on boot.  Any interested units should be WantedBy both
targets.  This updates bootc-publish-rhsm-facts.service to do just
that.
> Add bootc-status-updated-onboot.target 

- Cargo.lock
- Cargo.toml
- blockdev/Cargo.toml
- blockdev/src/blockdev.rs
- lib/Cargo.toml
- lib/src/bootloader.rs
- lib/src/install.rs
- lib/src/install/baseline.rs
- lib/src/lib.rs
This code has been forked between bootupd and coreos-installer and here. This is prep for having bootupd pull it from bootc's git so we can deduplicate.
> Split off a blockdev internal crate

- lib/src/cli.rs
- lib/src/lints.rs
This will help catch e.g. `/var/log/dnf.log` and such; no one really wants to leak those into containers by default.
Add a `Warning` level lint - this one shouldn't be fatal by default. But also add the ability to opt in to making warnings fatal.
> lints: Add warning level, add a check for /var/log

- Cargo.lock
- Cargo.toml
- blockdev/Cargo.toml
- lib/Cargo.toml
build-sys: Split workspace members to multiple lines
To lessen the chance of future conflicts when changing things here.
---
Rename internal blockdev crate to bootc-blockdev
To make a bit clearer this is an internal-to-bootc thing; but also
because other projects like bootupd may start referencing it.
---
> build-sys: Two minor patches

- Makefile
- cli/bootc-generator-stub
rpm can't handle hardlinked binaries with distinct labels today gracefully; ostree (and bootc) always break the hardlink which I think is generally right.
Anyways, switch to a dispatcher shell script to fix this.
To fix https://issues.redhat.com/browse/RHEL-76188
> Switch systemd generator to be a dispatcher shell script

- lib/src/cli.rs
- lib/src/lints.rs
We unit test each lint, but not the main function. As it grows in complexity it'll be useful to unit test.
- Change the function to write to a provided output, not always stdout/stderr
- Add a `passing_fixture` helper that passes all lints
- Fix the baseimage test not to use `??` because that turns the *inner* error into an outer error which is not what we want.
> lints: Also test main execution

- lib/Cargo.toml
- ostree-ext/Cargo.toml
- ostree-ext/src/container/deploy.rs
This is aiming to fix https://github.com/coreos/rpm-ostree/issues/5251 Basically we can't re-invoke the calling process if we aren't actually bootc.
(There are solutions that make this work, but what we'll hopefully
do shortly is propagate the logic to older streams to have
bootc take over the handling anyways)
> ostree-ext: Add bootc feature

- .packit.yaml
Trigger the build in Fedora Koji build system as a reaction to a new dist-git commit. Create a new update in Fedora Bodhi for successful Koji build.
I can't send PR in https://src.fedoraproject.org/rpms/bootc. According to https://fedoraproject.org/wiki/Infrastructure/fedorapeople.org#Accessing_your_fedorapeople.org_space, my fedora account should be in one group. Anyone can help to add my fedora account (@xiaofwan) into group? Thanks.
> ci: Land a new upstream release in Fedora with Packit

- .packit.yaml
- Cargo.lock
- cli/Cargo.toml
- contrib/packaging/bootc.spec
- deny.toml
- hack/build.sh
- lib/Cargo.toml
- lib/src/cli.rs
- lib/src/install.rs
- lib/src/lints.rs
- ostree-ext/Cargo.toml
- ostree-ext/src/ostree_prepareroot.rs
- xtask/Cargo.toml
- xtask/src/xtask.rs
Prep for https://github.com/containers/bootc/pull/935
> Install config verity prep

- ostree-ext/src/cli.rs
- ostree-ext/src/container/store.rs
This is effectively an internals command for us to aid debugging.
At some point it may make sense to expose this
at the bootc level too.
> ostree-ext: Add `image clear-cached-update`

- .github/workflows/ci.yml
- Cargo.lock
- hack/Containerfile
- ostree-ext/Cargo.toml
- ostree-ext/src/container/encapsulate.rs
- ostree-ext/src/container/store.rs
- ostree-ext/src/fixture.rs
- ostree-ext/src/ima.rs
- ostree-ext/src/ostree_prepareroot.rs
- ostree-ext/src/tar/import.rs
- tests/containerfiles/lbi/Containerfile
Notably this drops out several duplicate crates.
Depends on https://github.com/ostreedev/ostree/pull/3378 and (and publishing the update to crates.io)
> Update to ostree-rs 0.20

- ostree-ext/src/container/store.rs
Not totally sure how this got through CI, but the most recent two PRs semantically conflicted. Update the new code to use the new glib prelude import.
> store: Fix semantic merge conflict

- docs/src/filesystem.md
- Mention `ostree admin config-diff`
- Note that metadata also counts as a modification
> docs/filesystem: Flesh out `etc` a bit more

- lib/src/cli.rs
We now support deploying containers without `sysroot/ostree`, so drop the requirement for the linter to find that.
> lint: Drop ostree-container restriction

- Cargo.lock
- Cargo.toml
- Makefile
- cli/Cargo.toml
- cli/src/main.rs
- contrib/packaging/bootc.spec
- system-reinstall-bootc/Cargo.toml
- system-reinstall-bootc/sample_config.yaml
- system-reinstall-bootc/src/config/cli.rs
- system-reinstall-bootc/src/config/mod.rs
- system-reinstall-bootc/src/main.rs
- system-reinstall-bootc/src/podman.rs
- system-reinstall-bootc/src/prompt.rs
- system-reinstall-bootc/src/users.rs
- utils/Cargo.toml
- utils/src/command.rs
- utils/src/lib.rs
- utils/src/tracing_util.rs
> cli: add `system-reinstall-bootc` binary

- Cargo.lock
- lib/Cargo.toml
- lib/src/cli.rs
- lib/src/lints.rs
lints: Use enum instead of bool
This is always clearer. Prep for adding another argument to this function
that's an effective bool.
---
lints: Rework to use linkme
Two goals:
- The global static LINTS array is a conflict point
- It's easier to lay out the lint info when it's next to each
function; prep for extending the lint data more.
---
lints: Check for invalid /etc/hostname and /etc/resolv.conf
Detect problems from https://github.com/containers/buildah/issues/4242
or similar.
As part of this, add new infrastructure logic for lints that only operate on
non-running roots (we expect these are mounted/written at runtime).
---
> lints: More cleanup && lints: Check for invalid /etc/hostname and /etc/resolv.conf

- ostree-ext/src/container/store.rs
- tests/booted/readonly/011-hostname.nu
We can pretty safely work around this here; zero sized files for both are useless.
Closes: https://github.com/containers/bootc/issues/1064
> store: Clean up broken /etc/hostname and /etc/resolv.conf

- system-reinstall-bootc/src/users.rs
- system-reinstall-bootc/tests/fixtures/loginctl.json
> reinstall: avoid duplicate users in `loginctl_users`

- lib/src/cli.rs
- lib/src/lints.rs
lints; Add unit test checking pass/fail counts
We have a bug here that this will catch.
---
lints: Actually skip skipped lints
Oops.
---
lint: Add --skip
This allows people to explicitly skip individual lints; especially
useful for warnings. But maybe people have a legitimate reason
to skip ones we're calling fatal too.
Prep especially for supporting `--fix --skip`.
---
> lints: More tests && add --skip

- Cargo.lock
- contrib/packaging/bootc.spec
- system-reinstall-bootc/Cargo.toml
- system-reinstall-bootc/src/main.rs
- system-reinstall-bootc/src/podman.rs
- utils/src/command.rs
- utils/src/tracing_util.rs
See commit messages
Fixes #1104
> reinstall: Ensure podman is installed

- tests/booted/test-image-pushpull-upgrade.nu
- tests/booted/test-logically-bound-switch.nu
See https://github.com/containers/bootc/pull/1101#issuecomment-2653862974 Basically things break unless "podman" initializes the c/storage instance right now.
> tests/pushpull: Work around podman/skopeo interaction bug

- Cargo.lock
- hack/provision-derived.sh
- lib/src/install.rs
- lib/src/lints.rs
- lib/src/utils.rs
- utils/Cargo.toml
- utils/src/lib.rs
utils: Fix compliation standalone
We use `tokio::test` so need the macros feature.
---
utils: Add a method to split an iterator
---
provision-derived: Clean lots more stuff
Yeah, we're going to need a `dnf clean all --everything`...
---
Update cap-std-ext, use new open_dir_noxdev API
I moved the code there; I plan to use open_dir_noxdev in
the tmpfiles code too which can't depend on lib/util.
---
> A few misc prep patches

- lib/src/image.rs
- lib/src/imgstorage.rs
- tests/booted/test-image-pushpull-upgrade.nu
- tests/booted/test-logically-bound-switch.nu
Two of our tests (and an unknown set of users may) run
`bootc image copy-to-storage` which happens to invoke
skopeo to target /var/lib/containers/storage. If this
happens to be the *first* thing to write to that
c/storage instance it triggers a bug around the podman
image network setup.
> storage: Ensure global c/storage is initialized via podman

- system-reinstall-bootc/src/podman.rs
If the Containerfile has a USER directive, podman-run will execute the bootc command as that user, making the installation to fail. So, let's force the root as user/group to overwrite any possible USER directive.
> Set the UID/GID of podman-run to root

- system-reinstall-bootc/src/podman.rs
This warning message is shown when Podman is not found on the system. It
is not clear that the script will attempt to install Podman
automatically if it is not found. This commit changes the message to
make it clear that Podman will be installed automatically.
> reinstall: Clarify that Podman is being installed automatically

- .github/labeler.yml
Automatically mark any PR touching files in the system-reinstall-bootc
directory with the area/system-reinstall-bootc label.
> labeler: auto add system-reinstall-bootc label

- system-reinstall-bootc/src/prompt.rs
I've reworded the multi-user message in the past but the single-user message still had the older wording. This commit updates the single-user message to match the multi-user message.
> reinstall: Reword single-user message

- system-reinstall-bootc/src/main.rs
- system-reinstall-bootc/src/prompt.rs
The prompt will now only be shown if there were truly no users found,
and not when the user simply explicitly opted out of including them.
> reinstall: Move the no users prompt

- contrib/packaging/bootc.spec
Previously this was just running a "normal" `cargo build` a second
time, and overwriting the rhsm feature flags in the main bootc binary
Resolves: BIFROST-658
> specfile: fix system-reinstall-bootc cargo build invocation

- lib/src/lints.rs
- ostree-ext/src/ostree_prepareroot.rs
We do want to support using bootc without composefs for now.
Closes: https://github.com/containers/bootc/issues/1135
> lint: Split composefs into separate warning lint

- lib/src/kargs.rs
std::env::set_var is unsafe in 2024 edition, and upon looking into
that this use in the kargs test came up.  We don't need to set the
environment variable here, in fact I don't think this ever worked in
the first place.
> kargs: do not set ARCH envvar in tests

- system-reinstall-bootc/src/podman.rs
Add the "legacy" parameters to the podman run invocation because there are existing bootc images that need these parameters when running install to-existing-root.
---
I tested this with the fedora:40 image which has bootc v1.1.2.
> reinstall: Support legacy images in system-reinstall-bootc

- ostree-ext/src/container/store.rs
> ostree-ext: store: clear diff_ids when exporting to oci

- utils/src/tracing_util.rs
This used to work and I'm not exactly sure what changed. For some reason `with_env_filter` needs to be at the end of the chain for the RUST_LOG env var parsing to work.
> tracing: Fix RUST_LOG parsing

- docs/src/filesystem-storage.md
The info in this one was outdated and wrong (we now support labeling dynamically).
> storage: Drop duplicate SELinux section

- lib/src/lints.rs
We have two patterns to initialize a lint:
- Bare struct init
- A helper function
This changes to just one path: A helper function, plus setters for the optional fields.
Prep for adding a new lint option, which would otherwise require changes to everything using the bare struct init.
> lints: Add a set_root_type helper

- Cargo.lock
- system-reinstall-bootc/Cargo.toml
- system-reinstall-bootc/src/main.rs
- system-reinstall-bootc/src/podman.rs
- system-reinstall-bootc/src/prompt.rs
- system-reinstall-bootc/src/users.rs
Pushing this branch early for visibility. The first commit just parses the `sshd -T` output into a struct.
> Smarter ssh authorized key search for system-reinstall-bootc

- Cargo.lock
- system-reinstall-bootc/Cargo.toml
- system-reinstall-bootc/src/prompt.rs
- system-reinstall-bootc/src/users.rs
Just a couple of cleanup commits from review comments.
> Reinstall ssh followup cleanup

- Makefile
- docs/src/bootc-install.md
- lib/src/cli.rs
- lib/src/install.rs
- tests-integration/src/install.rs
Basically I want to get Anaconda to run this, then we can perform arbitrary fixups on whatever it did between the install and reboot without changing Anaconda's code.
Motivated specifically by https://github.com/containers/bootc/issues/971
This also applies to user `%post` scripts for example; maybe those break the bootloader entries in /boot; we have the opportunity to catch such things here.
Or we may choose to start forcibly relabeling the target `/etc`.
> install: Add a generic `install finalize`

- Makefile
This took me some thinking and experimenting. Basically we want:
- Hard deny some warnings (this is covered by the Cargo.toml workspace.lints.rust)
- Gate merging to main in CI on an exact set of warnings we want to forbid, but *without* also using a blanket -Dwarning deny policy because that could break our build when the compiler revs.
- A corollary to the previous: allow developing locally without killing the build just because you have an unused import or some dead code (for example). So we don't want to add `dead_code = deny` into the Cargo.toml.
- Be able to easily reproduce locally what CI is gating on in an efficient way.
We already had `make validate-rust` which was intending to navigate this, but what was missing was the "deny extended set of warnings" so we got code committed …
> build: Tweak `make validate-rust`

- system-reinstall-bootc/src/main.rs
- system-reinstall-bootc/src/podman.rs
This splits the `podman pull <image>` and the `podman ... bootc install to-existing` command to prepare for future features (e.g. cloud-init) that will require inspecting the image before constructing the bootc install command.
---
Also adds a prompt before installing podman since it needs to be installed before pulling the image which now happens immediately after running the command, before any other user prompts. Open to other ideas on the UX if this doesn't make sense.
> reinstall: Pull podman image early

- ostree-ext/src/container/store.rs
- tests/booted/readonly/011-test-resolvconf.nu
The previous change here was a no-op for two reasons:
- It's actually usr/etc at this point
- We were operating on the wrong rootfs
Fixes: https://github.com/containers/bootc/pull/1096/commits/57bd0dc9835669274696998386a547afb6709ff5
> store: Really remove empty /etc/resolv.conf and /etc/hostname

- ostree-ext/src/ostree_prepareroot.rs
We have duplicate code to parse this between C and Rust unfortunately; update the Rust side to honor what landed in https://github.com/ostreedev/ostree/pull/3354
> ostree-ext: Update parser to honor `composefs=verity`

- lib/src/fixtures/spec-staged-booted.yaml
- lib/src/status.rs
This is just irrelevant noise; nanoseconds never matter for container builds. Motivated by just making this look visually nicer.
In the future I'd like to look at rendering this how e.g. systemd does it also including a "; 1 day ago" humantime suffix.
> status: Drop nanoseconds from time

- docs/src/SUMMARY.md
- docs/src/experimental-fsck.md
- lib/src/cli.rs
- lib/src/fsck.rs
- lib/src/lib.rs
- tests/booted/readonly/015-test-fsck.nu
Split this out of the fsverity PR.
We obviously want a `fsck` command. This starts by doing just two checks:
- A verification of `etc/resolv.conf`; this tests https://github.com/containers/bootc/pull/1167/commits/98995f662b7207858630f72236c9b850e6f07154
- Just run `ostree fsck`
But obvious things we should be adding here are:
- Verifying kargs
- Verifying LBIs
etc.
> internals: Add new (experimental) `bootc internals fsck`

- lib/src/install.rs
On ostree systems, the boot directory already has our desired format, we should only remove the bootupd-state.json file to avoid bootupctl complaining about it already existing.
The motivation is that this will preserve the boot entry for the original deployment, allowing the user to boot into it if they want to.
This also makes sure `ostree admin status` continues working - since if we're in a booted ostree system but `ostree` can't find its physically (through boot entries) it complains.
> install: Do not clean boot directories on ostree systems

- docs/src/filesystem.md
We wrote the code and it is useful. We are probably just going to need to support it into the forseeable future. However, my core problem with it is what I wrote in the docs here: it has no equivalent in the docker/podman ecosystem, which I think cuts against a core principle that we're trying to make the booted host align with containers.
Of course, stateoverlay isn't a lot of code, and in theory it's a bit independent of ostree, so perhaps we could try to split it out at some point and then it could be used by e.g. `podman run --mount=type=stateoverlay` or so.
Before anyone starts just blindly enabling stateoverlays I'd like them to have considered alternatives such as the symlink approach.
> docs/filesystem: Weaken stateoverlay wording and direct to alternatives

- .copr/Makefile
- .packit.yaml
After movement, the Copr build does not work. Taking this failure fix, we can use Packit to build Copr build. So we do not need to update `.copr/Makefile` when build code changed. And we can remove `.copr` folder.
[Packit can build Copr build in custom Copr project](https://packit.dev/docs/configuration/upstream/copr_build#using-a-custom-copr-project)
> ci: Build Copr build with Packit

- lib/src/lints.rs
Saw in the wild that someone accidentally did an
`rm -rf /var`, and that only fails pretty late in the process.
Add a lint that hard requires the "API filesystem" directory mount points, plus `/var` - that one is a requirement for ostree right now.
> lint: Add an api-base-directories lint

- docs/src/man/bootc-rollback.md
- lib/src/cli.rs
Adds an --apply flag to the `bootc rollback` command to implement automated restarts.
Have confirmed this works by building the bootc binary and running `bootc rollback --apply` on my host.  This restarted the machine into the new (rollback) image.
Closes #1029
---
Hope you don't mind I took the easiest issue I could find :) 
This was mainly to familiarise myself with the debugging flow, and to get an environment setup.
The implementation was referencing the existing --apply flag for the switch command.  The error handling _should_ be okay, since if I understand correctly, the `?` prepended to the `crate::deploy::rollback(sysroot).await` will cause the function to work the same as it did previously - returning the error to the calling function inside a Result.
How do the docs changes …
> feat(rollback): add `--apply` flag

- lib/src/boundimage.rs
- lib/src/imgstorage.rs
- lib/src/install.rs
- lib/src/install/completion.rs
- lib/src/lsm.rs
- lib/src/store/mod.rs
- tests/booted/test-logically-bound-install.nu
Running some containers (e.g. mssql) requires the imgstorage labels to
be identical to the /var/lib/containers/storage. The ideal long term
solution to this is to ship a policy with bootc to be included in each
bootc image that handles the mapping. As a near term solution, this
commit creates each subdirectory of /sysroot/ostree/bootc/storage, sets
the label of each directory directly, then runs `podman --root ...
images` to populate the storage directory with all the correct labels
set. The reason for directly setting the labels rather than inferring
them from /var/lib/containers in an existing policy, is to avoid
requiring a policy when initializing the storage directory in other
places than the install to filesystem path (e.g. anaconda).
---
this ballooned into more changes than I …
> imgstorage: Set selinux labels for imgstorage

- lib/src/spec.rs
- lib/src/status.rs
The existing code didn't take into account the --booted option, so always showed the staged, current and rollback deployments.  This correctly wires through the --booted option to only show that deployment.
Stubs have been left in the code should we wish to enable options to show only the rollback or staged options (--rollback / --staged).
I tried to make the implementation not specific to --booted, so added the Slot enum as an input.  This meant making that enum public.  Please let me know if you would prefer a different approach.
No docs changes were required since the flag is already present.
Please find below the different outputs:
<details>
```
bootc-status-booted-only on  bootc-status-booted-only via 🦀 took 2s 
❯ sudo ./target/debug/bootc status --booted
[sudo] password for admin: …
```
> fix(status): enable --booted option to only show the current deployment

- GOVERNANCE.md
- SECURITY.md
This is what Podman uses, with a couple of removed rules and replacing Podman for Bootc.
However, the more I read it, it seems like too much process vs the contributor size we have currently.
I am trying to find another project example that is a little bit in line with our current process.
I do like this: https://github.com/flatcar/Flatcar/blob/main/governance.md a bit more. Is basically maintainers group and that's it. I think we should expand that a bit into maintainers and core maintainers. Where core maintainers deal with tie breakers and final decision ends up if we can't get lazy consensus or consensus.
I will try to use these two as prior art if the above goal looks good to you all.
> GOVERNANCE: Add Governance doc for CNCF onboarding

- lib/src/cli.rs
This is just adding the docs added on https://gitlab.com/fedora/bootc/docs/-/merge_requests/90 to the man page.
> man/bootc-rollback: add information about /etc

- lib/src/cli.rs
- lib/src/imgstorage.rs
- lib/src/lsm.rs
- tests/booted/readonly/020-test-relabel.nu
- tests/booted/test-logically-bound-install.nu
lsm: Add some more comments
No functional changes.
---
lsm, imgstorage: Rework relabeling
The previous work here wasn't quite right in a few ways.
Our LSM/SELinux code is a bit complex and under-tested.
Here we:
First, refactor some of the labeling bits so we have a clean
"relabel this file" API.
For the bootc-owned containers-storage we don't want
"recursive create dir and relabel" in the general case - we
need to handle upgrades, where there are definitely
non-directories too.
Hence rework the API to just be a clean recursive
relabeling pass, don't attempt to create anything.
While we're here:
- Rework the recursive traversal to operate on shared
single `&mut` path buffers to avoid a heap alloc per directory.
- Add a `bootc internals …
> lsm, imgstorage: Rework relabeling

- lib/src/bootloader.rs
- lib/src/install/baseline.rs
This will depend on https://github.com/coreos/bootupd/pull/839
And cleans up our bootloader code; move the bootloader partition definitions back to `install/baseline`. Conceptually now it's just the `to-disk` flow and bootupd that
know about bootloader partition GUIDs which is how I think it should be - the bootc core is agnostic to bootloaders.
> bootloader: Always pass full path to bootupd

- ostree-ext/src/tar/write.rs
This merged before I pushed an updated version, so follow up:
- Be explicit about also flushing the tar stream, since that can also
have trailing data.
- Remove unneeded comment about passing the input stream
> Comment tidy up from #1228

- docs/src/bootc-install.md
Update the `--via-loopback` example to clarify that this must be run as root.
We already state this at the very top of this document, but this makes it clearer for users who skip directly down to this example command.
> docs: install to-disk --via-loopback requires root

- lib/src/install.rs
Got a report over private chat of
```
ERROR Installing to filesystem: Removing boot directory content: Removing entries (noxdev): Removing entries (noxdev): Removing entries (noxdev): Read-only file system (os error 30)
```
That's ugly, we don't want a context per recursive directory entry. Only add a context at the toplevel invokers.
> install: Avoid context-per-recursion

- docs/src/filesystem.md
The support for this landed in a previous PR,
let's talk about it.
> docs/filesystem: Mention composefs.enabled = verity

- Cargo.lock
- Cargo.toml
- lib/src/mount.rs
- system-reinstall-bootc/src/users.rs
- utils/src/command.rs
No major changes required; we get to drop one `unsafe` call which is nice!
Looks like the ecosystem overall will need a fair bit of porting before we can drop the 0.38 version though.
> Update to rustix 1.0

- MAINTAINERS.md
- README.md
Add OpenSSF Best Practices badge and fix a name typo in Maintainers list.
> Add OpenSSF Best Practices badge

- ostree-ext/src/container/unencapsulate.rs
- ostree-ext/src/tar/write.rs
Followup to #1228
We use the decompressor a couple of times in unencapsulate_base in
addition to the previous fix in filter_tar_async.  Instead of
duplicating the decompressor flush logic in each place, wrap the
decompressor in a struct and implement Drop for it so we always
automatically flush the input stream when we're finished with it.
> unencapsulate: Wrap decompressor and implement Drop

- Cargo.lock
- lib/src/lints.rs
- tests-integration/src/install.rs
- tests-integration/src/selinux.rs
- tests-integration/src/tests-integration.rs
- utils/src/path.rs
Depends: https://github.com/coreos/cap-std-ext/pull/66
---
We have a few code paths which are doing a recursive filesystem
walk and it's much easier with an API like this, especially
when one wants to keep track of the full relative path.
> Update to use walk from cap-std-ext

- lib/src/fixtures/spec-only-booted.yaml
- lib/src/fixtures/spec-ostree-remote.yaml
- lib/src/fixtures/spec-ostree-to-bootc.yaml
- lib/src/fixtures/spec-staged-booted.yaml
- lib/src/fixtures/spec-staged-rollback.yaml
- lib/src/fixtures/spec-v1a1-orig.yaml
- lib/src/fixtures/spec-v1a1.yaml
- lib/src/fixtures/spec-via-local-oci.yaml
- lib/src/spec.rs
- lib/src/status.rs
- lib/src/store/ostree_container.rs
The argument here twofold:
- We used to show it with ostree refs because ostree doesn't have manifest lists
- Actually we do want to highlight that the digest of the image is always the digest of the per-arch image; we currently peel and discard manifest lists, which may not be obvious.
Closes: https://github.com/bootc-dev/bootc/issues/1238
> spec, status: Add architecture

- system-reinstall-bootc/src/podman.rs
The image is always pulled into containers-storage first, so let's use it here to avoid requiring registry keys to be baked into the image.
fixes #1205
> reinstall: Use containers-storage transport

- docs/src/bootc-install.md
- docs/src/man/bootc-install-to-disk.md
- docs/src/man/bootc-install-to-existing-root.md
- docs/src/man/bootc-install-to-filesystem.md
- hack/lldb/deploy.sh
- lib/src/install.rs
- tests-integration/src/hostpriv.rs
- tests-integration/src/install.rs
This deprecates skip-fetch-check in favor of the inverse, run-fetch-check. Updates docs and tests to reflect the change.
---
Spawned from https://github.com/bootc-dev/bootc/pull/1255#discussion_r2033391674. Opening this for discussion. Also, I'm not sure how to properly deprecate an argument so I just took a stab at it.
> install: Deprecate skip-fetch-check, replace with run-fetch-check

- Cargo.lock
- deny.toml
- lib/src/cli.rs
- lib/src/fsck.rs
- ostree-ext/Cargo.toml
- ostree-ext/src/fsverity.rs
~...and a bunch of probably-unnecessary changes to cargo lockfiles~
~Don't merge this yet: the composefs-rs revision isn't merged yet.~
> various: adapt to new composefs-rs fsverity API

- Cargo.lock
- system-reinstall-bootc/Cargo.toml
- system-reinstall-bootc/src/main.rs
- system-reinstall-bootc/src/prompt.rs
See commit messages, just some prompt tweaks to clarify usage of system-reinstall-bootc.
Closes: https://github.com/bootc-dev/bootc/issues/1269
> Reinstall prompt tweaks

- docs/src/filesystem.md
- Doesn't apply to LBIs, and actually c/storage has no knob for this
- Elaborate a bit on /etc and /var
> docs/filesystem: Explain a little bit more about fsverity

- tmt/tests/test-00-bootc-install.sh
In the test suite, pass the `--acknowledge-destructive` flag to `bootc install to-existing-root` to avoid the 20 second timer.
> test: Use to-existing-root --acknowledge-destructive

- lib/src/lints.rs
I guess this got misplaced somewhere along the way while reorganizing
the lint code, but I just now noticed it while browsing the code.
Also removed bit about "if it does not exist error", because that's
not accurate with the present behavior of the lint.
> lints: move misplaced docstring for LINT_VAR_RUN

- Cargo.lock
- Cargo.toml
- lib/Cargo.toml
- lib/src/bootloader.rs
- lib/src/install.rs
- lib/src/install/baseline.rs
- lib/src/lib.rs
- mount/Cargo.toml
- mount/src/mount.rs
Prep for using this elsewhere via git dependency, like we're doing now with bootupd for example.
> Split mount code into separate helper crate

- lib/src/status.rs
See https://github.com/bootc-dev/bootc/pull/1285
> status: Prep work for https://github.com/bootc-dev/bootc/pull/1285

- Makefile
- contrib/scripts/fedora-bootc-destructive-cleanup
- lib/src/cli.rs
- lib/src/install.rs
- system-reinstall-bootc/src/podman.rs
- systemd/bootc-destructive-cleanup.service
This will remove all rpms and containers/images from the previous install (found in /sysroot) on reboot after running `install to-existing-root.`
---
WIP: using this PR to test the rpm build
> Add alongside-cleanup systemd service

- lib/src/install.rs
Closes: https://github.com/bootc-dev/bootc/issues/1292
Basically we were doing the `/proc/1/root/var/tmp` trick for `/var/tmp` because we didn't have the dynamic bind mount infrastructure before. Now we do, so use it instead.
The specific motivation is that Go in some cases uses `EvalSymlinks` which gets confused by the `/proc/<pid>/root` magic links.
Also, this deletes a lot of code.
> install: Do a dynamic mount for /var/tmp

- system-reinstall-bootc/src/podman.rs
This enables `RUST_LOG=trace system-reinstall-bootc <image>` to print trace messages for the bootc install invocation.
> reinstall: Pass RUST_LOG env var into bootc install container

- system-reinstall-bootc/src/main.rs
- utils/src/command.rs
This makes it easier to copy/paste (and read) the `podman ... bootc install ...` command from the CLI output.
> reinstall: Cleaner formatting of podman bootc install message

- ostree-ext/src/container/store.rs
We're seeing a bug and I think this additional tracing will help.
> store: Add some more debug tracing

- lib/src/deploy.rs
- lib/src/spec.rs
Closes #1165
Performs tag-stripping when the image reference contains both 
a tag and digest.  This allows Skopeo to pull the image 
successfully, while still displaying both the tag + digest inside 
`bootc status`.
---
This does still perform unnecessary actions when switching onto the same image selected via digest, and there's an issue to tackle this no-op deployment here - #205
I chose to keep this logic inside bootc itself, rather than pushing it up to ostree_ext since this same logic will likely be required for the upcoming composefs integration. 
Since there's a separate argument for the transport, I am not accounting for the image ref containing the transport. 
e.g. `containers-storage:quay.io/example/someimage:42@sha256:blah`
```
bootc-switch-to-tag-with-digest on  …
```
> feat(switch): support tag + digest image reference

- utils/src/command.rs
- utils/src/path.rs
utils: PathQuotedDisplay: Avoid quoting more characters
This makes the output of command rendering much nicer.
---
utils: Strengthen quoted testing
Verify we see exactly one token.
---
> Dont quote me on this

- Cargo.lock
- lib/Cargo.toml
* reinstall: Pass RUST_LOG env var into bootc install container by @ckyrouac in https://github.com/bootc-dev/bootc/pull/1297
* reinstall: Cleaner formatting of podman bootc install message by @ckyrouac in https://github.com/bootc-dev/bootc/pull/1298
* store: Improve logging for filtered content by @cgwalters in https://github.com/bootc-dev/bootc/pull/1274
* test: Use to-existing-root --acknowledge-destructive by @evan-goode in https://github.com/bootc-dev/bootc/pull/1279
* lints: move misplaced docstring for LINT_VAR_RUN by @jeckersb in https://github.com/bootc-dev/bootc/pull/1290
* fsck: Don't run ostree fsck by @cgwalters in https://github.com/bootc-dev/bootc/pull/1287
* Port from once_cell to std by @cgwalters in https://github.com/bootc-dev/bootc/pull/1283
* Split mount code into …
> Release 1.1.8

- lib/src/spec.rs
The previous code in trying to parse `oci` was wrong; the syntax for an `oci` transport is the same as oci-archive, which includes a file path (and there's no mechanism to quote `:` note).
The canonical logic for all of this stuff is in Go, there's no canonical Rust library (yet, though I did think about putting this in oci-spec).
Previous to this attempt to handle tagged+digested, we weren't parsing image references at all.
First, factor out a `canonicalize_reference` helper since that's what we're really doing here, it's independent of the *transport*.
Fix the canonicalize function to drop out trying to parse `oci`.
Add a separate test case that incorrectly passes just so it's a bit more obvious to fix this later.
Note that today at least `skopeo` rejects trying to fetch via …
> spec: Note we don't canonicalize oci

- docs/src/filesystem.md
Ref https://gitlab.com/fedora/bootc/examples/-/merge_requests/59#note_2500726902
> filesystem: Note initramfs reneneration is required for prepare-root

- Cargo.lock
- mount/src/mount.rs
- system-reinstall-bootc/Cargo.toml
- system-reinstall-bootc/src/btrfs.rs
- system-reinstall-bootc/src/lvm.rs
- system-reinstall-bootc/src/main.rs
- system-reinstall-bootc/src/prompt.rs
@cgwalters this is a rough outline of what I'm planning to do to guide the user to handle their mounted filesystems. I'm not sure which mounts we should list though. This code correctly shows the `/home` mount from a Fedora workstation install but I'm sure there are other cases I'm missing.
(I'm also trying to figure out a more functional way to parse the filesystems)
> Reinstall mount warning

- lib/src/fixtures/spec-only-booted.yaml
- lib/src/fixtures/spec-ostree-remote.yaml
- lib/src/fixtures/spec-ostree-to-bootc.yaml
- lib/src/fixtures/spec-rfe-ostree-deployment.yaml
- lib/src/fixtures/spec-staged-booted.yaml
- lib/src/fixtures/spec-staged-rollback.yaml
- lib/src/fixtures/spec-v1a1-orig.yaml
- lib/src/fixtures/spec-v1a1.yaml
- lib/src/fixtures/spec-via-local-oci.yaml
- lib/src/spec.rs
- lib/src/status.rs
- tmt/tests/booted/readonly/001-test-status.nu
As we head towards factory reset work, this will be of critical importance.
For now this only shows up in the API, not in human readable status.
> spec: Add stateroot

- Makefile
- ostree-ext/src/container/deploy.rs
In some cases rust-analyzer seems to be building without the `bootc` feature which triggers some unused variable warnings here.
> ostree-ext: Squash some unused warnings

- lib/src/store/mod.rs
Check for the policy csum to make sure there is actually a policy available to lookup when trying to label the bootc container storage.
Fixes #1303
> install: Fallback to no sepolicy when init imgstore

- lib/src/fixtures/spec-booted-pinned.yaml
- lib/src/spec.rs
- lib/src/status.rs
Part of #904
Displays pinned deployments as part of "bootc status".
Includes unit tests to ensure correct parsing of the
pinned deployments, and that they are displayed in
human readable formats correctly.
---
Please find below how they look in both human and machine readable formats.
When the staged, booted or rollback deployments are pinned, the information is _not_ duplicated in the outputs.  
Please let me know if this output format is alright, or if you'd prefer some changes.
Human readable:
```
❯ sudo ./target/debug/bootc status          
[sudo] password for admin: 
● Booted image: ghcr.io/rsturla/eternal-linux/lumina:42-nvidia-open
Digest: sha256:fa8a2a7212a110caedb3729d70513fbcd518c4ed3f011ff16f4531b3b7a4d60e (amd64)
Version: 250507 (2025-05-07T01:44:43Z)
Pinned: yes
Rollback …
```
> feat(status): display pinned deployments

- .dockerignore
- .github/workflows/ci.yml
- hack/Containerfile
- hack/build.sh
Main motivation: I was looking at making more changes here
- Use an idiom I'd like to standardize more of copy context to `FROM scratch` image which is then mounted and consumed in other phases by mounting. This helps avoid polluting later containers with intermediate copied files.
- Change `build.sh` to handle being run from any directory
- Drop the `dev-rootfs` stuff as it's weird and awkward; instead we should encourage multi-step builds deriving from this image
- Don't make `bootc.tar.zst` only to immediately untar it; just use `COPY` from the build container
- Use heredocs to condense multiple `RUN` invocations to avoid pointless small layers
> hack: Rework+cleanup container build

- README.md
> README.md: Add versioning/semver standards

- ostree-ext/tests/it/main.rs
Just something weird I noticed when looking at #1328
> ostree-ext: tests: Don't call export_container twice

- lib/src/cli.rs
- lib/src/fsck.rs
- lib/src/lints.rs
- ostree-ext/src/container/store.rs
- utils/src/iterators.rs
Useful when running automatic reports and analyses
where all issues need to be visible at once without truncation.
To do this we needed to add a LintExecutionConfig to
propagate configuration through the lint system.
Also, refactor how we print things so there's a
shared helper functions for consistent formatting with and without truncation.
Closes: https://github.com/bootc-dev/bootc/issues/1260
> lints: Add --no-truncate flag to bootc container lint 

- lib/src/spec.rs
Our parser here doesn't handle complex cases that may specify c/storage options, as used by bootc-image-builder for example.
Closes: https://github.com/bootc-dev/bootc/issues/1308
> spec: Don't canonicalize containers-storage

- Cargo.lock
- lib/src/install.rs
- lib/src/status.rs
- lib/src/store/ostree_container.rs
- ostree-ext/src/container/encapsulate.rs
- ostree-ext/src/container/store.rs
- ostree-ext/src/fixture.rs
- utils/Cargo.toml
- utils/src/lib.rs
- utils/src/timestamp.rs
OciDir push_layer() calls push_layer_full() with
created = chrono::offset::Utc::now()
This should fix https://github.com/coreos/rpm-ostree/issues/5406
> ostree-ext: make OCI history reproducible

- docs/src/SUMMARY.md
- docs/src/bootloaders.md
> docs: Add bootloaders.md

- .github/workflows/ci.yml
- system-reinstall-bootc/src/main.rs
- system-reinstall-bootc/src/podman.rs
- tests-integration/src/system_reinstall.rs
This enables using a local image with system-reinstall-bootc. A couple drive by cleanups to the integration tests are included.
> reinstall: Only pull the image if it's not already present

- tmt/README.md
This PR adds a README file to explain how to run the integration tests on a local machine.
> test: Add README.md in tmt folder for integration test local running

- ostree-ext/src/chunking.rs
- ostree-ext/src/container/unencapsulate.rs
Description:  
This pull request makes small corrections to comments and documentation in the codebase. Specifically, it fixes a typo in the word "structure" in `chunking.rs` and corrects the spelling of "dependency" in `unencapsulate.rs`. No functional changes are introduced; these updates are purely for clarity and accuracy in the documentation.
> Minor Documentation and Comment Corrections

- docs/src/building/kernel-arguments.md
- Changes via `rpm-ostree kargs` will persist, this came up as a question
- Explicitly mention the `unshare -m` trick
- Emphasize a bit more bootc+rpm-ostree do interoperate; except for removing things added by `/usr/lib/bootc/kargs.d`, don't do that
> kargs: Clarify a bit more

- docs/src/filesystem-sysroot.md
- docs/src/relationship-particles.md
Description:  
This pull request addresses minor issues in the documentation by correcting typos and improving formatting for clarity and consistency. Specifically:
- Fixed a typo in the word "implemented" in `docs/src/relationship-particles.md`.
- Improved the formatting of the section title "Growing the filesystem" in `docs/src/filesystem-sysroot.md` for better readability.
No functional changes were made to the codebase; these are documentation improvements only.
> Fix Typos and Improve Formatting in Documentation

- Cargo.lock
- lib/Cargo.toml
> Release 1.4.0

- docs/src/building/guidance.md
- docs/src/building/users-and-groups.md
Description:  
This pull request corrects minor typographical errors in the documentation files guidance.md and users-and-groups.md. Specifically, it fixes the spelling of "encouraged" and "beginning" to improve clarity and professionalism in the documentation. No functional changes are introduced.
> Fix Typos in Documentation

- Cargo.lock
- ostree-ext/Cargo.toml
- ostree-ext/src/container/encapsulate.rs
- ostree-ext/src/container/store.rs
- ostree-ext/src/container/update_detachedmeta.rs
- ostree-ext/src/fixture.rs
- ostree-ext/src/integrationtest.rs
- ostree-ext/tests/it/main.rs
- tests-integration/Cargo.toml
Mostly just keeping up with things, but this is also prep for us using `GetRawBlob`.
> Bump to newer ocidir and containers-image-proxy

- lib/src/deploy.rs
- tmt/tests/booted/test-image-pushpull-upgrade.nu
When staging a new deployment, create /run/reboot-required to signal that a reboot is needed. This file is monitored by kured (Kubernetes Reboot Daemon) and other tools to detect when a system needs to be rebooted.
This makes it easier to integrate bootc with kured and similar tools without requiring manual configuration or bridging.
Fixes: [#1353](https://github.com/bootc-dev/bootc/issues/1353)
> Create /run/reboot-required by default

- docs/src/host-v1.schema.json
- docs/src/man/bootc-container-lint.md
- docs/src/man/bootc-container.md
- docs/src/man/bootc-edit.md
- docs/src/man/bootc-install-ensure-completion.md
- docs/src/man/bootc-install-finalize.md
- docs/src/man/bootc-install-print-configuration.md
- docs/src/man/bootc-install-to-disk.md
- docs/src/man/bootc-install-to-existing-root.md
- docs/src/man/bootc-install-to-filesystem.md
- docs/src/man/bootc-install.md
- docs/src/man/bootc-rollback.md
- docs/src/man/bootc-status.md
- docs/src/man/bootc-switch.md
- docs/src/man/bootc-upgrade.md
- docs/src/man/bootc-usr-overlay.md
- docs/src/man/bootc.md
- xtask/src/xtask.rs
> docs: Update generated

- GOVERNANCE.md
- README.md
> README.md: Add details for Friday Zoom meeting

- docs/src/building/secrets.md
- Note the existence of `/run` here
- Describe how to use `podman login --authfile` to write it
- Also describe the pattern of symlinking to keep things in sync where desired
> secrets: Expand on authfile

- Cargo.lock
- blockdev/Cargo.toml
- cli/Cargo.toml
- lib/Cargo.toml
- mount/Cargo.toml
- ostree-ext/Cargo.toml
- system-reinstall-bootc/Cargo.toml
- sysusers/Cargo.toml
- tmpfiles/Cargo.toml
- utils/Cargo.toml
See https://github.com/coreos/bootupd/pull/963
Basically I just want a way to keep these in sync with bootupd; we're not attempting to make a truly public library.
> Rework utils and blockdev crates as -internals in prep for publishing

- Cargo.lock
- Cargo.toml
- ostree-ext/Cargo.toml
- Bump composefs so we build on s390x and ppc64le
- use-libc for rustix so we will always work the same across every platform
> Bump composefs-rs and use-libc for rustix

- crates/ostree-ext/src/container/store.rs
- crates/ostree-ext/src/container/unencapsulate.rs
- crates/ostree-ext/src/generic_decompress.rs
- crates/ostree-ext/src/lib.rs
- crates/ostree-ext/src/tar/write.rs
For things like GzDecoder, we don't want to read via the actual
decompression reader because we don't care about decompressing at this
point.  Plus, the inner reader may have encountered an error partway
through, and trying to decode via decompression will error with
UnexpectedEof.
Instead, wrap a reader for each content type which knows how to get a
mutable reference to the underlying data stream.  When we finish
decompressing, read directly from this "inner" stream to flush any
data.
Resolves: #1407
> unencapsulate: use "inner" stream when finishing Decompressor

- Cargo.lock
- crates/blockdev/Cargo.toml
- crates/blockdev/src/blockdev.rs
- crates/lib/src/cli.rs
- crates/lib/src/lib.rs
This commit implements issue #799 by creating a signal-safe cleanup helper for loopback devices to prevent resource leaks when bootc install --via-loopback is interrupted by signals like SIGINT (Ctrl-C).
The solution uses an 'out-of-process drop' helper that:
- Forks a cleanup helper process when creating a loopback device
- Uses PR_SET_PDEATHSIG to detect when the parent process dies
- Masks most signals to avoid being killed accidentally
- Automatically cleans up leaked loopback devices if the parent dies
- Gracefully terminates when the parent performs normal cleanup
This prevents the common issue where interrupting bootc install --via-loopback with Ctrl-C would leave /dev/loopN devices allocated on the system.
Fixes: https://github.com/bootc-dev/bootc/issues/799
> blockdev: Fix loopback device resource leak on signal interruption

- Cargo.lock
- crates/blockdev/Cargo.toml
- crates/blockdev/src/blockdev.rs
- crates/lib/src/cli.rs
- crates/lib/src/lib.rs
This reverts commit c2c918cc805fe5cfcc9434e4da419b98460abb60.
As it makes install to-disk fail:
https://github.com/bootc-dev/bootc/issues/1439
> Revert "blockdev: implement signal-safe loopback device cleanup helper"

- Cargo.lock
- crates/lib/src/cli.rs
- crates/ostree-ext/Cargo.toml
- crates/ostree-ext/src/fsverity.rs
Also pull in `composefs-boot` and `composefs-oci`
> Bump composefs-rs

- crates/lib/src/cli.rs
- crates/ostree-ext/src/fsverity.rs
To paper over the fork-vs-fsverity issue a bit
more.
> fsverity: use _with_retry

- crates/lib/src/bootloader.rs
- crates/lib/src/install.rs
Tell bootupctl to load components from the deployed image rather than expecting we are running in the container (or assume that the buildroot is the container.)
As the image content is already deployed at this stage, pointing to it makes it work in both scenarios (different buildroot or running from the container.)
Fixes https://github.com/bootc-dev/bootc/issues/1455
> install: use deployed sysroot as root for bootloader install

- ADOPTERS.md
to the ADOPTERS.md. We have builds dating all the way back to 2022.
> docs: add Playtron GameOS

- crates/blockdev/src/blockdev.rs
- crates/lib/src/cli.rs
- crates/lib/src/install.rs
- crates/lib/src/install/baseline.rs
- crates/lib/src/lib.rs
- crates/lib/src/lsm.rs
- crates/lib/src/podman.rs
- crates/ostree-ext/src/container/deploy.rs
- crates/utils/src/lib.rs
- crates/utils/src/reexec.rs
Prep for fixing https://github.com/bootc-dev/bootc/issues/1434
Basically in the selinux path we copy our binary to a tempfile, which breaks `/proc/self/exe`.
Fix this by setting an environment variable when we do that re-exec and ensuring that *everything* references an internal API (now moved to utils/ so it can be shared) that looks for the env var first.
> tree-wide: Clean up our re-exec path

- tmt/plans/integration.fmf
- tmt/tests/booted/test-image-upgrade-reboot.nu
- tmt/tests/test-24-local-upgrade-reboot.fmf
This uses the existing `test-20-local-upgrade.fmf` with a lot of the unneeded tests stripped out.  
It builds a bootc OCI image, switches into it with an `--apply` flag and validates both a reboot occurred, and that kargs from the new image are applied.
> test: add integration tests for 'bootc switch --apply'

- .github/workflows/scheduled-release.yml
Since there is some user intervention required for the scheduled release, this adds a 2 day buffer in case the buttons weren't clicked immediately last time.
> ci: Shorten the release interval to 19 days

- docs/src/filesystem.md
Add comprehensive documentation for the `root.transient-ro` option that allows privileged users to create dynamic top-level mountpoints at runtime while keeping the `filesystem` read-only by default.
> docs: add documentation for root.transient-ro feature

- crates/lib/src/reboot.rs
It was not a useful abstraction in the end, just remove it.
While here, also extend a comment with rationale for why we sleep.
> reboot: Drop use of Task

- docs/src/SUMMARY.md
- docs/src/bootc-in-container.md
Closes: https://github.com/bootc-dev/bootc/issues/1461
> docs: We're read only by default in a container

- crates/lib/src/install.rs
- crates/lib/src/kernel.rs
This adds a new `kernel::Cmdline` struct, which is populated either
via `Cmdline::from` (borrowed) or `Cmdline::from_proc` (owned).
This attempts to follow the same behavior as the kernel, which is
mostly covered in:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/lib/cmdline.c?id=e8d780dcd957d80725ad5dd00bab53b856429bc0#n227
The algorithm is basically:
- Scan forward until you find the first unquoted isspace()
byte. That's the end of the param.
- If you encounter an `=` along the way, note where. That's where it
will terminate the key and split for the value. Any future `=` are
not treated as special.
- The value can be quoted to allow spaces, but is unquoted only in as
much as `"` is removed from the first or last byte. You can still
have `"` in the middle of the …
> Improve kernel argument parsing

- crates/lib/src/install.rs
> install: Use read_file from composefs-boot

- crates/blockdev/src/blockdev.rs
Adds the missing `internals` subcommand when spawning `loopback-cleanup-helper` so it runs as intended during `bootc install --via-loopback`. Without `internals`, the helper fails with `unrecognized subcommand 'loopback-cleanup-helper'`, preventing loop device cleanup. This doesn’t block install/boot because the helper is fire-and-forget, but it leaves loop devices uncleared.
Fixes: #1510
> fix(blockdev): include "internals" when spawning loopback-cleanup-helper

- .github/scripts/assign_reviewer.py
Use `gh pr edit` for reviewer assignment to avoid JSON formatting issues
We saw the error when assigning reviewers: `For 'properties/reviewers', "[\"ckyrouac\"]" is not an array. (HTTP 422)`
> fix: simplify reviewer assignment using gh pr edit

- Dockerfile
- tmt/tests/bootc-install-provision.sh
This is a hackaround for https://gitlab.com/redhat/centos-stream/containers/bootc/-/issues/1174
> ci/tmt: distro-sync ostree

- crates/system-reinstall-bootc/src/prompt.rs
We're seeing a CI failure where the final reinstall message isn't seen, I think this might fix it.
> system-reinstall-bootc: Ensure stdout is flushed

- Cargo.lock
- crates/lib/Cargo.toml
- crates/lib/src/lib.rs
- crates/lib/src/parsers/bls_config.rs
- crates/lib/src/parsers/grub_menuconfig.rs
- crates/lib/src/parsers/mod.rs
Some prep work for merging the composefs-backend branch.
> Map grub feature to composefs-backend and import parser/bls

- crates/lib/src/cli.rs
- crates/lib/src/deploy.rs
- crates/lib/src/spec.rs
- crates/lib/src/status.rs
- crates/ostree-ext/Cargo.toml
- crates/ostree-ext/src/lib.rs
- tmt/plans/integration.fmf
- tmt/tests/booted/test-soft-reboot.nu
- tmt/tests/test-25-soft-reboot.fmf
Closes: https://github.com/bootc-dev/bootc/issues/1350
depends on
> lib: add support for soft-reboots

- crates/lib/src/install.rs
- crates/ostree-ext/src/bootabletree.rs
This allows you to set a non-default ostree bootloader backend.  In particular, this is needed for aboot images, as otherwise  the deploy will not shell out to aboot-deploy to create the required A/B boot symlinks.
PR includes a fix to make aboot-deploy actually work.
> install: Automatically configure aboot

- MAINTAINERS.md
Feel free to adjust wording as needed, this is just an example.
This is a good way to empower PMs other folks to be able to help out with meta things around the project. We explicitly list the the role in governance so that the people listed here end up in the main cncf maintainers.csv.
Being in the csv file is important because it is a check the CNCF uses to ensure maintainers are requesting the resources. And for CFP submissions, "did one of the maintainers submit this talk or was it someone else?", etc.
> governance: add community manager role

- Cargo.lock
- crates/initramfs/Cargo.toml
- crates/initramfs/src/mount.rs
Add error contexts to functions. Create wrappers around intrenal functions with error context added.
Also make `/etc` a bind mount
> initramfs: Better error handling

- crates/initramfs/src/lib.rs
- crates/initramfs/src/main.rs
Create a lib.rs as we'd like to utilize these functions elsewhere in the codebase
Also: Prep for https://github.com/bootc-dev/bootc/pull/1560
> initramfs: Convert to library

- Cargo.lock
- Cargo.toml
- crates/lib/src/boundimage.rs
- crates/lib/src/cli.rs
- crates/lib/src/deploy.rs
- crates/lib/src/install.rs
- crates/lib/src/install/completion.rs
- crates/ostree-ext/src/container/deploy.rs
- crates/utils/Cargo.toml
- crates/utils/src/tracing_util.rs
Log key operations (deploy, upgrade, switch, install, etc.) to systemd journal with structured fields including image references, digests, and operation types. Uses existing journal infrastructure and follows ostree logging patterns.
> Add systemd structured logging for bootc state changes

- Makefile
> Makefile: Create storage symlink as relative

- Cargo.lock
- crates/cli/Cargo.toml
- crates/cli/src/main.rs
- crates/system-reinstall-bootc/Cargo.toml
- crates/system-reinstall-bootc/src/main.rs
- crates/utils/Cargo.toml
- crates/utils/src/lib.rs
As part of the tracing-subscriber CVE I did a quick audit for usages of `tracing::error!` and I noticed when we updated the `main()` function in the primary
crate we missed also doing the same for system-reinstall-bootc.
Move the handling of that to utils.
xref: https://bugzilla.redhat.com/show_bug.cgi?id=2392017
> Deduplicate main error printing

- crates/lib/src/cfsctl.rs
- crates/lib/src/cli.rs
For image building, we want to be able to run this on a non-bootc host
or in a container.  There we'll manipulate the composefs repo in a
provided tempdir.
> cfs: only get sysroot storage when repo is not supplied

- Cargo.lock
- crates/etc-merge/Cargo.toml
- crates/etc-merge/src/lib.rs
- crates/lib/Cargo.toml
- crates/lib/src/cli.rs
> Implementation for /etc merge

- crates/lib/src/deploy.rs
- tmt/tests/booted/test-image-pushpull-upgrade.nu
This change updates the /run/reboot-required file to include information
about the staged bootc image. This will provide users with information
about what bootc image will be effective after the system has been
rebooted.
Fixes #1574
> Update reboot-required file with information about the staged image

- crates/lib/src/cli.rs
- crates/lib/src/install.rs
- crates/lib/src/lsm.rs
- crates/utils/src/lib.rs
- crates/utils/src/reexec.rs
- crates/utils/src/tracing_util.rs
I went to look at our journal logging and it didn't do what I expected.
The intention was to always log to the systemd journal,
even if we're spawned directly on the CLI outside of a unit.
> log to journal if root

- crates/lib/src/cli.rs
- crates/lib/src/install.rs
- crates/lib/src/spec.rs
- crates/lib/src/status.rs
Fix Grub boot error caused by https://github.com/bootc-dev/bootc/pull/1541. Introduce a `--bootloader` cli option to `--composefs-native`. Depending upon the type of bootloader passed in we write BLS configs respectively
> composefs-native/boot: Handle systemd-boot and grub

- crates/kernel_cmdline/src/lib.rs
This moves the bulk of the parsing logic into `Parameter`.  Its
`parse` method returns a 2-tuple, its items being:
1.  An `Option<Parameter>` which contains the parsed `Parameter`.
This will be `None` if the provided input is empty or contains only
whitespace.
2.  A byte slice of the rest of the input which was not consumed by
the yielded `Parameter`.
This also adds new tests for some cases that would fail under the
previous parser implementation.
> kernel_cmdline: Refactor parsing to improve quote and whitespace handling

- .dockerignore
- Cargo.lock
- Dockerfile
- crates/xtask/Cargo.toml
- crates/xtask/src/man.rs
- crates/xtask/src/xtask.rs
Closes: https://github.com/bootc-dev/bootc/issues/1627
> Fix man page generation

- crates/lib/Cargo.toml
- crates/lib/src/fsck.rs
- crates/lib/src/progress_jsonl.rs
- crates/ostree-ext/src/generic_decompress.rs
- **rust-1.90: Fix warnings on unnecessary parentheses**
- **rust-1.90: Remove newly-detected dead code**
- **rust-1.90: Update MSRV to 1.84.0**
Closes: https://github.com/bootc-dev/bootc/issues/1605
> Fixes for rust 1.90

- .github/workflows/ci.yml
- .github/workflows/integration.yml
- CONTRIBUTING.md
- Dockerfile
- Justfile
- Makefile
- contrib/packaging/fedora-extra.txt
- crates/etc-merge/src/lib.rs
- crates/xtask/src/xtask.rs
The emphasis here is on trying to have
the `Justfile` be the default entrypoint,
wrapping other tools.
- Replace mentions of podman-bootc with bcvk
since I hope the latter supercedes the former
- Unify the unit test entrypoint
- Set up /var/tmp as a tmpdir to fix the etc merge
test (otherwise, selinux failures w/tmp)
- Run the unit+container tests in integration.yml
- Have `just validate` run in a container
Closes: https://github.com/bootc-dev/bootc/issues/1635
> Updates to build sys and CONTRIBUTING.md

- contrib/packaging/bootc.spec
> specfile: Handle updated macros in c9s rust-toolset

- crates/initramfs/src/lib.rs
- crates/lib/src/bootc_composefs/state.rs
- crates/lib/src/cli.rs
Similar to ostree, mount a transient overlayfs on /usr
> composefs-backend: Implement `bootc usr-overlay`

- Dockerfile
- Makefile
- crates/lib/src/generator.rs
- crates/lib/src/install.rs
- crates/tests-integration/src/system_reinstall.rs
- systemd/bootc-destructive-cleanup.service
- systemd/bootc-status-updated-onboot.target
- systemd/bootc-status-updated.path
Right now this service fails in `bcvk run-ephemeral`, but
also likely fails in any non-bootc system that has `subscription-manager`
installed.
A problem is that dependencies of units are started even
if the dependee has a condition that disables it.
This basically the target and path depend on `/run/ostree-booted`
being present (which yes, won't work for composefs...)
Tests: Covered by extant `012-test-unit-status.nu`
>     generator: Conditionally enable bootc-status units

- docs/src/registries-and-offline.md
Changes made:
I create a private registry section to explain where to add `auth.json` file for OCI auth
> docs: Adding a private OCI registry section

- tmt/plans/integration.fmf
- tmt/tests/booted/test-custom-selinux-policy.nu
- tmt/tests/test-27-custom-selinux-policy.fmf
Ensure that if a custom policy is added in a
Containerfile, the resulting deployment has the expected
labels as well.
>  tests: add custom selinux policy test

- crates/system-reinstall-bootc/src/config/mod.rs
- crates/system-reinstall-bootc/src/main.rs
- crates/tests-integration/src/container.rs
I wanted to add a CLI option here to avoid the reboot, and ran into the fact that our option parsing was suboptimal to start with.
We never documented `BOOTC_REINSTALL_CONFIG` at all...I'm kind of tempted to deprecate it.
> system-reinstall-bootc: Handle --help

- .github/workflows/ci.yml
Recent podman versions got stricter about not doing overlay-on-overlay by default.
> install: Add a tmpfs for /var/lib/containers

- docs/src/filesystem-sysroot.md
- docs/src/package-managers.md
> Expand/consolidate "detecting bootc"

- Cargo.lock
- crates/system-reinstall-bootc/Cargo.toml
- crates/system-reinstall-bootc/src/btrfs.rs
- crates/system-reinstall-bootc/src/config/mod.rs
- crates/system-reinstall-bootc/src/lvm.rs
- crates/system-reinstall-bootc/src/main.rs
- crates/system-reinstall-bootc/src/podman.rs
- crates/system-reinstall-bootc/src/prompt.rs
- crates/system-reinstall-bootc/src/users.rs
If the system has a swap partition (or any other volume which is not
currently mounted) the `findmnt` command will (expectedly) fail to
find it.  Don't early exit in this case, instead just ignore that
volume.  If it wasn't mounted in the first place, we don't need to
warn about it being unmounted after the reinstall operation is
complete.
Closes: #1659
> system-reinstall-bootc: Do not warn on unmounted LVM volumes

- .dockerignore
> dockerignore: Workaround for podman bug with secrets + remote

- hack/Containerfile.packit
- hack/packit-reboot.yml
- hack/provision-packit.sh
- tests/run-tmt.sh
- tmt/plans/integration.fmf
In Fedora or OSCI dist-git gating, SRPM is the only way to get test code. Change to extracting SRPM to get source code. That works with both Packit and dist-git gating.
This PR also includes a `when: running_env != unify` in prepare to make it only runs on Packit or dist-git gating test. In our case, `unify` means running on Github CI or locally.
> test: Use SRPM as test code source to work with gating test
