bootc-dev/bootc

- README.md
Closes: https://github.com/containers/bootc/issues/8
> README.md: Add a decription of relationship with rpm-ostree

- lib/src/status.rs
This reduces duplication between the JSON and `println!` paths.
> status: Use both C struct and gathered info consistently

- lib/src/cli.rs
- lib/src/status.rs
Add an API to gather our extra metadata from a single deployment, such as the supported status.  Use it in the status path and the upgrade path, instead of gathering the supported state separately.
> Also use DeploymentStatus for upgrade

- lib/src/cli.rs
> cli: Use the new exported cli functions from ostree-ext

- README.md
Also using this as a canary to test the new CI.
> README.md: Add a status note

- lib/Cargo.toml
- lib/src/status.rs
- tests/kolainst/basic
In preparation for https://github.com/ostreedev/ostree-rs-ext/pull/454
> Use version API from ostree-ext

- .github/workflows/docs.yml
- README.md
- docs/index.md
README.md: Fix cmdline for install
---
docs: Start adding some
---
> docs: Start adding some

- lib/src/install.rs
A random hardcoded 4G size makes no sense.  Change things to use all space by default.
I ran out of space when trying to install a desktop system this way.
Add a TODO to add a *relative* size option too for better ergonomics.
> install: Consume all space for root by default

- .github/workflows/ci.yml
- ci/lints.sh
- xtask/src/xtask.rs
xtask: Clean up CLI dispatch
Tempting to use clap, but it's heavyweight...
---
ci: Move lints into xtask
Honestly just to reduce the code statistics; be nice to have
zero shell script in the repo 😃
---
> ci: Move lints into xtask

- lib/src/install.rs
We should use cap-std where we can for all the usual reasons; we're juggling two root filesystems.
> install: Also hold a fd open on target root

- lib/src/install.rs
- lib/src/task.rs
This is nicer than using absolute paths where we can.
> task: Add root parameter

- lib/src/install.rs
task: Add root parameter
This is nicer than using absolute paths where we can.
---
install: Clean up filesystem finalization
- Don't trim *all* mounted filesystems, just the ones we mount
- Move code into a helper function
- Add some comments/docs
---
> install: Two minor cleanups

- Makefile
- ci/Dockerfile.fcos
- ci/run-kola.sh
ci: Enable all features
---
ci: Use `cosa kola` to pick up `ARTIFACT_DIR` handling
So I can see the logs in Prow.
---
> ci: Two small fixes

- lib/Cargo.toml
- lib/src/install.rs
Prep for re-exec work where we need to save state.
> install: Make install config serializable

- lib/src/install.rs
We need to be able to use this in more places; rework things so that we have a handy function.
> install: Refactor selinux re-execution more

- lib/Cargo.toml
- lib/src/cli.rs
- lib/src/install.rs
This came up in chat. The error message right now is pretty obscure, we fail in `chcon` which might make you think something is wrong with SELinux.
> install: Verify we're root

- lib/src/install.rs
It only appeared to kind of work because we ended up with a copy of the host rootfs for some reason.
As the comment in the code indicates, what we're really trying to do here is the problem domain covered by
https://brauner.io/2023/02/28/mounting-into-mount-namespaces.html where we want to dynamically insert mounts into a running container.
I was thinking about this and with some experimentation I realized that while we can't change the mount namespacing to make `/tmp` in our container be the same thing as the host `/tmp`, the "magic link" for `/proc/1/root` *will* traverse outside our mount namespace, so it works to just symlink `/tmp` -> `/proc/1/root/tmp`.  It's not beautiful, but it works.
> install: Drop host bind mount code that never worked

- lib/src/install.rs
`ostree container commit` today will delete it, which is arguably a bug.  We then also need to handle the absence of `/var/tmp`.
> install: Handle missing `/var`

- README.md
- docs/install.md
This needs a lot of explanation.  Add a section on how to configure SSH keys.
> Add docs/install.md

- lib/src/install.rs
- lib/src/lsm.rs
I've opened https://github.com/containers/bootc/issues/83 to track a better fix.
> install: Fall back to `setenforce 0` if needed

- README.md
For example, let's spell out things like the lack of hard dependency on Kubernetes, but alignment with the API types.
> README.md: Elaborate on relationship with podman and kube

- lib/src/install.rs
We want to assume we're pulling from a registry using the source image name by default, so that `bootc upgrade` works out of the box.
> install: Do assume we're pulling from a registry by default

- lib/src/cli.rs
- lib/src/deploy.rs
- lib/src/lib.rs
> Factor out staging/deployment module

- lib/src/cli.rs
This mirrors https://github.com/ostreedev/ostree-rs-ext/pull/515
From looking at cargo bloat.
> lib: Dispatch to monomorphic function

- lib/Cargo.toml
- lib/src/install.rs
> lib: Bump to ostree-ext 0.12, rustix 0.38 

- docs/install.md
> install: Doc `install-to-filesystem --replace=alongside`

- lib/src/cli.rs
- lib/src/status.rs
- Add a bit more to the doc info
- Add explicit warning it's not stable
> cli: Expand on the status of status

- lib/src/install.rs
If we don't have skopeo on the host (and it turns out the default Fedora Workstation install has podman but not skopeo) then we only error out halfway through an install.
Do this upfront to make the error clearer.
> install: Query skopeo upfront

- README.md
- docs/bootc-images.md
> README: Add more information on base images

- lib/src/bootloader.rs
This just leverages logic from
https://github.com/coreos/bootupd/pull/555
which simplifies things.
> Use `bootupctl --auto` in alongside mode

- README.md
- docs/bootc-images.md
> Docs: Updated links referencing project Sagano.

- lib/src/lsm.rs
This was helpful for me when reading the logs.
> lsm: Clarify selinux mode being set

- .github/workflows/ci.yml
- docs/bootc-images.md
- docs/index.md
- tests/kolainst/install
There's a new image location now.
> Update references to centos-boot images

- tests/kolainst/install
Followup to https://github.com/containers/bootc/pull/193
> tests: Verify bootprefix

- .github/workflows/ci.yml
- ci/installdeps.sh
> ci: Add a c9s build

- .github/workflows/ci.yml
> ci: gate clippy on `correctness` and `suspicious`

- lib/src/cli.rs
Closes: https://github.com/containers/bootc/discussions/245
> cli: Document that check doesn't fetch layers

- .github/labeler.yml
> labeler: Fix syntax

- docs/index.md
We now have bootc packaged, so let's just tell people to use that.
> docs: Fix FCOS description

- .github/renovate.json5
The renovate PR spam we're seeing is too much.
> renovate: Group non-major updates

- lib/src/utils.rs
Use the same ordering as systemd.
> utils: Fall back if EDITOR is unset

- lib/src/install.rs
> Add more failure contexts for exec_in_host_mountns

- docs/src/installation.md
The overlap/conflicts between bootc and zincati/ignition are important to understand for that case.
> docs: Elaborate a bit on FCOS

- .github/workflows/docs.yml
> ci/docs: install mdbook-mermaid

- docs/src/installation.md
> docs: Link to Fedora/CentOS bootc

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- docs/book.toml
> ci/docs: Add mdbook-linkcheck

- lib/src/cli.rs
> upgrade: More detailed rpm-ostree modification error msg

- lib/src/cli.rs
> cli: Drop a duplicate rootfs open

- docs/src/filesystem.md
> filesystem: Document timestamp squashing

- lib/src/boundimage.rs
The previous iteration would detect %% in a bound image spec field but it would not transform them into %. This is the only systemd specifier that is allowed in the bound image specs, so they need to be transformed into their parsed value.
> boundimage: Replace %% with % in bound image spec

- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- lib/Cargo.toml
- tests-integration/Cargo.toml
- xtask/Cargo.toml
Prep for addding another crate, where I want to avoid duplicating all the versions again.
> build-sys: Switch to workspace dependencies

- lib/src/install.rs
This makes the code slightly more consise. Not prep for anything, just a cleanup.
> install: Use some fs_utf8 bits

- lib/src/install.rs
Was looking at cleaning up the blockdev stuff a bit more; the unsafe nix ioctl code we have is a bit of a wart. Some searching turns up this use of nix, but rustix exposes what we want here.
(rustix and nix heavily overlap, I think rustix is a bit
better designed, though nix has been doing some breaking
changes to catch up)
> install: Use rustix instead of nix in one place

- lib/src/install.rs
This works around what is arguably a podman bug where it tries to run `mkdir("/etc/containers/networks")` and bails even if the directory exists but is read-only.
This is a currently necessary workaround for having `bootc install` pull bound images.
> install: Ensure /etc/containers is writable

- lib/src/status.rs
> Fix clippy warning with `make validate`

- Cargo.lock
- lib/Cargo.toml
The biggest feature here is the new support for "logically bound images", which is still classified as experimental, but we are very interested in feedback.
> Release 0.1.15

- docs/src/filesystem-sysroot.md
> docs: Fix broken link

- README.md
Adding the logo to the top of the README like the other containers repo projects.
> added bootc logo to README

- lib/src/deploy.rs
> clippy: size is already u64

- tests/e2e/bootc-install.sh
Workaround issue https://github.com/containers/podman/issues/22813
> test: Add workaround for zstd:chunked issue

- Cargo.lock
- lib/Cargo.toml
I skipped 1.1.1 because it looks weird =)
> Release 1.1.2

- lib/src/kargs.rs
I'm experimenting with custom base images and hit on this not existing.
> kargs: Handle when kargs.d doesn't exist

- Cargo.lock
Some updates are being blocked by our incorrect
renovate config. Let's do an update run of everything.
> lockfile: Update(*)

- ostree-ext/Cargo.toml
- ostree-ext/src/container/store.rs
- ostree-ext/src/fixture.rs
- Wire up to workspace lint standards
- Fix a few remaining clippy lints
> ext: Fix a few lints

- lib/src/deploy.rs
- lib/src/status.rs
- ostree-ext/src/container/store.rs
- ostree-ext/tests/it/main.rs
- Fix an unused variable in ostree-ext
- Fix other clippy lints
> Fix various minor lints

- ostree-ext/src/fixture.rs
> ostree-ext: test: fix clippy warning

- docs/src/SUMMARY.md
Closes: https://github.com/containers/bootc/issues/962
> docs: Link to bootc container lint

- .copr/Makefile
> copr: use dnf instead of dnf5

- lib/src/install.rs
Fixes: 84cd0f8e79faf9c8cac3e2fc5da3f3d36aebe3a1
Closes: #1010
> install: Fix cleanup function to remove empty dirs too

- docs/src/relationships.md
I think this info can probably be pieced together from the rest of the docs, but let's add a dedicated section for it. Came up in an internal chat.
> docs/relationships: add section about ostree

- docs/src/experimental-progress-fd.md
- lib/src/progress_jsonl.rs
> Typo fixup for #961

- docs/src/logically-bound-images.md
> docs/lbi: Mention not to configure globally

- docs/src/man/bootc-container-lint.md
- docs/src/man/bootc-install-to-disk.md
- docs/src/man/bootc-install-to-existing-root.md
- docs/src/man/bootc-install-to-filesystem.md
- docs/src/man/bootc-switch.md
- lib/Cargo.toml
- lib/src/cli.rs
- lib/src/lints.rs
Closes: https://github.com/containers/bootc/issues/1065
> lints: Add description and `--list`

- lib/src/lints.rs
This should just be an empty mount point.
Prep for custom base images, where it's quite likely that some tools stick kernel content in there, when we actually expect it in `/usr/lib/modules`.
> lint: Check for /boot

- system-reinstall-bootc/src/users.rs
Solves https://github.com/containers/bootc/issues/1089
See diff for details.
> reinstall: handle loginctl compatibility issues

- system-reinstall-bootc/src/podman.rs
- utils/src/command.rs
> reinstall: Fix the --user option in podman command

- sysusers/src/lib.rs
The libvirt package has this entry with a numeric user but an explicit named group reference:
`u qemu 107:qemu "qemu user" - -`
Fix the parser to handle this.
> sysusers: Handle named group references

- Cargo.lock
- lib/Cargo.toml
A fair numebr of fixes and smaller features here.
> Release 1.1.6

- docs/src/man/bootc-container-lint.md
- docs/src/man/bootc-container.md
- docs/src/man/bootc-edit.md
- docs/src/man/bootc-install-ensure-completion.md
- docs/src/man/bootc-install-finalize.md
- docs/src/man/bootc-install-print-configuration.md
- docs/src/man/bootc-install-to-disk.md
- docs/src/man/bootc-install-to-existing-root.md
- docs/src/man/bootc-install-to-filesystem.md
- docs/src/man/bootc-install.md
- docs/src/man/bootc-rollback.md
- docs/src/man/bootc-status.md
- docs/src/man/bootc-switch.md
- docs/src/man/bootc-upgrade.md
- docs/src/man/bootc-usr-overlay.md
- docs/src/man/bootc.md
> docs: Update generated

- README.md
- docs/_config.yml
- lib/src/lints.rs
> Update links to new docs site

- ostree-ext/src/fixture.rs
- ostree-ext/tests/it/main.rs
To debug https://github.com/containers/bootc/issues/1172
> tests: Diff manifests if digest is different

- MAINTAINERS.md
> Maintainers.md: Update and add users

- README.md
> README.md: Add reference to CNCF Code of Conduct

- MAINTAINERS.md
He'll be at least helping maintain CI and approving issues related to that.
> MAINTAINERS.md: Add henrywang

- ostree-ext/src/container/unencapsulate.rs
Leftovers from the refactor in [#677](https://github.com/ostreedev/ostree-rs-ext/pull/677)
> ostree-ext: unencapsulate: Fix goofy match usage

- ostree-ext/src/container/encapsulate.rs
Currently the encapsulate code assumes it's generating images that match the platform (os+arch) that's running. However, for rpm-ostree we have a use case of performing "rechunking" in a cross-architecture fashion. In the end we don't run any code in that process, it's just manipulating bits, so it's perfectly fine to operate cross-arch.
Allow passing in an override for the generated image platform to facilitate this.
> ostree/encapsulate: Support overriding platform (arch)

- docs/src/filesystem.md
- Move the recommendation for `tmpfiles.d` above the philosophy so it's a bit more obvious
- Reword and clarify the "only applied once" semantic
- Drop the link to the ostree change as it's no longer "new"
Motivated by seeing another question on this.
> docs/filesystem: Reword /var a bit

- ostree-ext/src/container/store.rs
- ostree-ext/src/container/unencapsulate.rs
- ostree-ext/src/tar/write.rs
- Moved standalone `decompressor` function to `Decompressor::new`
- Add finish() method which consumes the Decompressor and does finalization
- Update all existing callers to use finish()
- Update Drop impl to attempt to finish, and panic on failure
- Unit tests for panic+non-panic drop
> unencapsulate: more Decompressor improvements

- lib/src/lsm.rs
Came up in chat around why the admin was seeing `invalid_bootcinstall_testlabel_t` in the logs.
> lsm: Add more comments about the SELinux reexec

- lib/src/deploy.rs
- lib/src/install.rs
Verify there is enough space to pull the bootc image on the ostree repo's disk. Adds pretty_bytes to print the error message in human readable format.
> install: Error out when not enough disk space to pull image

- lib/src/install.rs
- lib/src/store/mod.rs
see commit messages. This is to fix the bug where running `install to-existing-root` continually fails after an initial failure due to low disk space.
> Redeploy bug fix

- Cargo.lock
- lib/Cargo.toml
> Release 1.1.7

- ostree-ext/src/container/store.rs
We thought this code may be related to a bug where layer content was apparently getting lost, though
I don't think it was in the end.
Anyways though, use the same "show first n items from iterator" code that we have in the lint to actually display the filtered state.
> store: Improve logging for filtered content

- lib/src/fsck.rs
ref https://github.com/bootc-dev/bootc/issues/1216
> fsck: Don't run ostree fsck

- Cargo.lock
- ostree-ext/Cargo.toml
- ostree-ext/src/fixture.rs
- ostree-ext/src/globals.rs
- ostree-ext/src/isolation.rs
- ostree-ext/tests/it/main.rs
No major reason, just a drive by thing after discussion of once_cell in composefs-rs.
> Port from once_cell to std

- docs/src/bootc-install.md
- docs/src/filesystem.md
- lib/src/lsm.rs
> docs: fix typos

- Cargo.lock
- lib/src/cli.rs
- ostree-ext/Cargo.toml
Prep for work on the composefs-rs backend.
> Bump composefs-rs

- crates/lib/src/install/osbuild.rs
I've come to the conclusion that Task isn't buying us much value over Command.
I'd like to eventually drop it. This is just getting the ball rolling.
> osbuild: Drop use of Task

- .github/workflows/ci.yml
- Dockerfile
If enabled this pulls in git main of ostree which I want for soft reboot work.
> Dockerfile: Support pulling in the continuous repo

- crates/lib/src/cli.rs
https://github.com/ostreedev/ostree/issues/3503
> cli: hide --soft-reboot as ostree side needs further stabilization
